///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class BloodSugarTemplateCategory {
/*
{
  "id": "447581b4-a59b-4ad5-8331-2f98d492d4d7",
  "name": "Mẫu D2",
  "description": "Cơ sở y tế khuyến nghị của việc đo đường huyết?\r\nGlucose (còn gọi là đường) là nguồn năng lượng chính đi nuôi cơ thể, được chuyển hóa từ các loại thực phẩm mà chúng ta cung cấp cho bản thân mỗi ngày. Trong máu của con người luôn có một lượng Glucose nhất định để đảm bảo việc cung cấp năng lượng cho các hoạt động thường ngày:\r\n90 - 130 mg/dl (tức 5 - 7,2 mmol/l) ở thời điểm trước bữa ăn.\r\nDưới 180 mg/dl (tức 10 mmol/l) ở thời điểm sau ăn khoảng 1 - 2 tiếng.\r\n100 - 150 mg/l (tức 6 - 8,3 mmol/l) ở thời điểm trước khi đi ngủ.\r\nĐo chỉ số Glucose của mình ở những khoảng thời gian đo này và đối chiếu chỉ số cho phù hợp để biết mình có mắc bệnh tiểu đường hay không."
} 
*/

  String? id;
  String? name;
  String? description;

  BloodSugarTemplateCategory({
    this.id,
    this.name,
    this.description,
  });
  BloodSugarTemplateCategory.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toString();
    name = json["name"]?.toString();
    description = json["description"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["name"] = name;
    data["description"] = description;
    return data;
  }
}

