///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class BloodSugarTemplateDetailResponse {
/*
{
  "id": "07dd8935-54ab-4d9c-a2ca-32f8408822ef",
  "name": "Mẫu A1",
  "category": 1,
  "template": 1,
  "isWeekTemplate": true,
  "day": 0,
  "isBeforeBreakfast": true,
  "isAfterBreakfast": false,
  "isBeforeLunch": false,
  "isAfterLunch": false,
  "isBeforeDinner": false,
  "isAfterDinner": false,
  "isBeforeSleeping": false
} 
*/

  String? id;
  String? name;
  int? category;
  int? template;
  bool? isWeekTemplate;
  int? day;
  bool? isBeforeBreakfast;
  bool? isAfterBreakfast;
  bool? isBeforeLunch;
  bool? isAfterLunch;
  bool? isBeforeDinner;
  bool? isAfterDinner;
  bool? isBeforeSleeping;

  BloodSugarTemplateDetailResponse({
    this.id,
    this.name,
    this.category,
    this.template,
    this.isWeekTemplate,
    this.day,
    this.isBeforeBreakfast,
    this.isAfterBreakfast,
    this.isBeforeLunch,
    this.isAfterLunch,
    this.isBeforeDinner,
    this.isAfterDinner,
    this.isBeforeSleeping,
  });
  BloodSugarTemplateDetailResponse.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toString();
    name = json["name"]?.toString();
    category = json["category"]?.toInt();
    template = json["template"]?.toInt();
    isWeekTemplate = json["isWeekTemplate"];
    day = json["day"]?.toInt();
    isBeforeBreakfast = json["isBeforeBreakfast"];
    isAfterBreakfast = json["isAfterBreakfast"];
    isBeforeLunch = json["isBeforeLunch"];
    isAfterLunch = json["isAfterLunch"];
    isBeforeDinner = json["isBeforeDinner"];
    isAfterDinner = json["isAfterDinner"];
    isBeforeSleeping = json["isBeforeSleeping"];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["name"] = name;
    data["category"] = category;
    data["template"] = template;
    data["isWeekTemplate"] = isWeekTemplate;
    data["day"] = day;
    data["isBeforeBreakfast"] = isBeforeBreakfast;
    data["isAfterBreakfast"] = isAfterBreakfast;
    data["isBeforeLunch"] = isBeforeLunch;
    data["isAfterLunch"] = isAfterLunch;
    data["isBeforeDinner"] = isBeforeDinner;
    data["isAfterDinner"] = isAfterDinner;
    data["isBeforeSleeping"] = isBeforeSleeping;
    return data;
  }
}

