import 'package:medical/src/modal/user/schedule_glucose_model.dart';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class BloodSugarTemplateResponseDataSchedules {
/*
{
  "day": 6,
  "isBeforeBreakfast": true,
  "isAfterBreakfast": false,
  "isBeforeLunch": true,
  "isAfterLunch": false,
  "isBeforeDinner": true,
  "isAfterDinner": false,
  "isBeforeSleeping": true
} 
*/

  int? day;
  bool? isBeforeBreakfast;
  bool? isAfterBreakfast;
  bool? isBeforeLunch;
  bool? isAfterLunch;
  bool? isBeforeDinner;
  bool? isAfterDinner;
  bool? isBeforeSleeping;

  BloodSugarTemplateResponseDataSchedules({
    this.day,
    this.isBeforeBreakfast,
    this.isAfterBreakfast,
    this.isBeforeLunch,
    this.isAfterLunch,
    this.isBeforeDinner,
    this.isAfterDinner,
    this.isBeforeSleeping,
  });

  ScheduleModel get scheduleModel => ScheduleModel(
        isBeforeBreakfast: this.isBeforeBreakfast,
        isAfterBreakfast: this.isAfterBreakfast,
        isBeforeLunch: this.isBeforeLunch,
        isAfterLunch: this.isAfterLunch,
        isBeforeDinner: this.isBeforeDinner,
        isAfterDinner: this.isAfterDinner,
        isBeforeSleeping: this.isBeforeSleeping,
      );

  BloodSugarTemplateResponseDataSchedules.fromJson(Map<String, dynamic> json) {
    day = json["day"]?.toInt();
    isBeforeBreakfast = json["isBeforeBreakfast"];
    isAfterBreakfast = json["isAfterBreakfast"];
    isBeforeLunch = json["isBeforeLunch"];
    isAfterLunch = json["isAfterLunch"];
    isBeforeDinner = json["isBeforeDinner"];
    isAfterDinner = json["isAfterDinner"];
    isBeforeSleeping = json["isBeforeSleeping"];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["day"] = day;
    data["isBeforeBreakfast"] = isBeforeBreakfast;
    data["isAfterBreakfast"] = isAfterBreakfast;
    data["isBeforeLunch"] = isBeforeLunch;
    data["isAfterLunch"] = isAfterLunch;
    data["isBeforeDinner"] = isBeforeDinner;
    data["isAfterDinner"] = isAfterDinner;
    data["isBeforeSleeping"] = isBeforeSleeping;
    return data;
  }
}

class BloodSugarTemplateResponseData {
/*
{
  "id": "e89a508e-1c6b-48ca-99c0-2e9b22af5014",
  "code": "K",
  "name": "Mẫu K",
  "isWeekTemplate": true,
  "timePerDay": 6,
  "description": "Chúng tôi khuyến nghị bạn đo đường huyết 4 lần/ngày ",
  "note": "",
  "schedules": [
    {
      "day": 6,
      "isBeforeBreakfast": true,
      "isAfterBreakfast": false,
      "isBeforeLunch": true,
      "isAfterLunch": false,
      "isBeforeDinner": true,
      "isAfterDinner": false,
      "isBeforeSleeping": true
    }
  ]
} 
*/

  String? id;
  String? code;
  String? name;
  bool? isWeekTemplate;
  int? timePerDay;
  String? description;
  String? note;
  List<BloodSugarTemplateResponseDataSchedules?>? schedules;

  BloodSugarTemplateResponseData({
    this.id,
    this.code,
    this.name,
    this.isWeekTemplate,
    this.timePerDay,
    this.description,
    this.note,
    this.schedules,
  });

  ScheduleGlucoseModel get scheduleGlucoseModel {
    if (this.isWeekTemplate == true) {
      return ScheduleGlucoseModel(
        monday: getScheduleModelByIndex(1),
        tuesday: getScheduleModelByIndex(2),
        wednesday: getScheduleModelByIndex(3),
        thursday: getScheduleModelByIndex(4),
        friday: getScheduleModelByIndex(5),
        saturday: getScheduleModelByIndex(6),
        sunday: getScheduleModelByIndex(7),
      );
    } else {
      final ScheduleModel? scheduleModel = this.schedules?.first?.scheduleModel;
      return ScheduleGlucoseModel(
        monday: scheduleModel,
        tuesday: scheduleModel,
        wednesday: scheduleModel,
        thursday: scheduleModel,
        friday: scheduleModel,
        saturday: scheduleModel,
        sunday: scheduleModel,
      );
    }
  }

  ScheduleModel? getScheduleModelByIndex(int dayIndex) {
    final int? index =
        this.schedules?.indexWhere((schedule) => dayIndex == schedule?.day);
    if (index == -1) return null;
    final BloodSugarTemplateResponseDataSchedules? data =
        this.schedules?[index!];
    return data?.scheduleModel;
  }

  BloodSugarTemplateResponseData.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toString();
    code = json["code"]?.toString();
    name = json["name"]?.toString();
    isWeekTemplate = json["isWeekTemplate"];
    timePerDay = json["timePerDay"]?.toInt();
    description = json["description"]?.toString();
    note = json["note"]?.toString();
    if (json["schedules"] != null) {
      final v = json["schedules"];
      final arr0 = <BloodSugarTemplateResponseDataSchedules>[];
      v.forEach((v) {
        arr0.add(BloodSugarTemplateResponseDataSchedules.fromJson(v));
      });
      schedules = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["code"] = code;
    data["name"] = name;
    data["isWeekTemplate"] = isWeekTemplate;
    data["timePerDay"] = timePerDay;
    data["description"] = description;
    data["note"] = note;
    if (schedules != null) {
      final v = schedules;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["schedules"] = arr0;
    }
    return data;
  }
}

class BloodSugarTemplateResponse {
/*
{
  "id": "00000000-0000-0000-0000-000000000000",
  "statusCode": 200,
  "message": "Success",
  "data": {
    "id": "e89a508e-1c6b-48ca-99c0-2e9b22af5014",
    "code": "K",
    "name": "Mẫu K",
    "isWeekTemplate": true,
    "timePerDay": 6,
    "description": "Chúng tôi khuyến nghị bạn đo đường huyết 4 lần/ngày ",
    "note": "",
    "schedules": [
      {
        "day": 6,
        "isBeforeBreakfast": true,
        "isAfterBreakfast": false,
        "isBeforeLunch": true,
        "isAfterLunch": false,
        "isBeforeDinner": true,
        "isAfterDinner": false,
        "isBeforeSleeping": true
      }
    ]
  }
} 
*/

  String? id;
  int? statusCode;
  String? message;
  BloodSugarTemplateResponseData? data;

  BloodSugarTemplateResponse({
    this.id,
    this.statusCode,
    this.message,
    this.data,
  });
  BloodSugarTemplateResponse.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toString();
    statusCode = json["statusCode"]?.toInt();
    message = json["message"]?.toString();
    data = (json["data"] != null)
        ? BloodSugarTemplateResponseData.fromJson(json["data"])
        : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["statusCode"] = statusCode;
    data["message"] = message;
    if (data != null) {
      data["data"] = this.data!.toJson();
    }
    return data;
  }
}
