///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class BloodSugarTemplateCategoryResponseData {
/*
{
  "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "name": "string",
  "description": "string"
} 
*/

  String? id;
  String? name;
  String? description;

  BloodSugarTemplateCategoryResponseData({
    this.id,
    this.name,
    this.description,
  });
  BloodSugarTemplateCategoryResponseData.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toString();
    name = json["name"]?.toString();
    description = json["description"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["name"] = name;
    data["description"] = description;
    return data;
  }
}

class BloodSugarTemplateCategoryResponseMeta {
/*
{
  "success": true
} 
*/

  bool? success;

  BloodSugarTemplateCategoryResponseMeta({
    this.success,
  });
  BloodSugarTemplateCategoryResponseMeta.fromJson(Map<String, dynamic> json) {
    success = json["success"];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["success"] = success;
    return data;
  }
}

class BloodSugarTemplateCategoryResponse {
/*
{
  "meta": {
    "success": true
  },
  "data": [
    {
      "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "name": "string",
      "description": "string"
    }
  ]
} 
*/

  BloodSugarTemplateCategoryResponseMeta? meta;
  List<BloodSugarTemplateCategoryResponseData?>? data;

  BloodSugarTemplateCategoryResponse({
    this.meta,
    this.data,
  });
  BloodSugarTemplateCategoryResponse.fromJson(Map<String, dynamic> json) {
    meta = (json["meta"] != null) ? BloodSugarTemplateCategoryResponseMeta.fromJson(json["meta"]) : null;
  if (json["data"] != null) {
  final v = json["data"];
  final arr0 = <BloodSugarTemplateCategoryResponseData>[];
  v.forEach((v) {
  arr0.add(BloodSugarTemplateCategoryResponseData.fromJson(v));
  });
    this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (meta != null) {
      data["meta"] = meta!.toJson();
    }
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data["data"] = arr0;
    }
    return data;
  }
}

