///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class BloodSugarTemplateDetailResponseData {
/*
{
  "id": "09dbfa4f-c23c-4a5a-88ab-3f4b783b6893",
  "name": "Mẫu K",
  "category": 5,
  "template": 6,
  "isWeekTemplate": true,
  "day": 6,
  "isBeforeBreakfast": false,
  "isAfterBreakfast": false,
  "isBeforeLunch": false,
  "isAfterLunch": false,
  "isBeforeDinner": false,
  "isAfterDinner": false,
  "isBeforeSleeping": false
} 
*/

  String? id;
  String? name;
  int? category;
  int? template;
  bool? isWeekTemplate;
  int? day;
  bool? isBeforeBreakfast;
  bool? isAfterBreakfast;
  bool? isBeforeLunch;
  bool? isAfterLunch;
  bool? isBeforeDinner;
  bool? isAfterDinner;
  bool? isBeforeSleeping;

  BloodSugarTemplateDetailResponseData({
    this.id,
    this.name,
    this.category,
    this.template,
    this.isWeekTemplate,
    this.day,
    this.isBeforeBreakfast,
    this.isAfterBreakfast,
    this.isBeforeLunch,
    this.isAfterLunch,
    this.isBeforeDinner,
    this.isAfterDinner,
    this.isBeforeSleeping,
  });
  BloodSugarTemplateDetailResponseData.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toString();
    name = json["name"]?.toString();
    category = json["category"]?.toInt();
    template = json["template"]?.toInt();
    isWeekTemplate = json["isWeekTemplate"];
    day = json["day"]?.toInt();
    isBeforeBreakfast = json["isBeforeBreakfast"];
    isAfterBreakfast = json["isAfterBreakfast"];
    isBeforeLunch = json["isBeforeLunch"];
    isAfterLunch = json["isAfterLunch"];
    isBeforeDinner = json["isBeforeDinner"];
    isAfterDinner = json["isAfterDinner"];
    isBeforeSleeping = json["isBeforeSleeping"];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["name"] = name;
    data["category"] = category;
    data["template"] = template;
    data["isWeekTemplate"] = isWeekTemplate;
    data["day"] = day;
    data["isBeforeBreakfast"] = isBeforeBreakfast;
    data["isAfterBreakfast"] = isAfterBreakfast;
    data["isBeforeLunch"] = isBeforeLunch;
    data["isAfterLunch"] = isAfterLunch;
    data["isBeforeDinner"] = isBeforeDinner;
    data["isAfterDinner"] = isAfterDinner;
    data["isBeforeSleeping"] = isBeforeSleeping;
    return data;
  }
}

class BloodSugarTemplateDetailResponseMeta {
/*
{
  "success": true
} 
*/

  bool? success;

  BloodSugarTemplateDetailResponseMeta({
    this.success,
  });
  BloodSugarTemplateDetailResponseMeta.fromJson(Map<String, dynamic> json) {
    success = json["success"];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["success"] = success;
    return data;
  }
}

class BloodSugarTemplateDetailResponse {
/*
{
  "meta": {
    "success": true
  },
  "data": [
    {
      "id": "09dbfa4f-c23c-4a5a-88ab-3f4b783b6893",
      "name": "Mẫu K",
      "category": 5,
      "template": 6,
      "isWeekTemplate": true,
      "day": 6,
      "isBeforeBreakfast": false,
      "isAfterBreakfast": false,
      "isBeforeLunch": false,
      "isAfterLunch": false,
      "isBeforeDinner": false,
      "isAfterDinner": false,
      "isBeforeSleeping": false
    }
  ]
} 
*/

  BloodSugarTemplateDetailResponseMeta? meta;
  List<BloodSugarTemplateDetailResponseData?>? data;

  BloodSugarTemplateDetailResponse({
    this.meta,
    this.data,
  });
  BloodSugarTemplateDetailResponse.fromJson(Map<String, dynamic> json) {
    meta = (json["meta"] != null) ? BloodSugarTemplateDetailResponseMeta.fromJson(json["meta"]) : null;
  if (json["data"] != null) {
  final v = json["data"];
  final arr0 = <BloodSugarTemplateDetailResponseData>[];
  v.forEach((v) {
  arr0.add(BloodSugarTemplateDetailResponseData.fromJson(v));
  });
    this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (meta != null) {
      data["meta"] = meta!.toJson();
    }
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data["data"] = arr0;
    }
    return data;
  }
}