import 'error_data.dart';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CreateSmartGoalResponseDataTargetSchedulerTargetSchedulerWeeks {
/*
{
  "dayInWeek": 0,
  "targetSchedulerId": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
} 
*/

  int? dayInWeek;
  String? targetSchedulerId;

  CreateSmartGoalResponseDataTargetSchedulerTargetSchedulerWeeks({
    this.dayInWeek,
    this.targetSchedulerId,
  });
  CreateSmartGoalResponseDataTargetSchedulerTargetSchedulerWeeks.fromJson(Map<String, dynamic> json) {
    dayInWeek = json['dayInWeek']?.toInt();
    targetSchedulerId = json['targetSchedulerId']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['dayInWeek'] = dayInWeek;
    data['targetSchedulerId'] = targetSchedulerId;
    return data;
  }
}

class CreateSmartGoalResponseDataTargetScheduler {
/*
{
  "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "repeatTime": 0,
  "repeatType": 0,
  "endDate": 0,
  "targetSchedulerWeeks": [
    {
      "dayInWeek": 0,
      "targetSchedulerId": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
    }
  ]
} 
*/

  String? id;
  int? repeatTime;
  int? repeatType;
  int? endDate;
  List<CreateSmartGoalResponseDataTargetSchedulerTargetSchedulerWeeks?>? targetSchedulerWeeks;

  CreateSmartGoalResponseDataTargetScheduler({
    this.id,
    this.repeatTime,
    this.repeatType,
    this.endDate,
    this.targetSchedulerWeeks,
  });
  CreateSmartGoalResponseDataTargetScheduler.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    repeatTime = json['repeatTime']?.toInt();
    repeatType = json['repeatType']?.toInt();
    endDate = json['endDate']?.toInt();
    if (json['targetSchedulerWeeks'] != null) {
      final v = json['targetSchedulerWeeks'];
      final arr0 = <CreateSmartGoalResponseDataTargetSchedulerTargetSchedulerWeeks>[];
      v.forEach((v) {
        arr0.add(CreateSmartGoalResponseDataTargetSchedulerTargetSchedulerWeeks.fromJson(v));
      });
      targetSchedulerWeeks = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['repeatTime'] = repeatTime;
    data['repeatType'] = repeatType;
    data['endDate'] = endDate;
    if (targetSchedulerWeeks != null) {
      final v = targetSchedulerWeeks;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['targetSchedulerWeeks'] = arr0;
    }
    return data;
  }
}

class CreateSmartGoalResponseData {
/*
{
  "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "name": "string",
  "type": 0,
  "appointmentDate": 0,
  "repeatType": 0,
  "targetSchedulerId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "executeType": 0,
  "executeDayTimes": 0,
  "executeWeekTimes": 0,
  "targetScheduler": {
    "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
    "repeatTime": 0,
    "repeatType": 0,
    "endDate": 0,
    "targetSchedulerWeeks": [
      {
        "dayInWeek": 0,
        "targetSchedulerId": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
      }
    ]
  }
} 
*/

  String? id;
  String? name;
  int? type;
  int? appointmentDate;
  int? repeatType;
  String? targetSchedulerId;
  int? executeType;
  int? executeDayTimes;
  int? executeWeekTimes;
  CreateSmartGoalResponseDataTargetScheduler? targetScheduler;

  CreateSmartGoalResponseData({
    this.id,
    this.name,
    this.type,
    this.appointmentDate,
    this.repeatType,
    this.targetSchedulerId,
    this.executeType,
    this.executeDayTimes,
    this.executeWeekTimes,
    this.targetScheduler,
  });
  CreateSmartGoalResponseData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    name = json['name']?.toString();
    type = json['type']?.toInt();
    appointmentDate = json['appointmentDate']?.toInt();
    repeatType = json['repeatType']?.toInt();
    targetSchedulerId = json['targetSchedulerId']?.toString();
    executeType = json['executeType']?.toInt();
    executeDayTimes = json['executeDayTimes']?.toInt();
    executeWeekTimes = json['executeWeekTimes']?.toInt();
    targetScheduler = (json['targetScheduler'] != null)
        ? CreateSmartGoalResponseDataTargetScheduler.fromJson(json['targetScheduler'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['type'] = type;
    data['appointmentDate'] = appointmentDate;
    data['repeatType'] = repeatType;
    data['targetSchedulerId'] = targetSchedulerId;
    data['executeType'] = executeType;
    data['executeDayTimes'] = executeDayTimes;
    data['executeWeekTimes'] = executeWeekTimes;
    if (targetScheduler != null) {
      data['targetScheduler'] = targetScheduler!.toJson();
    }
    return data;
  }
}

class CreateSmartGoalResponseMeta {
/*
{
  "success": true
} 
*/

  bool? success;

  CreateSmartGoalResponseMeta({
    this.success,
  });
  CreateSmartGoalResponseMeta.fromJson(Map<String, dynamic> json) {
    success = json['success'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    return data;
  }
}

class CreateSmartGoalResponse {
/*
{
  "meta": {
    "success": true
  },
  "data": {
    "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
    "name": "string",
    "type": 0,
    "appointmentDate": 0,
    "repeatType": 0,
    "targetSchedulerId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
    "executeType": 0,
    "executeDayTimes": 0,
    "executeWeekTimes": 0,
    "targetScheduler": {
      "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "repeatTime": 0,
      "repeatType": 0,
      "endDate": 0,
      "targetSchedulerWeeks": [
        {
          "dayInWeek": 0,
          "targetSchedulerId": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
        }
      ]
    }
  }
} 
*/

  CreateSmartGoalResponseMeta? meta;
  CreateSmartGoalResponseData? data;
  ErrorData? error;

  CreateSmartGoalResponse({
    this.meta,
    this.data,
    this.error,
  });
  CreateSmartGoalResponse.fromJson(Map<String, dynamic> json) {
    meta = (json['meta'] != null) ? CreateSmartGoalResponseMeta.fromJson(json['meta']) : null;
    data = (json['data'] != null) ? CreateSmartGoalResponseData.fromJson(json['data']) : null;
    error = (json['error'] != null) ? ErrorData.fromJson(json['error']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (meta != null) {
      data['meta'] = meta!.toJson();
    }
    if (this.data != null) {
      data['data'] = this.data!.toJson();
    }
    if (this.error != null) {
      data['error'] = this.error!.toJson();
    }
    return data;
  }
}
