///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CreateMenuResponse {
/*
{
  "id": "00000000-0000-0000-0000-000000000000",
  "statusCode": 400,
  "message": " Chưa có menu phù hợp với Kcal và số bửa ăn",
  "data": "00000000-0000-0000-0000-000000000000"
} 
*/

  String? id;
  int? statusCode;
  String? message;
  String? data;

  CreateMenuResponse({
    this.id,
    this.statusCode,
    this.message,
    this.data,
  });
  CreateMenuResponse.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toString();
    statusCode = json["statusCode"]?.toInt();
    message = json["message"]?.toString();
    data = json["data"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["statusCode"] = statusCode;
    data["message"] = message;
    data["data"] = this.data;
    return data;
  }
}