///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CreateMenuResponseMeta {
/*
{
  "success": true
} 
*/

  bool? success;

  CreateMenuResponseMeta({
    this.success,
  });
  CreateMenuResponseMeta.fromJson(Map<String, dynamic> json) {
    success = json["success"];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["success"] = success;
    return data;
  }
}

class CreateMenuResponse {
/*
{
  "meta": {
    "success": true
  },
  "data": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
} 
*/

  CreateMenuResponseMeta? meta;
  String? data;

  CreateMenuResponse({
    this.meta,
    this.data,
  });
  CreateMenuResponse.fromJson(Map<String, dynamic> json) {
    meta = (json["meta"] != null) ? CreateMenuResponseMeta.fromJson(json["meta"]) : null;
    data = json["data"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (meta != null) {
      data["meta"] = meta!.toJson();
    }
    data["data"] = this.data;
    return data;
  }
}