///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class DeleteSmartGoalReponseMeta {
/*
{
  "success": true
} 
*/

  bool? success;

  DeleteSmartGoalReponseMeta({
    this.success,
  });
  DeleteSmartGoalReponseMeta.fromJson(Map<String, dynamic> json) {
    success = json['success'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    return data;
  }
}

class DeleteSmartGoalReponse {
/*
{
  "meta": {
    "success": true
  },
  "data": true
} 
*/

  DeleteSmartGoalReponseMeta? meta;
  bool? data;

  DeleteSmartGoalReponse({
    this.meta,
    this.data,
  });
  DeleteSmartGoalReponse.fromJson(Map<String, dynamic> json) {
    meta = (json['meta'] != null)
        ? DeleteSmartGoalReponseMeta.fromJson(json['meta'])
        : null;
    data = json['data'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (meta != null) {
      data['meta'] = meta!.toJson();
    }
    data['data'] = this.data;
    return data;
  }
}
