///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class DiabetesStatusResponseData {
/*
{
  "status": 1,
  "date": 0,
  "name": "string"
} 
*/

  int? status;
  int? date;
  String? name;

  DiabetesStatusResponseData({
    this.status,
    this.date,
    this.name,
  });
  DiabetesStatusResponseData.fromJson(Map<String, dynamic> json) {
    status = json["status"]?.toInt();
    date = json["date"]?.toInt();
    name = json["name"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["status"] = status;
    data["date"] = date;
    data["name"] = name;
    return data;
  }
}

class DiabetesStatusResponseMeta {
/*
{
  "success": true
} 
*/

  bool? success;

  DiabetesStatusResponseMeta({
    this.success,
  });
  DiabetesStatusResponseMeta.fromJson(Map<String, dynamic> json) {
    success = json["success"];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["success"] = success;
    return data;
  }
}

class DiabetesStatusResponse {
/*
{
  "meta": {
    "success": true
  },
  "data": {
    "status": 1,
    "date": 0,
    "name": "string"
  }
} 
*/

  DiabetesStatusResponseMeta? meta;
  DiabetesStatusResponseData? data;

  DiabetesStatusResponse({
    this.meta,
    this.data,
  });
  DiabetesStatusResponse.fromJson(Map<String, dynamic> json) {
    meta = (json["meta"] != null) ? DiabetesStatusResponseMeta.fromJson(json["meta"]) : null;
    data = (json["data"] != null) ? DiabetesStatusResponseData.fromJson(json["data"]) : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (meta != null) {
      data["meta"] = meta!.toJson();
    }
    if (data != null) {
      data["data"] = this.data!.toJson();
    }
    return data;
  }
}

