///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class DiabetesStatusResponse {
/*
{
  "status": 1,
  "date": 0,
  "name": "string"
} 
*/

  int? status;
  int? date;
  String? name;

  DiabetesStatusResponse({
    this.status,
    this.date,
    this.name,
  });
  DiabetesStatusResponse.fromJson(Map<String, dynamic> json) {
    status = json["status"]?.toInt();
    date = json["date"]?.toInt();
    name = json["name"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["status"] = status;
    data["date"] = date;
    data["name"] = name;
    return data;
  }
}

