import 'package:medical/src/modal/base/images.dart';
import 'package:medical/src/utils/const.dart';
import 'package:medical/src/utils/utils.dart';
import 'package:medical/src/widget/my_plan_screens/my_plan/models/completion_status.dart';
import 'package:medical/src/widgets/day_in_week_widget.dart';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ExerciseMovementResponseDataExerciseMovementAccounts {
/*
{
  "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "code": "string",
  "accountId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "exerciseMovementId": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
} 
*/

  String? id;
  String? code;
  String? accountId;
  String? exerciseMovementId;

  ExerciseMovementResponseDataExerciseMovementAccounts({
    this.id,
    this.code,
    this.accountId,
    this.exerciseMovementId,
  });
  ExerciseMovementResponseDataExerciseMovementAccounts.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    code = json['code']?.toString();
    accountId = json['accountId']?.toString();
    exerciseMovementId = json['exerciseMovementId']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['code'] = code;
    data['accountId'] = accountId;
    data['exerciseMovementId'] = exerciseMovementId;
    return data;
  }
}

class ExerciseMovementResponseDataReviewSummary {
/*
{
  "tooLightExercisePercent": 0,
  "tooLightExerciseCount": 0,
  "lightExercisePercent": 0,
  "lightExerciseCount": 0,
  "moderateExercisePercent": 0,
  "moderateExerciseCount": 0,
  "heavyExercisePercent": 0,
  "heavyExerciseCount": 0,
  "tooHeavyExercisePercent": 0,
  "tooHeavyExerciseCount": 0
} 
*/

  int? tooLightExercisePercent;
  int? tooLightExerciseCount;
  int? lightExercisePercent;
  int? lightExerciseCount;
  int? moderateExercisePercent;
  int? moderateExerciseCount;
  int? heavyExercisePercent;
  int? heavyExerciseCount;
  int? tooHeavyExercisePercent;
  int? tooHeavyExerciseCount;

  ExerciseMovementResponseDataReviewSummary({
    this.tooLightExercisePercent,
    this.tooLightExerciseCount,
    this.lightExercisePercent,
    this.lightExerciseCount,
    this.moderateExercisePercent,
    this.moderateExerciseCount,
    this.heavyExercisePercent,
    this.heavyExerciseCount,
    this.tooHeavyExercisePercent,
    this.tooHeavyExerciseCount,
  });
  ExerciseMovementResponseDataReviewSummary.fromJson(Map<String, dynamic> json) {
    tooLightExercisePercent = json['tooLightExercisePercent']?.toInt();
    tooLightExerciseCount = json['tooLightExerciseCount']?.toInt();
    lightExercisePercent = json['lightExercisePercent']?.toInt();
    lightExerciseCount = json['lightExerciseCount']?.toInt();
    moderateExercisePercent = json['moderateExercisePercent']?.toInt();
    moderateExerciseCount = json['moderateExerciseCount']?.toInt();
    heavyExercisePercent = json['heavyExercisePercent']?.toInt();
    heavyExerciseCount = json['heavyExerciseCount']?.toInt();
    tooHeavyExercisePercent = json['tooHeavyExercisePercent']?.toInt();
    tooHeavyExerciseCount = json['tooHeavyExerciseCount']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['tooLightExercisePercent'] = tooLightExercisePercent;
    data['tooLightExerciseCount'] = tooLightExerciseCount;
    data['lightExercisePercent'] = lightExercisePercent;
    data['lightExerciseCount'] = lightExerciseCount;
    data['moderateExercisePercent'] = moderateExercisePercent;
    data['moderateExerciseCount'] = moderateExerciseCount;
    data['heavyExercisePercent'] = heavyExercisePercent;
    data['heavyExerciseCount'] = heavyExerciseCount;
    data['tooHeavyExercisePercent'] = tooHeavyExercisePercent;
    data['tooHeavyExerciseCount'] = tooHeavyExerciseCount;
    return data;
  }
}

class ExerciseMovementResponseDataSections {
/*
{
  "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "code": "string",
  "name": "string",
  "exerciseCategoryId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "replayTime": 0,
  "videoUrl": "string"
} 
*/

  String? id;
  String? code;
  String? name;
  String? description;
  String? exerciseCategoryId;
  int? replayTime;
  String? videoUrl;

  ExerciseMovementResponseDataSections({
    this.id,
    this.code,
    this.name,
    this.description,
    this.exerciseCategoryId,
    this.replayTime,
    this.videoUrl,
  });
  ExerciseMovementResponseDataSections.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    code = json['code']?.toString();
    name = json['name']?.toString();
    description = json['description']?.toString();
    exerciseCategoryId = json['exerciseCategoryId']?.toString();
    replayTime = json['replayTime']?.toInt();
    videoUrl = json['videoUrl']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['code'] = code;
    data['name'] = name;
    data['description'] = description;
    data['exerciseCategoryId'] = exerciseCategoryId;
    data['replayTime'] = replayTime;
    data['videoUrl'] = videoUrl;
    return data;
  }
}

class ExerciseMovementResponseData {
/*
{
  "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "code": "string",
  "coverId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "roadmapId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "name": "string",
  "description": "string",
  "isFree": true,
  "isBlank": true,
  "practiceTime": 0,
  "videoUrl": "string",
  "day": 0,
  "image": {
    "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
    "url": "string"
  },
  "sections": [
    {
      "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "code": "string",
      "name": "string",
      "exerciseCategoryId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "replayTime": 0,
      "videoUrl": "string"
    }
  ],
  "reviewSummary": {
    "tooLightExercisePercent": 0,
    "tooLightExerciseCount": 0,
    "lightExercisePercent": 0,
    "lightExerciseCount": 0,
    "moderateExercisePercent": 0,
    "moderateExerciseCount": 0,
    "heavyExercisePercent": 0,
    "heavyExerciseCount": 0,
    "tooHeavyExercisePercent": 0,
    "tooHeavyExerciseCount": 0
  },
  "exerciseMovementAccounts": [
    {
      "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "code": "string",
      "accountId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "exerciseMovementId": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
    }
  ],
  "exerciseMovementStates": 0
} 
*/

  String? id;
  String? code;
  String? coverId;
  String? agendaId;
  String? name;
  String? description;
  bool? isFree;
  bool? isBlank;
  int? practiceTime;
  String? videoUrl;
  int? day;
  ImagesModel? image;
  List<ExerciseMovementResponseDataSections?>? sections;
  ExerciseMovementResponseDataReviewSummary? reviewSummary;
  List<ExerciseMovementResponseDataExerciseMovementAccounts?>? exerciseMovementAccounts;
  int? exerciseMovementStates;
  bool? isToday;

  ExerciseMovementResponseData({
    this.id,
    this.code,
    this.coverId,
    this.agendaId,
    this.name,
    this.description,
    this.isFree,
    this.isBlank,
    this.practiceTime,
    this.videoUrl,
    this.day,
    this.image,
    this.sections,
    this.reviewSummary,
    this.exerciseMovementAccounts,
    this.exerciseMovementStates,
    this.isToday,
  });

  CompletionStatus get completionStatus {
    if (exerciseMovementStates == Const.LESSON_NOT_LEARN) return CompletionStatus.not_completed;
    if (exerciseMovementStates == Const.LESSON_LEARNT) return CompletionStatus.completed;
    if (exerciseMovementStates == Const.LESSON_LEARNING) return CompletionStatus.studying;
    return CompletionStatus.not_start_yet;
  }

  ExerciseMovementResponseData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    code = json['code']?.toString();
    coverId = json['coverId']?.toString();
    agendaId = json['agendaId']?.toString();
    name = json['name']?.toString();
    description = json['description']?.toString();
    isFree = json['isFree'];
    isBlank = json['isBlank'];
    isToday = json['isToday'];
    practiceTime = json['practiceTime']?.toInt();
    videoUrl = json['videoUrl']?.toString();
    day = json['day']?.toInt();
    image = (json['image'] != null) ? ImagesModel.fromJson(json['image']) : null;
    if (json['sections'] != null) {
      final v = json['sections'];
      final arr0 = <ExerciseMovementResponseDataSections>[];
      if (v is List && v.isNotEmpty) {
        v.forEach((v) {
          arr0.add(ExerciseMovementResponseDataSections.fromJson(v));
        });
        sections = arr0;
      }
    }
    // reviewSummary = (json['reviewSummary'] != null)
    //     ? ExerciseMovementResponseDataReviewSummary.fromJson(
    //         json['reviewSummary'])
    //     : null;
    if (json['exerciseMovementAccounts'] != null) {
      final v = json['exerciseMovementAccounts'];
      final arr0 = <ExerciseMovementResponseDataExerciseMovementAccounts>[];
      v.forEach((v) {
        arr0.add(ExerciseMovementResponseDataExerciseMovementAccounts.fromJson(v));
      });
      exerciseMovementAccounts = arr0;
    }
    exerciseMovementStates = json['exerciseMovementStates']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['code'] = code;
    data['coverId'] = coverId;
    data['agendaId'] = agendaId;
    data['name'] = name;
    data['description'] = description;
    data['isFree'] = isFree;
    data['isBlank'] = isBlank;
    data['isToday'] = isToday;
    data['practiceTime'] = practiceTime;
    data['videoUrl'] = videoUrl;
    data['day'] = day;
    if (image != null) {
      data['image'] = image!.toJson();
    }
    if (sections != null) {
      final v = sections;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['sections'] = arr0;
    }
    if (reviewSummary != null) {
      data['reviewSummary'] = reviewSummary!.toJson();
    }
    if (exerciseMovementAccounts != null) {
      final v = exerciseMovementAccounts;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['exerciseMovementAccounts'] = arr0;
    }
    data['exerciseMovementStates'] = exerciseMovementStates;
    return data;
  }
}

class ExerciseMovementResponseMeta {
/*
{
  "success": true
} 
*/

  bool? success;

  ExerciseMovementResponseMeta({
    this.success,
  });

  ExerciseMovementResponseMeta.fromJson(Map<String, dynamic> json) {
    success = json['success'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    return data;
  }
}

class ExerciseMovementResponse {
/*
{
  "meta": {
    "success": true
  },
  "data": [
    {
      "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "code": "string",
      "coverId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "roadmapId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "name": "string",
      "description": "string",
      "isFree": true,
      "isBlank": true,
      "practiceTime": 0,
      "videoUrl": "string",
      "day": 0,
      "image": {
        "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
        "url": "string"
      },
      "sections": [
        {
          "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
          "code": "string",
          "name": "string",
          "exerciseCategoryId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
          "replayTime": 0,
          "videoUrl": "string"
        }
      ],
      "reviewSummary": {
        "tooLightExercisePercent": 0,
        "tooLightExerciseCount": 0,
        "lightExercisePercent": 0,
        "lightExerciseCount": 0,
        "moderateExercisePercent": 0,
        "moderateExerciseCount": 0,
        "heavyExercisePercent": 0,
        "heavyExerciseCount": 0,
        "tooHeavyExercisePercent": 0,
        "tooHeavyExerciseCount": 0
      },
      "exerciseMovementAccounts": [
        {
          "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
          "code": "string",
          "accountId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
          "exerciseMovementId": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
        }
      ],
      "exerciseMovementStates": 0
    }
  ]
} 
*/

  ExerciseMovementResponseMeta? meta;
  List<ExerciseMovementResponseData?>? data;

  ExerciseMovementResponse({
    this.meta,
    this.data,
  });

  int get firstExerciseIndex {
    if (data?.isNotEmpty != true) return 0;
    for (int index = 0; index < (data?.length ?? 0); index++) {
      if (data?[index]?.exerciseMovementStates != null && data?[index]?.exerciseMovementStates != Const.LESSON_LEARNT) {
        return index;
      }
    }
    return 0;
  }

  ExerciseMovementResponseData? getExerciseFromDayInWeek({
    required int week,
    required int dayIndex,
  }) {
    if (data == null) return null;
    return data?[dayIndex];
  }

  int getMarkNotLearnIndex({required int week, required int userCurrentWeek}) {
    if (data == null) return 0;
    if (week < userCurrentWeek) return 14;
    if (week > userCurrentWeek) return 0;

    for (int index = 0; index < (data?.length ?? 0); index++) {
      if (data?[index]?.completionStatus == CompletionStatus.studying) return index;
    }

    return 0;
  }

  int getCurrentDayIndex(int week) {
    for (int index = 0; index < (data?.length ?? 0); index++) {
      // if (data?[index]?.completionStatus == CompletionStatus.studying) {
      //   return index;
      // }
      if (data?[index]?.isToday ?? false) {
        return index;
      }
    }
    return 0;
  }

  List<DayInWeekData> get dayInWeekList {
    if (data == null) return [];
    final List<DayInWeekData> dayInWeekList = [];
    int dayIndex = 7;
    for (int index = (data?.length ?? 0) - 1; index >= 0; index--) {
      if (dayIndex - 1 >= 0) {
        dayIndex -= 1;
      } else {
        dayIndex = 6;
      }
      dayInWeekList.insert(
        0,
        DayInWeekData(
          title: Utils.getDayInWeekTitle(dayIndex),
          dayStatus: data?[index]?.completionStatus ?? CompletionStatus.not_start_yet,
          isToday: data?[index]?.isToday,
        ),
      );
    }
    return dayInWeekList;
  }

  ExerciseMovementResponse.fromJson(Map<String, dynamic> json) {
    meta = (json['meta'] != null) ? ExerciseMovementResponseMeta.fromJson(json['meta']) : null;
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <ExerciseMovementResponseData>[];
      v.forEach((v) {
        arr0.add(ExerciseMovementResponseData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (meta != null) {
      data['meta'] = meta!.toJson();
    }
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }
}
