///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///

class FilterDataItemGroup {
/*
{
  "disabled": true,
  "name": "string"
} 
*/

  bool? disabled;
  String? name;

  FilterDataItemGroup({
    this.disabled,
    this.name,
  });

  FilterDataItemGroup get copy => FilterDataItemGroup(
        disabled: this.disabled,
        name: this.name,
      );

  FilterDataItemGroup.fromJson(Map<String, dynamic> json) {
    disabled = json['disabled'];
    name = json['name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['disabled'] = disabled;
    data['name'] = name;
    return data;
  }
}

class FilterDataItem {
/*
{
  "disabled": true,
  "group": {
    "disabled": true,
    "name": "string"
  },
  "selected": true,
  "text": "string",
  "value": "string"
} 
*/

  bool? disabled;
  FilterDataItemGroup? group;
  bool? selected;
  String? text;
  String? value;

  FilterDataItem({
    this.disabled,
    this.group,
    this.selected,
    this.text,
    this.value,
  });

  FilterDataItem get copy => FilterDataItem(
        disabled: this.disabled,
        group: this.group?.copy,
        selected: this.selected,
        text: this.text,
        value: this.value,
      );

  FilterDataItem.fromJson(Map<String, dynamic> json) {
    disabled = json['disabled'];
    group = (json['group'] != null)
        ? FilterDataItemGroup.fromJson(json['group'])
        : null;
    selected = json['selected'];
    text = json['text']?.toString();
    value = json['value']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['disabled'] = disabled;
    if (group != null) {
      data['group'] = group!.toJson();
    }
    data['selected'] = selected;
    data['text'] = text;
    data['value'] = value;
    return data;
  }
}

class FilterDataResponseData {
/*
{
  "lessonStates": [
    {
      "disabled": true,
      "group": {
        "disabled": true,
        "name": "string"
      },
      "selected": true,
      "text": "string",
      "value": "string"
    }
  ],
  "lessonLevels": [
    {
      "disabled": true,
      "group": {
        "disabled": true,
        "name": "string"
      },
      "selected": true,
      "text": "string",
      "value": "string"
    }
  ],
  "lessonModules": [
    {
      "disabled": true,
      "group": {
        "disabled": true,
        "name": "string"
      },
      "selected": true,
      "text": "string",
      "value": "string"
    }
  ],
  "lessonTags": [
    {
      "disabled": true,
      "group": {
        "disabled": true,
        "name": "string"
      },
      "selected": true,
      "text": "string",
      "value": "string"
    }
  ],
  "lessonTypes": [
    {
      "disabled": true,
      "group": {
        "disabled": true,
        "name": "string"
      },
      "selected": true,
      "text": "string",
      "value": "string"
    }
  ],
  "lessons": [
    {
      "disabled": true,
      "group": {
        "disabled": true,
        "name": "string"
      },
      "selected": true,
      "text": "string",
      "value": "string"
    }
  ]
} 
*/

  List<FilterDataItem?>? lessonStates;
  List<FilterDataItem?>? lessonLevels;
  List<FilterDataItem?>? lessonModules;
  List<FilterDataItem?>? lessonTags;
  List<FilterDataItem?>? lessonTypes;
  List<FilterDataItem?>? lessons;

  FilterDataResponseData({
    this.lessonStates,
    this.lessonLevels,
    this.lessonModules,
    this.lessonTags,
    this.lessonTypes,
    this.lessons,
  });

  FilterDataResponseData.fromJson(Map<String, dynamic> json) {
    if (json['lessonStates'] != null) {
      final v = json['lessonStates'];
      final arr0 = <FilterDataItem>[];
      v.forEach((v) {
        arr0.add(FilterDataItem.fromJson(v));
      });
      lessonStates = arr0;
    }
    if (json['lessonLevels'] != null) {
      final v = json['lessonLevels'];
      final arr0 = <FilterDataItem>[];
      v.forEach((v) {
        arr0.add(FilterDataItem.fromJson(v));
      });
      lessonLevels = arr0;
    }
    if (json['lessonModules'] != null) {
      final v = json['lessonModules'];
      final arr0 = <FilterDataItem>[];
      v.forEach((v) {
        arr0.add(FilterDataItem.fromJson(v));
      });
      lessonModules = arr0;
    }
    if (json['lessonTags'] != null) {
      final v = json['lessonTags'];
      final arr0 = <FilterDataItem>[];
      v.forEach((v) {
        arr0.add(FilterDataItem.fromJson(v));
      });
      lessonTags = arr0;
    }
    if (json['lessonTypes'] != null) {
      final v = json['lessonTypes'];
      final arr0 = <FilterDataItem>[];
      v.forEach((v) {
        arr0.add(FilterDataItem.fromJson(v));
      });
      lessonTypes = arr0;
    }
    if (json['lessons'] != null) {
      final v = json['lessons'];
      final arr0 = <FilterDataItem>[];
      v.forEach((v) {
        arr0.add(FilterDataItem.fromJson(v));
      });
      lessons = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (lessonStates != null) {
      final v = lessonStates;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['lessonStates'] = arr0;
    }
    if (lessonLevels != null) {
      final v = lessonLevels;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['lessonLevels'] = arr0;
    }
    if (lessonModules != null) {
      final v = lessonModules;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['lessonModules'] = arr0;
    }
    if (lessonTags != null) {
      final v = lessonTags;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['lessonTags'] = arr0;
    }
    if (lessonTypes != null) {
      final v = lessonTypes;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['lessonTypes'] = arr0;
    }
    if (lessons != null) {
      final v = lessons;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['lessons'] = arr0;
    }
    return data;
  }
}

class FilterDataResponseMeta {
/*
{
  "success": true
} 
*/

  bool? success;

  FilterDataResponseMeta({
    this.success,
  });
  FilterDataResponseMeta.fromJson(Map<String, dynamic> json) {
    success = json['success'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    return data;
  }
}

class FilterDataResponse {
/*
{
  "meta": {
    "success": true
  },
  "data": {
    "lessonStates": [
      {
        "disabled": true,
        "group": {
          "disabled": true,
          "name": "string"
        },
        "selected": true,
        "text": "string",
        "value": "string"
      }
    ],
    "lessonLevels": [
      {
        "disabled": true,
        "group": {
          "disabled": true,
          "name": "string"
        },
        "selected": true,
        "text": "string",
        "value": "string"
      }
    ],
    "lessonModules": [
      {
        "disabled": true,
        "group": {
          "disabled": true,
          "name": "string"
        },
        "selected": true,
        "text": "string",
        "value": "string"
      }
    ],
    "lessonTags": [
      {
        "disabled": true,
        "group": {
          "disabled": true,
          "name": "string"
        },
        "selected": true,
        "text": "string",
        "value": "string"
      }
    ],
    "lessonTypes": [
      {
        "disabled": true,
        "group": {
          "disabled": true,
          "name": "string"
        },
        "selected": true,
        "text": "string",
        "value": "string"
      }
    ],
    "lessons": [
      {
        "disabled": true,
        "group": {
          "disabled": true,
          "name": "string"
        },
        "selected": true,
        "text": "string",
        "value": "string"
      }
    ]
  }
} 
*/

  FilterDataResponseMeta? meta;
  FilterDataResponseData? data;

  FilterDataResponse({
    this.meta,
    this.data,
  });
  FilterDataResponse.fromJson(Map<String, dynamic> json) {
    meta = (json['meta'] != null)
        ? FilterDataResponseMeta.fromJson(json['meta'])
        : null;
    data = (json['data'] != null)
        ? FilterDataResponseData.fromJson(json['data'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (meta != null) {
      data['meta'] = meta!.toJson();
    }
    if (this.data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
