///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class FoodSuggestResponseData {
/*
{
  "id": "0c8467de-08cb-42d1-2e51-08d981116b4e",
  "foodMenuCode": "TD19",
  "dateCode": "T2",
  "timeCode": 1,
  "foodId": "02821a58-50cb-4290-7797-08d945b50f3d",
  "foodCategoryId": "8eff87be-cecd-43e2-300d-08d945b3544f",
  "foodUnitId": "4fd993d2-ebf1-4b5b-ad89-5e0058ab5896",
  "foodUnitName": "Phần",
  "foodName": "Ức gà nướng ớt chuông",
  "portion": 2,
  "calorie": 150.9,
  "glucose": 2.6,
  "lipid": 4.6,
  "protein": 23.2,
  "fibre": 0.8,
  "note": "T2 food"
} 
*/

  String? id;
  String? foodMenuCode;
  String? dateCode;
  int? timeCode;
  String? foodId;
  String? foodCategoryId;
  String? foodUnitId;
  String? foodUnitName;
  String? foodName;
  int? portion;
  double? calorie;
  double? glucose;
  double? lipid;
  double? protein;
  double? fibre;
  String? note;

  FoodSuggestResponseData({
    this.id,
    this.foodMenuCode,
    this.dateCode,
    this.timeCode,
    this.foodId,
    this.foodCategoryId,
    this.foodUnitId,
    this.foodUnitName,
    this.foodName,
    this.portion,
    this.calorie,
    this.glucose,
    this.lipid,
    this.protein,
    this.fibre,
    this.note,
  });

  
  FoodSuggestResponseData.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toString();
    foodMenuCode = json["foodMenuCode"]?.toString();
    dateCode = json["dateCode"]?.toString();
    timeCode = json["timeCode"]?.toInt();
    foodId = json["foodId"]?.toString();
    foodCategoryId = json["foodCategoryId"]?.toString();
    foodUnitId = json["foodUnitId"]?.toString();
    foodUnitName = json["foodUnitName"]?.toString();
    foodName = json["foodName"]?.toString();
    portion = json["portion"]?.toInt();
    calorie = json["calorie"]?.toDouble();
    glucose = json["glucose"]?.toDouble();
    lipid = json["lipid"]?.toDouble();
    protein = json["protein"]?.toDouble();
    fibre = json["fibre"]?.toDouble();
    note = json["note"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["foodMenuCode"] = foodMenuCode;
    data["dateCode"] = dateCode;
    data["timeCode"] = timeCode;
    data["foodId"] = foodId;
    data["foodCategoryId"] = foodCategoryId;
    data["foodUnitId"] = foodUnitId;
    data["foodUnitName"] = foodUnitName;
    data["foodName"] = foodName;
    data["portion"] = portion;
    data["calorie"] = calorie;
    data["glucose"] = glucose;
    data["lipid"] = lipid;
    data["protein"] = protein;
    data["fibre"] = fibre;
    data["note"] = note;
    return data;
  }
}

class FoodSuggestResponse {
/*
{
  "id": "00000000-0000-0000-0000-000000000000",
  "statusCode": 200,
  "message": "Success",
  "data": [
    {
      "id": "0c8467de-08cb-42d1-2e51-08d981116b4e",
      "foodMenuCode": "TD19",
      "dateCode": "T2",
      "timeCode": 1,
      "foodId": "02821a58-50cb-4290-7797-08d945b50f3d",
      "foodCategoryId": "8eff87be-cecd-43e2-300d-08d945b3544f",
      "foodUnitId": "4fd993d2-ebf1-4b5b-ad89-5e0058ab5896",
      "foodUnitName": "Phần",
      "foodName": "Ức gà nướng ớt chuông",
      "portion": 2,
      "calorie": 150.9,
      "glucose": 2.6,
      "lipid": 4.6,
      "protein": 23.2,
      "fibre": 0.8,
      "note": "T2 food"
    }
  ]
} 
*/

  String? id;
  int? statusCode;
  String? message;
  List<FoodSuggestResponseData?>? data;

  FoodSuggestResponse({
    this.id,
    this.statusCode,
    this.message,
    this.data,
  });
  FoodSuggestResponse.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toString();
    statusCode = json["statusCode"]?.toInt();
    message = json["message"]?.toString();
  if (json["data"] != null) {
  final v = json["data"];
  final arr0 = <FoodSuggestResponseData>[];
  v.forEach((v) {
  arr0.add(FoodSuggestResponseData.fromJson(v));
  });
    this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["statusCode"] = statusCode;
    data["message"] = message;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data["data"] = arr0;
    }
    return data;
  }
}