import 'package:medical/src/modal/base/images.dart';
import 'package:medical/src/modal/food/food_model.dart';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class FoodSuggestResponseData {
/*
{
  "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "foodMenuCode": "string",
  "dateCode": "string",
  "timeCode": 1,
  "foodId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "foodCategoryId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "foodUnitId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "foodUnitName": "string",
  "foodName": "string",
  "portion": 0,
  "calorie": 0,
  "glucose": 0,
  "lipid": 0,
  "protein": 0,
  "fibre": 0,
  "note": "string",
  "image": {
    "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
    "url": "string"
  },
  "liked": true
} 
*/

  String? id;
  String? foodMenuCode;
  String? dateCode;
  int? timeCode;
  String? foodId;
  String? foodCategoryId;
  String? foodUnitId;
  String? foodUnitName;
  String? foodName;
  int? portion;
  double? calorie;
  double? glucose;
  double? lipid;
  double? protein;
  double? fibre;
  String? note;
  ImagesModel? image;
  bool? liked;

  FoodSuggestResponseData({
    this.id,
    this.foodMenuCode,
    this.dateCode,
    this.timeCode,
    this.foodId,
    this.foodCategoryId,
    this.foodUnitId,
    this.foodUnitName,
    this.foodName,
    this.portion,
    this.calorie,
    this.glucose,
    this.lipid,
    this.protein,
    this.fibre,
    this.note,
    this.image,
    this.liked,
  });

  FoodModel get foodModel => FoodModel(
        id: this.id,
        code: this.foodMenuCode,
        name: this.foodName,
        portion: this.portion?.toDouble() ?? 0.0,
        unit: this.foodUnitName,
        calorie: this.calorie ?? 0.0,
        glucose: this.glucose,
        lipid: this.lipid,
        protein: this.protein,
        fibre: this.fibre,
        image: this.image,
        liked: this.liked,
        text: '',
        description: '',
        foodCategoryId: this.foodCategoryId, quantity: 0.0,
      );

  FoodSuggestResponseData.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toString();
    foodMenuCode = json["foodMenuCode"]?.toString();
    dateCode = json["dateCode"]?.toString();
    timeCode = json["timeCode"]?.toInt();
    foodId = json["foodId"]?.toString();
    foodCategoryId = json["foodCategoryId"]?.toString();
    foodUnitId = json["foodUnitId"]?.toString();
    foodUnitName = json["foodUnitName"]?.toString();
    foodName = json["foodName"]?.toString();
    portion = json["portion"]?.toInt();
    calorie = json["calorie"]?.toInt();
    glucose = json["glucose"]?.toInt();
    lipid = json["lipid"]?.toInt();
    protein = json["protein"]?.toInt();
    fibre = json["fibre"]?.toInt();
    note = json["note"]?.toString();
    image =
        (json["image"] != null) ? ImagesModel.fromJson(json["image"]) : null;
    liked = json["liked"];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["foodMenuCode"] = foodMenuCode;
    data["dateCode"] = dateCode;
    data["timeCode"] = timeCode;
    data["foodId"] = foodId;
    data["foodCategoryId"] = foodCategoryId;
    data["foodUnitId"] = foodUnitId;
    data["foodUnitName"] = foodUnitName;
    data["foodName"] = foodName;
    data["portion"] = portion;
    data["calorie"] = calorie;
    data["glucose"] = glucose;
    data["lipid"] = lipid;
    data["protein"] = protein;
    data["fibre"] = fibre;
    data["note"] = note;
    if (image != null) {
      data["image"] = image!.toJson();
    }
    data["liked"] = liked;
    return data;
  }
}

class FoodSuggestResponse {
/*
{
  "id": "00000000-0000-0000-0000-000000000000",
  "statusCode": 200,
  "message": "Success",
  "data": [
    {
      "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "foodMenuCode": "string",
      "dateCode": "string",
      "timeCode": 1,
      "foodId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "foodCategoryId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "foodUnitId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "foodUnitName": "string",
      "foodName": "string",
      "portion": 0,
      "calorie": 0,
      "glucose": 0,
      "lipid": 0,
      "protein": 0,
      "fibre": 0,
      "note": "string",
      "image": {
        "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
        "url": "string"
      },
      "liked": true
    }
  ]
} 
*/

  String? id;
  int? statusCode;
  String? message;
  List<FoodSuggestResponseData?>? data;

  FoodSuggestResponse({
    this.id,
    this.statusCode,
    this.message,
    this.data,
  });

  List<FoodModel> get foodModelList {
    final List<FoodModel> foodModelList = [];
    for (final FoodSuggestResponseData? food in data ?? []) {
      final FoodModel? foodModel = food?.foodModel;
      if (foodModel != null) {
        foodModelList.add(foodModel);
      }
    }
    return foodModelList;
  }

  FoodSuggestResponse.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toString();
    statusCode = json["statusCode"]?.toInt();
    message = json["message"]?.toString();
    if (json["data"] != null) {
      final v = json["data"];
      final arr0 = <FoodSuggestResponseData>[];
      v.forEach((v) {
        arr0.add(FoodSuggestResponseData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["statusCode"] = statusCode;
    data["message"] = message;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["data"] = arr0;
    }
    return data;
  }
}
