import 'package:medical/src/modal/base/images.dart';
import 'package:medical/src/modal/food/food_model.dart';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///

class FoodSuggestResponseData {
/*
{
  "id": "00000000-0000-0000-0000-000000000000",
  "foodMenuCode": "78813eeb-e279-4d47-1f17-08d9b3274fab",
  "dateCode": "T2",
  "timeCode": 0,
  "foodId": "736531e6-bc86-4bb7-bbed-7ab6b9edaf2b",
  "foodCategoryId": "0da37baf-6e1d-43fb-9d88-5dbfe777dd80",
  "foodUnitId": "022907df-7814-4bb9-a03b-7bfe7f538c7d",
  "foodUnitName": "Cái",
  "foodName": "Bánh hot-dog nhân phômai",
  "portion": 1,
  "calorie": 129,
  "glucose": 15,
  "lipid": 5,
  "protein": 6,
  "fibre": 0,
  "note": "String",
  "image": {
    "id": "fc7b8dd0-08f6-4426-9bcb-08d8fe8c4080",
    "url": "http://diab-api-dev.savvycom.vn/App/Image/fc7b8dd0-08f6-4426-9bcb-08d8fe8c4080?expires=1638331343&signature=862e61f24e5e4e88b878f3042deaf7eeabbe01762efb0b20b87adcc96386e49f"
  },
  "foodSubstitute": true,
  "liked": false
} 
*/

  String? id;
  String? foodMenuCode;
  String? dateCode;
  int? timeCode;
  String? foodId;
  String? foodCategoryId;
  String? foodUnitId;
  String? foodUnitName;
  String? foodName;
  int? portion;
  int? calorie;
  int? glucose;
  int? lipid;
  int? protein;
  int? fibre;
  String? note;
  ImagesModel? image;
  bool? foodSubstitute;
  bool? liked;

  FoodSuggestResponseData({
    this.id,
    this.foodMenuCode,
    this.dateCode,
    this.timeCode,
    this.foodId,
    this.foodCategoryId,
    this.foodUnitId,
    this.foodUnitName,
    this.foodName,
    this.portion,
    this.calorie,
    this.glucose,
    this.lipid,
    this.protein,
    this.fibre,
    this.note,
    this.image,
    this.foodSubstitute,
    this.liked,
  });

  FoodModel get foodModel => FoodModel(
        id: this.foodId,
        code: this.foodMenuCode,
        name: this.foodName,
        portion: this.portion?.toDouble() ?? 0.0,
        unit: this.foodUnitName,
        calorie: this.calorie?.toDouble() ?? 0.0,
        glucose: this.glucose?.toDouble(),
        lipid: this.lipid?.toDouble(),
        protein: this.protein?.toDouble(),
        fibre: this.fibre?.toDouble(),
        image: this.image,
        liked: this.liked,
        text: '',
        description: '',
        foodCategoryId: this.foodCategoryId,
        quantity: 0.0,
      );

  FoodSuggestResponseData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    foodMenuCode = json['foodMenuCode']?.toString();
    dateCode = json['dateCode']?.toString();
    timeCode = json['timeCode']?.toInt();
    foodId = json['foodId']?.toString();
    foodCategoryId = json['foodCategoryId']?.toString();
    foodUnitId = json['foodUnitId']?.toString();
    foodUnitName = json['foodUnitName']?.toString();
    foodName = json['foodName']?.toString();
    portion = json['portion']?.toInt();
    calorie = json['calorie']?.toInt();
    glucose = json['glucose']?.toInt();
    lipid = json['lipid']?.toInt();
    protein = json['protein']?.toInt();
    fibre = json['fibre']?.toInt();
    note = json['note']?.toString();
    image =
        (json['image'] != null) ? ImagesModel.fromJson(json['image']) : null;
    foodSubstitute = json['foodSubstitute'];
    liked = json['liked'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['foodMenuCode'] = foodMenuCode;
    data['dateCode'] = dateCode;
    data['timeCode'] = timeCode;
    data['foodId'] = foodId;
    data['foodCategoryId'] = foodCategoryId;
    data['foodUnitId'] = foodUnitId;
    data['foodUnitName'] = foodUnitName;
    data['foodName'] = foodName;
    data['portion'] = portion;
    data['calorie'] = calorie;
    data['glucose'] = glucose;
    data['lipid'] = lipid;
    data['protein'] = protein;
    data['fibre'] = fibre;
    data['note'] = note;
    if (image != null) {
      data['image'] = image!.toJson();
    }
    data['foodSubstitute'] = foodSubstitute;
    data['liked'] = liked;
    return data;
  }
}

class FoodSuggestResponse {
/*
{
  "id": "00000000-0000-0000-0000-000000000000",
  "statusCode": 200,
  "message": "Success",
  "data": [
    {
      "id": "00000000-0000-0000-0000-000000000000",
      "foodMenuCode": "78813eeb-e279-4d47-1f17-08d9b3274fab",
      "dateCode": "T2",
      "timeCode": 0,
      "foodId": "736531e6-bc86-4bb7-bbed-7ab6b9edaf2b",
      "foodCategoryId": "0da37baf-6e1d-43fb-9d88-5dbfe777dd80",
      "foodUnitId": "022907df-7814-4bb9-a03b-7bfe7f538c7d",
      "foodUnitName": "Cái",
      "foodName": "Bánh hot-dog nhân phômai",
      "portion": 1,
      "calorie": 129,
      "glucose": 15,
      "lipid": 5,
      "protein": 6,
      "fibre": 0,
      "note": "String",
      "image": {
        "id": "fc7b8dd0-08f6-4426-9bcb-08d8fe8c4080",
        "url": "http://diab-api-dev.savvycom.vn/App/Image/fc7b8dd0-08f6-4426-9bcb-08d8fe8c4080?expires=1638331343&signature=862e61f24e5e4e88b878f3042deaf7eeabbe01762efb0b20b87adcc96386e49f"
      },
      "foodSubstitute": true,
      "liked": false
    }
  ]
} 
*/

  String? id;
  int? statusCode;
  String? message;
  List<FoodSuggestResponseData?>? data;

  FoodSuggestResponse({
    this.id,
    this.statusCode,
    this.message,
    this.data,
  });

  List<FoodModel> get foodModelList {
    final List<FoodModel> foodModelList = [];
    for (final FoodSuggestResponseData? food in data ?? []) {
      final FoodModel? foodModel = food?.foodModel;
      if (foodModel != null) {
        foodModelList.add(foodModel);
      }
    }
    return foodModelList;
  }

  FoodSuggestResponse.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    statusCode = json['statusCode']?.toInt();
    message = json['message']?.toString();
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <FoodSuggestResponseData>[];
      v.forEach((v) {
        arr0.add(FoodSuggestResponseData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['statusCode'] = statusCode;
    data['message'] = message;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }
}
