///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class LatestHba1cInputResponse {
/*
{
  "id": "00000000-0000-0000-0000-000000000000",
  "statusCode": 200,
  "message": "Success",
  "data": 1.4
} 
*/

  String? id;
  int? statusCode;
  String? message;
  double? data;

  LatestHba1cInputResponse({
    this.id,
    this.statusCode,
    this.message,
    this.data,
  });
  LatestHba1cInputResponse.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toString();
    statusCode = json["statusCode"]?.toInt();
    message = json["message"]?.toString();
    data = json["data"]?.toDouble();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["statusCode"] = statusCode;
    data["message"] = message;
    data["data"] = this.data;
    return data;
  }
}

