///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class LatestHba1cInputResponseDataImages {
/*
{
  "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "url": "string"
} 
*/

  String? id;
  String? url;

  LatestHba1cInputResponseDataImages({
    this.id,
    this.url,
  });
  LatestHba1cInputResponseDataImages.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toString();
    url = json["url"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["url"] = url;
    return data;
  }
}

class LatestHba1cInputResponseData {
/*
{
  "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "date": 0,
  "type": "string",
  "hbA1C": 0,
  "glucose": 0,
  "unit": "string",
  "description": "string",
  "color": "string",
  "fontColor": "string",
  "backgroundColor": "string",
  "borderColor": "string",
  "percentColor": "string",
  "images": [
    {
      "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "url": "string"
    }
  ]
} 
*/

  String? id;
  int? date;
  String? type;
  int? hbA1C;
  int? glucose;
  String? unit;
  String? description;
  String? color;
  String? fontColor;
  String? backgroundColor;
  String? borderColor;
  String? percentColor;
  List<LatestHba1cInputResponseDataImages?>? images;

  LatestHba1cInputResponseData({
    this.id,
    this.date,
    this.type,
    this.hbA1C,
    this.glucose,
    this.unit,
    this.description,
    this.color,
    this.fontColor,
    this.backgroundColor,
    this.borderColor,
    this.percentColor,
    this.images,
  });
  LatestHba1cInputResponseData.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toString();
    date = json["date"]?.toInt();
    type = json["type"]?.toString();
    hbA1C = json["hbA1C"]?.toInt();
    glucose = json["glucose"]?.toInt();
    unit = json["unit"]?.toString();
    description = json["description"]?.toString();
    color = json["color"]?.toString();
    fontColor = json["fontColor"]?.toString();
    backgroundColor = json["backgroundColor"]?.toString();
    borderColor = json["borderColor"]?.toString();
    percentColor = json["percentColor"]?.toString();
  if (json["images"] != null) {
  final v = json["images"];
  final arr0 = <LatestHba1cInputResponseDataImages>[];
  v.forEach((v) {
  arr0.add(LatestHba1cInputResponseDataImages.fromJson(v));
  });
    images = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["date"] = date;
    data["type"] = type;
    data["hbA1C"] = hbA1C;
    data["glucose"] = glucose;
    data["unit"] = unit;
    data["description"] = description;
    data["color"] = color;
    data["fontColor"] = fontColor;
    data["backgroundColor"] = backgroundColor;
    data["borderColor"] = borderColor;
    data["percentColor"] = percentColor;
    if (images != null) {
      final v = images;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data["images"] = arr0;
    }
    return data;
  }
}

class LatestHba1cInputResponseMeta {
/*
{
  "success": true
} 
*/

  bool? success;

  LatestHba1cInputResponseMeta({
    this.success,
  });
  LatestHba1cInputResponseMeta.fromJson(Map<String, dynamic> json) {
    success = json["success"];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["success"] = success;
    return data;
  }
}

class LatestHba1cInputResponse {
/*
{
  "meta": {
    "success": true
  },
  "data": {
    "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
    "date": 0,
    "type": "string",
    "hbA1C": 0,
    "glucose": 0,
    "unit": "string",
    "description": "string",
    "color": "string",
    "fontColor": "string",
    "backgroundColor": "string",
    "borderColor": "string",
    "percentColor": "string",
    "images": [
      {
        "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
        "url": "string"
      }
    ]
  }
} 
*/

  LatestHba1cInputResponseMeta? meta;
  LatestHba1cInputResponseData? data;

  LatestHba1cInputResponse({
    this.meta,
    this.data,
  });
  LatestHba1cInputResponse.fromJson(Map<String, dynamic> json) {
    meta = (json["meta"] != null) ? LatestHba1cInputResponseMeta.fromJson(json["meta"]) : null;
    data = (json["data"] != null) ? LatestHba1cInputResponseData.fromJson(json["data"]) : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (meta != null) {
      data["meta"] = meta!.toJson();
    }
    if (data != null) {
      data["data"] = this.data!.toJson();
    }
    return data;
  }
}

