import 'package:medical/res/R.dart';
import 'package:medical/src/modal/base/images.dart';
import 'package:medical/src/model/response/quiz_lesson.dart';
import 'package:medical/src/utils/const.dart';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///

class LessonSectionListResponseDataLessonTagsGroup {
/*
{
  "disabled": true,
  "name": "string"
} 
*/

  bool? disabled;
  String? name;

  LessonSectionListResponseDataLessonTagsGroup({
    this.disabled,
    this.name,
  });
  LessonSectionListResponseDataLessonTagsGroup.fromJson(
      Map<String, dynamic> json) {
    disabled = json['disabled'];
    name = json['name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['disabled'] = disabled;
    data['name'] = name;
    return data;
  }
}

class LessonSectionListResponseDataLessonTags {
/*
{
  "disabled": true,
  "group": {
    "disabled": true,
    "name": "string"
  },
  "selected": true,
  "text": "string",
  "value": "string"
} 
*/

  bool? disabled;
  LessonSectionListResponseDataLessonTagsGroup? group;
  bool? selected;
  String? text;
  String? value;

  LessonSectionListResponseDataLessonTags({
    this.disabled,
    this.group,
    this.selected,
    this.text,
    this.value,
  });
  LessonSectionListResponseDataLessonTags.fromJson(Map<String, dynamic> json) {
    disabled = json['disabled'];
    group = (json['group'] != null)
        ? LessonSectionListResponseDataLessonTagsGroup.fromJson(json['group'])
        : null;
    selected = json['selected'];
    text = json['text']?.toString();
    value = json['value']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['disabled'] = disabled;
    if (group != null) {
      data['group'] = group!.toJson();
    }
    data['selected'] = selected;
    data['text'] = text;
    data['value'] = value;
    return data;
  }
}

class LessonSectionListResponseDataLessonLevelsGroup {
/*
{
  "disabled": true,
  "name": "string"
} 
*/

  bool? disabled;
  String? name;

  LessonSectionListResponseDataLessonLevelsGroup({
    this.disabled,
    this.name,
  });
  LessonSectionListResponseDataLessonLevelsGroup.fromJson(
      Map<String, dynamic> json) {
    disabled = json['disabled'];
    name = json['name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['disabled'] = disabled;
    data['name'] = name;
    return data;
  }
}

class LessonSectionListResponseDataLessonLevels {
/*
{
  "disabled": true,
  "group": {
    "disabled": true,
    "name": "string"
  },
  "selected": true,
  "text": "string",
  "value": "string"
} 
*/

  bool? disabled;
  LessonSectionListResponseDataLessonLevelsGroup? group;
  bool? selected;
  String? text;
  String? value;

  LessonSectionListResponseDataLessonLevels({
    this.disabled,
    this.group,
    this.selected,
    this.text,
    this.value,
  });
  LessonSectionListResponseDataLessonLevels.fromJson(
      Map<String, dynamic> json) {
    disabled = json['disabled'];
    group = (json['group'] != null)
        ? LessonSectionListResponseDataLessonLevelsGroup.fromJson(json['group'])
        : null;
    selected = json['selected'];
    text = json['text']?.toString();
    value = json['value']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['disabled'] = disabled;
    if (group != null) {
      data['group'] = group!.toJson();
    }
    data['selected'] = selected;
    data['text'] = text;
    data['value'] = value;
    return data;
  }
}

class LessonSectionListResponseDataLessonTypesGroup {
/*
{
  "disabled": true,
  "name": "string"
} 
*/

  bool? disabled;
  String? name;

  LessonSectionListResponseDataLessonTypesGroup({
    this.disabled,
    this.name,
  });
  LessonSectionListResponseDataLessonTypesGroup.fromJson(
      Map<String, dynamic> json) {
    disabled = json['disabled'];
    name = json['name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['disabled'] = disabled;
    data['name'] = name;
    return data;
  }
}

class LessonSectionListResponseDataLessonTypes {
/*
{
  "disabled": true,
  "group": {
    "disabled": true,
    "name": "string"
  },
  "selected": true,
  "text": "string",
  "value": "string"
} 
*/

  bool? disabled;
  LessonSectionListResponseDataLessonTypesGroup? group;
  bool? selected;
  String? text;
  String? value;

  LessonSectionListResponseDataLessonTypes({
    this.disabled,
    this.group,
    this.selected,
    this.text,
    this.value,
  });
  LessonSectionListResponseDataLessonTypes.fromJson(Map<String, dynamic> json) {
    disabled = json['disabled'];
    group = (json['group'] != null)
        ? LessonSectionListResponseDataLessonTypesGroup.fromJson(json['group'])
        : null;
    selected = json['selected'];
    text = json['text']?.toString();
    value = json['value']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['disabled'] = disabled;
    if (group != null) {
      data['group'] = group!.toJson();
    }
    data['selected'] = selected;
    data['text'] = text;
    data['value'] = value;
    return data;
  }
}

class LessonSectionListResponseDataLessonModulesGroup {
/*
{
  "disabled": true,
  "name": "string"
} 
*/

  bool? disabled;
  String? name;

  LessonSectionListResponseDataLessonModulesGroup({
    this.disabled,
    this.name,
  });
  LessonSectionListResponseDataLessonModulesGroup.fromJson(
      Map<String, dynamic> json) {
    disabled = json['disabled'];
    name = json['name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['disabled'] = disabled;
    data['name'] = name;
    return data;
  }
}

class LessonSectionListResponseDataLessonModules {
/*
{
  "disabled": true,
  "group": {
    "disabled": true,
    "name": "string"
  },
  "selected": true,
  "text": "string",
  "value": "string"
} 
*/

  bool? disabled;
  LessonSectionListResponseDataLessonModulesGroup? group;
  bool? selected;
  String? text;
  String? value;

  LessonSectionListResponseDataLessonModules({
    this.disabled,
    this.group,
    this.selected,
    this.text,
    this.value,
  });
  LessonSectionListResponseDataLessonModules.fromJson(
      Map<String, dynamic> json) {
    disabled = json['disabled'];
    group = (json['group'] != null)
        ? LessonSectionListResponseDataLessonModulesGroup.fromJson(
            json['group'])
        : null;
    selected = json['selected'];
    text = json['text']?.toString();
    value = json['value']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['disabled'] = disabled;
    if (group != null) {
      data['group'] = group!.toJson();
    }
    data['selected'] = selected;
    data['text'] = text;
    data['value'] = value;
    return data;
  }
}

class LessonSectionListResponseDataLessonStatesGroup {
/*
{
  "disabled": true,
  "name": "string"
} 
*/

  bool? disabled;
  String? name;

  LessonSectionListResponseDataLessonStatesGroup({
    this.disabled,
    this.name,
  });
  LessonSectionListResponseDataLessonStatesGroup.fromJson(
      Map<String, dynamic> json) {
    disabled = json['disabled'];
    name = json['name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['disabled'] = disabled;
    data['name'] = name;
    return data;
  }
}

class LessonSectionListResponseDataLessonStates {
/*
{
  "disabled": true,
  "group": {
    "disabled": true,
    "name": "string"
  },
  "selected": true,
  "text": "string",
  "value": "string"
} 
*/

  bool? disabled;
  LessonSectionListResponseDataLessonStatesGroup? group;
  bool? selected;
  String? text;
  String? value;

  LessonSectionListResponseDataLessonStates({
    this.disabled,
    this.group,
    this.selected,
    this.text,
    this.value,
  });
  LessonSectionListResponseDataLessonStates.fromJson(
      Map<String, dynamic> json) {
    disabled = json['disabled'];
    group = (json['group'] != null)
        ? LessonSectionListResponseDataLessonStatesGroup.fromJson(json['group'])
        : null;
    selected = json['selected'];
    text = json['text']?.toString();
    value = json['value']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['disabled'] = disabled;
    if (group != null) {
      data['group'] = group!.toJson();
    }
    data['selected'] = selected;
    data['text'] = text;
    data['value'] = value;
    return data;
  }
}

class LessonSectionListResponseDataLessonReviews {
/*
{
  "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "lessonId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "accountId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "rating": 1,
  "note": "string"
} 
*/

  String? id;
  String? lessonId;
  String? accountId;
  int? rating;
  String? note;

  LessonSectionListResponseDataLessonReviews({
    this.id,
    this.lessonId,
    this.accountId,
    this.rating,
    this.note,
  });
  LessonSectionListResponseDataLessonReviews.fromJson(
      Map<String, dynamic> json) {
    id = json['id']?.toString();
    lessonId = json['lessonId']?.toString();
    accountId = json['accountId']?.toString();
    rating = json['rating']?.toInt();
    note = json['note']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['lessonId'] = lessonId;
    data['accountId'] = accountId;
    data['rating'] = rating;
    data['note'] = note;
    return data;
  }
}

class LessonSectionListResponseDataLessonSectionsLessonSectionTypesGroup {
/*
{
  "disabled": true,
  "name": "string"
} 
*/

  bool? disabled;
  String? name;

  LessonSectionListResponseDataLessonSectionsLessonSectionTypesGroup({
    this.disabled,
    this.name,
  });
  LessonSectionListResponseDataLessonSectionsLessonSectionTypesGroup.fromJson(
      Map<String, dynamic> json) {
    disabled = json['disabled'];
    name = json['name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['disabled'] = disabled;
    data['name'] = name;
    return data;
  }
}

class LessonSectionListResponseDataLessonSectionsLessonSectionTypes {
/*
{
  "disabled": true,
  "group": {
    "disabled": true,
    "name": "string"
  },
  "selected": true,
  "text": "string",
  "value": "string"
} 
*/

  bool? disabled;
  LessonSectionListResponseDataLessonSectionsLessonSectionTypesGroup? group;
  bool? selected;
  String? text;
  String? value;

  LessonSectionListResponseDataLessonSectionsLessonSectionTypes({
    this.disabled,
    this.group,
    this.selected,
    this.text,
    this.value,
  });
  LessonSectionListResponseDataLessonSectionsLessonSectionTypes.fromJson(
      Map<String, dynamic> json) {
    disabled = json['disabled'];
    group = (json['group'] != null)
        ? LessonSectionListResponseDataLessonSectionsLessonSectionTypesGroup
            .fromJson(json['group'])
        : null;
    selected = json['selected'];
    text = json['text']?.toString();
    value = json['value']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['disabled'] = disabled;
    if (group != null) {
      data['group'] = group!.toJson();
    }
    data['selected'] = selected;
    data['text'] = text;
    data['value'] = value;
    return data;
  }
}

class LessonSectionListResponseDataLessonSectionsLessonSectionStatesGroup {
/*
{
  "disabled": true,
  "name": "string"
} 
*/

  bool? disabled;
  String? name;

  LessonSectionListResponseDataLessonSectionsLessonSectionStatesGroup({
    this.disabled,
    this.name,
  });
  LessonSectionListResponseDataLessonSectionsLessonSectionStatesGroup.fromJson(
      Map<String, dynamic> json) {
    disabled = json['disabled'];
    name = json['name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['disabled'] = disabled;
    data['name'] = name;
    return data;
  }
}

class LessonSectionListResponseDataLessonSectionsLessonSectionStates {
/*
{
  "disabled": true,
  "group": {
    "disabled": true,
    "name": "string"
  },
  "selected": true,
  "text": "string",
  "value": "string"
} 
*/

  bool? disabled;
  LessonSectionListResponseDataLessonSectionsLessonSectionStatesGroup? group;
  bool? selected;
  String? text;
  String? value;

  LessonSectionListResponseDataLessonSectionsLessonSectionStates({
    this.disabled,
    this.group,
    this.selected,
    this.text,
    this.value,
  });
  LessonSectionListResponseDataLessonSectionsLessonSectionStates.fromJson(
      Map<String, dynamic> json) {
    disabled = json['disabled'];
    group = (json['group'] != null)
        ? LessonSectionListResponseDataLessonSectionsLessonSectionStatesGroup
            .fromJson(json['group'])
        : null;
    selected = json['selected'];
    text = json['text']?.toString();
    value = json['value']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['disabled'] = disabled;
    if (group != null) {
      data['group'] = group!.toJson();
    }
    data['selected'] = selected;
    data['text'] = text;
    data['value'] = value;
    return data;
  }
}

class LessonSectionListResponseDataLessonSectionsLessonAccounts {
/*
{
  "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "code": "string",
  "accountId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "lessonId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "lessonType": 1,
  "lessonSectionId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "isComplete": true
} 
*/

  String? id;
  String? code;
  String? accountId;
  String? lessonId;
  int? lessonType;
  String? lessonSectionId;
  bool? isComplete;

  LessonSectionListResponseDataLessonSectionsLessonAccounts({
    this.id,
    this.code,
    this.accountId,
    this.lessonId,
    this.lessonType,
    this.lessonSectionId,
    this.isComplete,
  });
  LessonSectionListResponseDataLessonSectionsLessonAccounts.fromJson(
      Map<String, dynamic> json) {
    id = json['id']?.toString();
    code = json['code']?.toString();
    accountId = json['accountId']?.toString();
    lessonId = json['lessonId']?.toString();
    lessonType = json['lessonType']?.toInt();
    lessonSectionId = json['lessonSectionId']?.toString();
    isComplete = json['isComplete'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['code'] = code;
    data['accountId'] = accountId;
    data['lessonId'] = lessonId;
    data['lessonType'] = lessonType;
    data['lessonSectionId'] = lessonSectionId;
    data['isComplete'] = isComplete;
    return data;
  }
}

class LessonSectionListResponseDataLessonSectionsLessonSectionLinks {
/*
{
  "id": "string",
  "type": 1,
  "url": "string"
} 
*/

  String? id;
  int? type;
  String? url;

  LessonSectionListResponseDataLessonSectionsLessonSectionLinks({
    this.id,
    this.type,
    this.url,
  });
  LessonSectionListResponseDataLessonSectionsLessonSectionLinks.fromJson(
      Map<String, dynamic> json) {
    id = json['id']?.toString();
    type = json['type']?.toInt();
    url = json['url']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['type'] = type;
    data['url'] = url;
    return data;
  }
}

class LessonSectionListResponseDataLessonSectionsQuizLessonSectionsQuizQuizAnswers {
/*
{
  "name": "string",
  "isCorrect": true,
  "order": 0,
  "quizId": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
} 
*/

  String? name;
  bool? isCorrect;
  int? order;
  String? quizId;

  LessonSectionListResponseDataLessonSectionsQuizLessonSectionsQuizQuizAnswers({
    this.name,
    this.isCorrect,
    this.order,
    this.quizId,
  });
  LessonSectionListResponseDataLessonSectionsQuizLessonSectionsQuizQuizAnswers.fromJson(
      Map<String, dynamic> json) {
    name = json['name']?.toString();
    isCorrect = json['isCorrect'];
    order = json['order']?.toInt();
    quizId = json['quizId']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['name'] = name;
    data['isCorrect'] = isCorrect;
    data['order'] = order;
    data['quizId'] = quizId;
    return data;
  }
}

class LessonSectionListResponseDataLessonSectionsQuizLessonSectionsQuiz {
/*
{
  "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "code": "string",
  "name": "string",
  "status": 0,
  "type": "string",
  "lessonLevel": "string",
  "lesson": "string",
  "quizAnswers": [
    {
      "name": "string",
      "isCorrect": true,
      "order": 0,
      "quizId": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
    }
  ]
} 
*/

  String? id;
  String? code;
  String? name;
  int? status;
  String? type;
  String? lessonLevel;
  String? lesson;
  List<LessonSectionListResponseDataLessonSectionsQuizLessonSectionsQuizQuizAnswers?>?
      quizAnswers;

  LessonSectionListResponseDataLessonSectionsQuizLessonSectionsQuiz({
    this.id,
    this.code,
    this.name,
    this.status,
    this.type,
    this.lessonLevel,
    this.lesson,
    this.quizAnswers,
  });
  LessonSectionListResponseDataLessonSectionsQuizLessonSectionsQuiz.fromJson(
      Map<String, dynamic> json) {
    id = json['id']?.toString();
    code = json['code']?.toString();
    name = json['name']?.toString();
    status = json['status']?.toInt();
    type = json['type']?.toString();
    lessonLevel = json['lessonLevel']?.toString();
    lesson = json['lesson']?.toString();
    if (json['quizAnswers'] != null) {
      final v = json['quizAnswers'];
      final arr0 = <
          LessonSectionListResponseDataLessonSectionsQuizLessonSectionsQuizQuizAnswers>[];
      v.forEach((v) {
        arr0.add(
            LessonSectionListResponseDataLessonSectionsQuizLessonSectionsQuizQuizAnswers
                .fromJson(v));
      });
      quizAnswers = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['code'] = code;
    data['name'] = name;
    data['status'] = status;
    data['type'] = type;
    data['lessonLevel'] = lessonLevel;
    data['lesson'] = lesson;
    if (quizAnswers != null) {
      final v = quizAnswers;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['quizAnswers'] = arr0;
    }
    return data;
  }
}

class LessonSectionListResponseDataLessonSections {
/*
{
  "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "code": "string",
  "lessonId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "name": "string",
  "type": 1,
  "status": 0,
  "content": "string",
  "order": 0,
  "quizLessonSections": [
    {
      "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "quizId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "lessonSectionId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "quiz": {
        "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
        "code": "string",
        "name": "string",
        "status": 0,
        "type": "string",
        "lessonLevel": "string",
        "lesson": "string",
        "quizAnswers": [
          {
            "name": "string",
            "isCorrect": true,
            "order": 0,
            "quizId": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
          }
        ]
      }
    }
  ],
  "lessonSectionLinks": [
    {
      "id": "string",
      "type": 1,
      "url": "string"
    }
  ],
  "lessonAccounts": [
    {
      "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "code": "string",
      "accountId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "lessonId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "lessonType": 1,
      "lessonSectionId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "isComplete": true
    }
  ],
  "isComplete": true,
  "lessonSectionStates": [
    {
      "disabled": true,
      "group": {
        "disabled": true,
        "name": "string"
      },
      "selected": true,
      "text": "string",
      "value": "string"
    }
  ],
  "lessonSectionTypes": [
    {
      "disabled": true,
      "group": {
        "disabled": true,
        "name": "string"
      },
      "selected": true,
      "text": "string",
      "value": "string"
    }
  ]
} 
*/

  String? id;
  String? code;
  String? lessonId;
  String? name;
  int? type;
  int? status;
  String? content;
  int? order;
  List<QuizLesson?>? quizLessonSections;
  List<LessonSectionListResponseDataLessonSectionsLessonSectionLinks?>?
      lessonSectionLinks;
  List<LessonSectionListResponseDataLessonSectionsLessonAccounts?>?
      lessonAccounts;
  bool? isComplete;
  List<LessonSectionListResponseDataLessonSectionsLessonSectionStates?>?
      lessonSectionStates;
  List<LessonSectionListResponseDataLessonSectionsLessonSectionTypes?>?
      lessonSectionTypes;

  LessonSectionListResponseDataLessonSections({
    this.id,
    this.code,
    this.lessonId,
    this.name,
    this.type,
    this.status,
    this.content,
    this.order,
    this.quizLessonSections,
    this.lessonSectionLinks,
    this.lessonAccounts,
    this.isComplete,
    this.lessonSectionStates,
    this.lessonSectionTypes,
  });

  List<String> get sourceUrls {
    final List<String> sourceUrls =
        lessonSectionLinks?.map((item) => item?.url ?? '').toList() ?? [];
    return sourceUrls;
  }

  String get icon {
    if (type == Const.LESSON_SECTION_TYPE_VIDEO)
      return R.drawable.ic_lesson_section_video;
    if (type == Const.LESSON_SECTION_TYPE_AUDIO)
      return R.drawable.ic_lesson_section_audio;
    if (type == Const.LESSON_SECTION_TYPE_TEXT)
      return R.drawable.ic_lesson_section_text;
    if (type == Const.LESSON_SECTION_TYPE_QUIZ)
    return R.drawable.ic_question_circle;
    return '';
  }

  LessonSectionListResponseDataLessonSections.fromJson(
      Map<String, dynamic> json) {
    id = json['id']?.toString();
    code = json['code']?.toString();
    lessonId = json['lessonId']?.toString();
    name = json['name']?.toString();
    type = json['type']?.toInt();
    status = json['status']?.toInt();
    content = json['content']?.toString();
    order = json['order']?.toInt();
    if (json['quizLessonSections'] != null) {
      final v = json['quizLessonSections'];
      final arr0 = <QuizLesson>[];
      v.forEach((v) {
        arr0.add(QuizLesson.fromJson(v));
      });
      quizLessonSections = arr0;
    }
    if (json['lessonSectionLinks'] != null) {
      final v = json['lessonSectionLinks'];
      final arr0 =
          <LessonSectionListResponseDataLessonSectionsLessonSectionLinks>[];
      v.forEach((v) {
        arr0.add(LessonSectionListResponseDataLessonSectionsLessonSectionLinks
            .fromJson(v));
      });
      lessonSectionLinks = arr0;
    }
    if (json['lessonAccounts'] != null) {
      final v = json['lessonAccounts'];
      final arr0 =
          <LessonSectionListResponseDataLessonSectionsLessonAccounts>[];
      v.forEach((v) {
        arr0.add(
            LessonSectionListResponseDataLessonSectionsLessonAccounts.fromJson(
                v));
      });
      lessonAccounts = arr0;
    }
    isComplete = json['isComplete'];
    if (json['lessonSectionStates'] != null) {
      final v = json['lessonSectionStates'];
      final arr0 =
          <LessonSectionListResponseDataLessonSectionsLessonSectionStates>[];
      v.forEach((v) {
        arr0.add(LessonSectionListResponseDataLessonSectionsLessonSectionStates
            .fromJson(v));
      });
      lessonSectionStates = arr0;
    }
    if (json['lessonSectionTypes'] != null) {
      final v = json['lessonSectionTypes'];
      final arr0 =
          <LessonSectionListResponseDataLessonSectionsLessonSectionTypes>[];
      v.forEach((v) {
        arr0.add(LessonSectionListResponseDataLessonSectionsLessonSectionTypes
            .fromJson(v));
      });
      lessonSectionTypes = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['code'] = code;
    data['lessonId'] = lessonId;
    data['name'] = name;
    data['type'] = type;
    data['status'] = status;
    data['content'] = content;
    data['order'] = order;
    if (quizLessonSections != null) {
      final v = quizLessonSections;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['quizLessonSections'] = arr0;
    }
    if (lessonSectionLinks != null) {
      final v = lessonSectionLinks;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['lessonSectionLinks'] = arr0;
    }
    if (lessonAccounts != null) {
      final v = lessonAccounts;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['lessonAccounts'] = arr0;
    }
    data['isComplete'] = isComplete;
    if (lessonSectionStates != null) {
      final v = lessonSectionStates;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['lessonSectionStates'] = arr0;
    }
    if (lessonSectionTypes != null) {
      final v = lessonSectionTypes;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['lessonSectionTypes'] = arr0;
    }
    return data;
  }
}

class LessonSectionListResponseDataLessonTagMappings {
/*
{
  "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "lessonId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "lessonTagId": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
} 
*/

  String? id;
  String? lessonId;
  String? lessonTagId;

  LessonSectionListResponseDataLessonTagMappings({
    this.id,
    this.lessonId,
    this.lessonTagId,
  });
  LessonSectionListResponseDataLessonTagMappings.fromJson(
      Map<String, dynamic> json) {
    id = json['id']?.toString();
    lessonId = json['lessonId']?.toString();
    lessonTagId = json['lessonTagId']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['lessonId'] = lessonId;
    data['lessonTagId'] = lessonTagId;
    return data;
  }
}

class LessonSectionListResponseDataQuizLessonsQuizQuizAnswers {
/*
{
  "name": "string",
  "isCorrect": true,
  "order": 0,
  "quizId": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
} 
*/

  String? name;
  bool? isCorrect;
  int? order;
  String? quizId;

  LessonSectionListResponseDataQuizLessonsQuizQuizAnswers({
    this.name,
    this.isCorrect,
    this.order,
    this.quizId,
  });
  LessonSectionListResponseDataQuizLessonsQuizQuizAnswers.fromJson(
      Map<String, dynamic> json) {
    name = json['name']?.toString();
    isCorrect = json['isCorrect'];
    order = json['order']?.toInt();
    quizId = json['quizId']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['name'] = name;
    data['isCorrect'] = isCorrect;
    data['order'] = order;
    data['quizId'] = quizId;
    return data;
  }
}

class LessonSectionListResponseDataQuizLessonsQuiz {
/*
{
  "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "code": "string",
  "name": "string",
  "status": 0,
  "type": "string",
  "lessonLevel": "string",
  "lesson": "string",
  "quizAnswers": [
    {
      "name": "string",
      "isCorrect": true,
      "order": 0,
      "quizId": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
    }
  ]
} 
*/

  String? id;
  String? code;
  String? name;
  int? status;
  String? type;
  String? lessonLevel;
  String? lesson;
  List<LessonSectionListResponseDataQuizLessonsQuizQuizAnswers?>? quizAnswers;

  LessonSectionListResponseDataQuizLessonsQuiz({
    this.id,
    this.code,
    this.name,
    this.status,
    this.type,
    this.lessonLevel,
    this.lesson,
    this.quizAnswers,
  });
  LessonSectionListResponseDataQuizLessonsQuiz.fromJson(
      Map<String, dynamic> json) {
    id = json['id']?.toString();
    code = json['code']?.toString();
    name = json['name']?.toString();
    status = json['status']?.toInt();
    type = json['type']?.toString();
    lessonLevel = json['lessonLevel']?.toString();
    lesson = json['lesson']?.toString();
    if (json['quizAnswers'] != null) {
      final v = json['quizAnswers'];
      final arr0 = <LessonSectionListResponseDataQuizLessonsQuizQuizAnswers>[];
      v.forEach((v) {
        arr0.add(
            LessonSectionListResponseDataQuizLessonsQuizQuizAnswers.fromJson(
                v));
      });
      quizAnswers = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['code'] = code;
    data['name'] = name;
    data['status'] = status;
    data['type'] = type;
    data['lessonLevel'] = lessonLevel;
    data['lesson'] = lesson;
    if (quizAnswers != null) {
      final v = quizAnswers;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['quizAnswers'] = arr0;
    }
    return data;
  }
}

class LessonSectionListResponseDataQuizLessons {
/*
{
  "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "code": "string",
  "quizId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "lessonId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "quiz": {
    "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
    "code": "string",
    "name": "string",
    "status": 0,
    "type": "string",
    "lessonLevel": "string",
    "lesson": "string",
    "quizAnswers": [
      {
        "name": "string",
        "isCorrect": true,
        "order": 0,
        "quizId": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
      }
    ]
  }
} 
*/

  String? id;
  String? code;
  String? quizId;
  String? lessonId;
  LessonSectionListResponseDataQuizLessonsQuiz? quiz;

  LessonSectionListResponseDataQuizLessons({
    this.id,
    this.code,
    this.quizId,
    this.lessonId,
    this.quiz,
  });
  LessonSectionListResponseDataQuizLessons.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    code = json['code']?.toString();
    quizId = json['quizId']?.toString();
    lessonId = json['lessonId']?.toString();
    quiz = (json['quiz'] != null)
        ? LessonSectionListResponseDataQuizLessonsQuiz.fromJson(json['quiz'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['code'] = code;
    data['quizId'] = quizId;
    data['lessonId'] = lessonId;
    if (quiz != null) {
      data['quiz'] = quiz!.toJson();
    }
    return data;
  }
}

class LessonSectionListResponseData {
/*
{
  "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "code": "string",
  "name": "string",
  "description": "string",
  "status": 0,
  "type": 1,
  "order": 0,
  "isEnabledRating": true,
  "minCompletePercent": 0,
  "coverId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "lessonModuleId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "lessonLevelId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "quizLessons": [
    {
      "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "code": "string",
      "quizId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "lessonId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "quiz": {
        "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
        "code": "string",
        "name": "string",
        "status": 0,
        "type": "string",
        "lessonLevel": "string",
        "lesson": "string",
        "quizAnswers": [
          {
            "name": "string",
            "isCorrect": true,
            "order": 0,
            "quizId": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
          }
        ]
      }
    }
  ],
  "lessonTagMappings": [
    {
      "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "lessonId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "lessonTagId": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
    }
  ],
  "lessonSections": [
    {
      "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "code": "string",
      "lessonId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "name": "string",
      "type": 1,
      "status": 0,
      "content": "string",
      "order": 0,
      "quizLessonSections": [
        {
          "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
          "quizId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
          "lessonSectionId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
          "quiz": {
            "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
            "code": "string",
            "name": "string",
            "status": 0,
            "type": "string",
            "lessonLevel": "string",
            "lesson": "string",
            "quizAnswers": [
              {
                "name": "string",
                "isCorrect": true,
                "order": 0,
                "quizId": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
              }
            ]
          }
        }
      ],
      "lessonSectionLinks": [
        {
          "id": "string",
          "type": 1,
          "url": "string"
        }
      ],
      "lessonAccounts": [
        {
          "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
          "code": "string",
          "accountId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
          "lessonId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
          "lessonType": 1,
          "lessonSectionId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
          "isComplete": true
        }
      ],
      "isComplete": true,
      "lessonSectionStates": [
        {
          "disabled": true,
          "group": {
            "disabled": true,
            "name": "string"
          },
          "selected": true,
          "text": "string",
          "value": "string"
        }
      ],
      "lessonSectionTypes": [
        {
          "disabled": true,
          "group": {
            "disabled": true,
            "name": "string"
          },
          "selected": true,
          "text": "string",
          "value": "string"
        }
      ]
    }
  ],
  "lessonReviews": [
    {
      "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "lessonId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "accountId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "rating": 1,
      "note": "string"
    }
  ],
  "lessonStates": [
    {
      "disabled": true,
      "group": {
        "disabled": true,
        "name": "string"
      },
      "selected": true,
      "text": "string",
      "value": "string"
    }
  ],
  "lessonModules": [
    {
      "disabled": true,
      "group": {
        "disabled": true,
        "name": "string"
      },
      "selected": true,
      "text": "string",
      "value": "string"
    }
  ],
  "lessonTypes": [
    {
      "disabled": true,
      "group": {
        "disabled": true,
        "name": "string"
      },
      "selected": true,
      "text": "string",
      "value": "string"
    }
  ],
  "lessonLevels": [
    {
      "disabled": true,
      "group": {
        "disabled": true,
        "name": "string"
      },
      "selected": true,
      "text": "string",
      "value": "string"
    }
  ],
  "lessonTags": [
    {
      "disabled": true,
      "group": {
        "disabled": true,
        "name": "string"
      },
      "selected": true,
      "text": "string",
      "value": "string"
    }
  ],
  "image": {
    "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
    "url": "string"
  }
} 
*/

  String? id;
  String? code;
  String? name;
  String? description;
  int? status;
  int? type;
  int? order;
  bool? isEnabledRating;
  int? minCompletePercent;
  String? coverId;
  String? lessonModuleId;
  String? lessonLevelId;
  List<LessonSectionListResponseDataQuizLessons?>? quizLessons;
  List<LessonSectionListResponseDataLessonTagMappings?>? lessonTagMappings;
  List<LessonSectionListResponseDataLessonSections?>? lessonSections;
  List<LessonSectionListResponseDataLessonReviews?>? lessonReviews;
  List<LessonSectionListResponseDataLessonStates?>? lessonStates;
  List<LessonSectionListResponseDataLessonModules?>? lessonModules;
  List<LessonSectionListResponseDataLessonTypes?>? lessonTypes;
  List<LessonSectionListResponseDataLessonLevels?>? lessonLevels;
  List<LessonSectionListResponseDataLessonTags?>? lessonTags;
  ImagesModel? image;

  LessonSectionListResponseData({
    this.id,
    this.code,
    this.name,
    this.description,
    this.status,
    this.type,
    this.order,
    this.isEnabledRating,
    this.minCompletePercent,
    this.coverId,
    this.lessonModuleId,
    this.lessonLevelId,
    this.quizLessons,
    this.lessonTagMappings,
    this.lessonSections,
    this.lessonReviews,
    this.lessonStates,
    this.lessonModules,
    this.lessonTypes,
    this.lessonLevels,
    this.lessonTags,
    this.image,
  });
  LessonSectionListResponseData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    code = json['code']?.toString();
    name = json['name']?.toString();
    description = json['description']?.toString();
    status = json['status']?.toInt();
    type = json['type']?.toInt();
    order = json['order']?.toInt();
    isEnabledRating = json['isEnabledRating'];
    minCompletePercent = json['minCompletePercent']?.toInt();
    coverId = json['coverId']?.toString();
    lessonModuleId = json['lessonModuleId']?.toString();
    lessonLevelId = json['lessonLevelId']?.toString();
    if (json['quizLessons'] != null) {
      final v = json['quizLessons'];
      final arr0 = <LessonSectionListResponseDataQuizLessons>[];
      v.forEach((v) {
        arr0.add(LessonSectionListResponseDataQuizLessons.fromJson(v));
      });
      quizLessons = arr0;
    }
    if (json['lessonTagMappings'] != null) {
      final v = json['lessonTagMappings'];
      final arr0 = <LessonSectionListResponseDataLessonTagMappings>[];
      v.forEach((v) {
        arr0.add(LessonSectionListResponseDataLessonTagMappings.fromJson(v));
      });
      lessonTagMappings = arr0;
    }
    if (json['lessonSections'] != null) {
      final v = json['lessonSections'];
      final arr0 = <LessonSectionListResponseDataLessonSections>[];
      v.forEach((v) {
        arr0.add(LessonSectionListResponseDataLessonSections.fromJson(v));
      });
      lessonSections = arr0;
    }
    if (json['lessonReviews'] != null) {
      final v = json['lessonReviews'];
      final arr0 = <LessonSectionListResponseDataLessonReviews>[];
      v.forEach((v) {
        arr0.add(LessonSectionListResponseDataLessonReviews.fromJson(v));
      });
      lessonReviews = arr0;
    }
    if (json['lessonStates'] != null) {
      final v = json['lessonStates'];
      final arr0 = <LessonSectionListResponseDataLessonStates>[];
      v.forEach((v) {
        arr0.add(LessonSectionListResponseDataLessonStates.fromJson(v));
      });
      lessonStates = arr0;
    }
    if (json['lessonModules'] != null) {
      final v = json['lessonModules'];
      final arr0 = <LessonSectionListResponseDataLessonModules>[];
      v.forEach((v) {
        arr0.add(LessonSectionListResponseDataLessonModules.fromJson(v));
      });
      lessonModules = arr0;
    }
    if (json['lessonTypes'] != null) {
      final v = json['lessonTypes'];
      final arr0 = <LessonSectionListResponseDataLessonTypes>[];
      v.forEach((v) {
        arr0.add(LessonSectionListResponseDataLessonTypes.fromJson(v));
      });
      lessonTypes = arr0;
    }
    if (json['lessonLevels'] != null) {
      final v = json['lessonLevels'];
      final arr0 = <LessonSectionListResponseDataLessonLevels>[];
      v.forEach((v) {
        arr0.add(LessonSectionListResponseDataLessonLevels.fromJson(v));
      });
      lessonLevels = arr0;
    }
    if (json['lessonTags'] != null) {
      final v = json['lessonTags'];
      final arr0 = <LessonSectionListResponseDataLessonTags>[];
      v.forEach((v) {
        arr0.add(LessonSectionListResponseDataLessonTags.fromJson(v));
      });
      lessonTags = arr0;
    }
    image =
        (json['image'] != null) ? ImagesModel.fromJson(json['image']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['code'] = code;
    data['name'] = name;
    data['description'] = description;
    data['status'] = status;
    data['type'] = type;
    data['order'] = order;
    data['isEnabledRating'] = isEnabledRating;
    data['minCompletePercent'] = minCompletePercent;
    data['coverId'] = coverId;
    data['lessonModuleId'] = lessonModuleId;
    data['lessonLevelId'] = lessonLevelId;
    if (quizLessons != null) {
      final v = quizLessons;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['quizLessons'] = arr0;
    }
    if (lessonTagMappings != null) {
      final v = lessonTagMappings;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['lessonTagMappings'] = arr0;
    }
    if (lessonSections != null) {
      final v = lessonSections;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['lessonSections'] = arr0;
    }
    if (lessonReviews != null) {
      final v = lessonReviews;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['lessonReviews'] = arr0;
    }
    if (lessonStates != null) {
      final v = lessonStates;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['lessonStates'] = arr0;
    }
    if (lessonModules != null) {
      final v = lessonModules;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['lessonModules'] = arr0;
    }
    if (lessonTypes != null) {
      final v = lessonTypes;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['lessonTypes'] = arr0;
    }
    if (lessonLevels != null) {
      final v = lessonLevels;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['lessonLevels'] = arr0;
    }
    if (lessonTags != null) {
      final v = lessonTags;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['lessonTags'] = arr0;
    }
    if (image != null) {
      data['image'] = image!.toJson();
    }
    return data;
  }
}

class LessonSectionListResponseMeta {
/*
{
  "success": true
} 
*/

  bool? success;

  LessonSectionListResponseMeta({
    this.success,
  });
  LessonSectionListResponseMeta.fromJson(Map<String, dynamic> json) {
    success = json['success'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    return data;
  }
}

class LessonSectionListResponse {
/*
{
  "meta": {
    "success": true
  },
  "data": {
    "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
    "code": "string",
    "name": "string",
    "description": "string",
    "status": 0,
    "type": 1,
    "order": 0,
    "isEnabledRating": true,
    "minCompletePercent": 0,
    "coverId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
    "lessonModuleId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
    "lessonLevelId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
    "quizLessons": [
      {
        "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
        "code": "string",
        "quizId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
        "lessonId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
        "quiz": {
          "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
          "code": "string",
          "name": "string",
          "status": 0,
          "type": "string",
          "lessonLevel": "string",
          "lesson": "string",
          "quizAnswers": [
            {
              "name": "string",
              "isCorrect": true,
              "order": 0,
              "quizId": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
            }
          ]
        }
      }
    ],
    "lessonTagMappings": [
      {
        "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
        "lessonId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
        "lessonTagId": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
      }
    ],
    "lessonSections": [
      {
        "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
        "code": "string",
        "lessonId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
        "name": "string",
        "type": 1,
        "status": 0,
        "content": "string",
        "order": 0,
        "quizLessonSections": [
          {
            "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
            "quizId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
            "lessonSectionId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
            "quiz": {
              "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
              "code": "string",
              "name": "string",
              "status": 0,
              "type": "string",
              "lessonLevel": "string",
              "lesson": "string",
              "quizAnswers": [
                {
                  "name": "string",
                  "isCorrect": true,
                  "order": 0,
                  "quizId": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
                }
              ]
            }
          }
        ],
        "lessonSectionLinks": [
          {
            "id": "string",
            "type": 1,
            "url": "string"
          }
        ],
        "lessonAccounts": [
          {
            "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
            "code": "string",
            "accountId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
            "lessonId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
            "lessonType": 1,
            "lessonSectionId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
            "isComplete": true
          }
        ],
        "isComplete": true,
        "lessonSectionStates": [
          {
            "disabled": true,
            "group": {
              "disabled": true,
              "name": "string"
            },
            "selected": true,
            "text": "string",
            "value": "string"
          }
        ],
        "lessonSectionTypes": [
          {
            "disabled": true,
            "group": {
              "disabled": true,
              "name": "string"
            },
            "selected": true,
            "text": "string",
            "value": "string"
          }
        ]
      }
    ],
    "lessonReviews": [
      {
        "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
        "lessonId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
        "accountId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
        "rating": 1,
        "note": "string"
      }
    ],
    "lessonStates": [
      {
        "disabled": true,
        "group": {
          "disabled": true,
          "name": "string"
        },
        "selected": true,
        "text": "string",
        "value": "string"
      }
    ],
    "lessonModules": [
      {
        "disabled": true,
        "group": {
          "disabled": true,
          "name": "string"
        },
        "selected": true,
        "text": "string",
        "value": "string"
      }
    ],
    "lessonTypes": [
      {
        "disabled": true,
        "group": {
          "disabled": true,
          "name": "string"
        },
        "selected": true,
        "text": "string",
        "value": "string"
      }
    ],
    "lessonLevels": [
      {
        "disabled": true,
        "group": {
          "disabled": true,
          "name": "string"
        },
        "selected": true,
        "text": "string",
        "value": "string"
      }
    ],
    "lessonTags": [
      {
        "disabled": true,
        "group": {
          "disabled": true,
          "name": "string"
        },
        "selected": true,
        "text": "string",
        "value": "string"
      }
    ],
    "image": {
      "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "url": "string"
    }
  }
} 
*/

  LessonSectionListResponseMeta? meta;
  LessonSectionListResponseData? data;

  LessonSectionListResponse({
    this.meta,
    this.data,
  });
  LessonSectionListResponse.fromJson(Map<String, dynamic> json) {
    meta = (json['meta'] != null)
        ? LessonSectionListResponseMeta.fromJson(json['meta'])
        : null;
    data = (json['data'] != null)
        ? LessonSectionListResponseData.fromJson(json['data'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (meta != null) {
      data['meta'] = meta!.toJson();
    }
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
