import 'package:medical/res/R.dart';
import 'package:medical/src/utils/const.dart';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class LessonSectionListResponseDataLinks {
/*
{
  "id": "21623041-88f2-4a5f-ab28-08d98d5a695e",
  "type": 1,
  "url": "https://zingnews.vn/"
} 
*/

  String? id;
  int? type;
  String? url;

  LessonSectionListResponseDataLinks({
    this.id,
    this.type,
    this.url,
  });
  LessonSectionListResponseDataLinks.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toString();
    type = json["type"]?.toInt();
    url = json["url"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["type"] = type;
    data["url"] = url;
    return data;
  }
}

class LessonSectionListResponseDataQuizzesAnswers {
/*
{
  "id": "00f2200c-60ef-4cdf-01b4-08d98d6c681f",
  "name": "câu tr? l?i s?a - 2",
  "order": 0,
  "isCorrect": false
} 
*/

  String? id;
  String? name;
  int? order;
  bool? isCorrect;

  LessonSectionListResponseDataQuizzesAnswers({
    this.id,
    this.name,
    this.order,
    this.isCorrect,
  });
  LessonSectionListResponseDataQuizzesAnswers.fromJson(
      Map<String, dynamic> json) {
    id = json["id"]?.toString();
    name = json["name"]?.toString();
    order = json["order"]?.toInt();
    isCorrect = json["isCorrect"];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["name"] = name;
    data["order"] = order;
    data["isCorrect"] = isCorrect;
    return data;
  }
}

class LessonSectionListResponseDataQuizzes {
/*
{
  "name": "tên quiz ediited",
  "type": 1,
  "explain": "Gi?i thích edited",
  "answers": [
    {
      "id": "00f2200c-60ef-4cdf-01b4-08d98d6c681f",
      "name": "câu tr? l?i s?a - 2",
      "order": 0,
      "isCorrect": false
    }
  ]
} 
*/

  String? name;
  int? type;
  String? explain;
  List<LessonSectionListResponseDataQuizzesAnswers?>? answers;

  LessonSectionListResponseDataQuizzes({
    this.name,
    this.type,
    this.explain,
    this.answers,
  });
  LessonSectionListResponseDataQuizzes.fromJson(Map<String, dynamic> json) {
    name = json["name"]?.toString();
    type = json["type"]?.toInt();
    explain = json["explain"]?.toString();
    if (json["answers"] != null) {
      final v = json["answers"];
      final arr0 = <LessonSectionListResponseDataQuizzesAnswers>[];
      v.forEach((v) {
        arr0.add(LessonSectionListResponseDataQuizzesAnswers.fromJson(v));
      });
      answers = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["name"] = name;
    data["type"] = type;
    data["explain"] = explain;
    if (answers != null) {
      final v = answers;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["answers"] = arr0;
    }
    return data;
  }
}

class LessonSectionListResponseData {
/*
{
  "id": "fb3e093b-96e8-4bfd-cc4a-08d98d956006",
  "name": "Khóa h?c dinh du?ng",
  "type": 3,
  "content": "Mô t? test",
  "quizzes": [
    {
      "name": "tên quiz ediited",
      "type": 1,
      "explain": "Gi?i thích edited",
      "answers": [
        {
          "id": "00f2200c-60ef-4cdf-01b4-08d98d6c681f",
          "name": "câu tr? l?i s?a - 2",
          "order": 0,
          "isCorrect": false
        }
      ]
    }
  ],
  "links": [
    {
      "id": "21623041-88f2-4a5f-ab28-08d98d5a695e",
      "type": 1,
      "url": "https://zingnews.vn/"
    }
  ],
  "isComplete": true
} 
*/

  String? id;
  String? name;
  int? type;
  String? content;
  List<LessonSectionListResponseDataQuizzes?>? quizzes;
  List<LessonSectionListResponseDataLinks?>? links;
  bool? isComplete;

  LessonSectionListResponseData({
    this.id,
    this.name,
    this.type,
    this.content,
    this.quizzes,
    this.links,
    this.isComplete,
  });

  List<String> get sourceUrls {
    final List<String> sourceUrls =
        links?.map((item) => item?.url ?? '').toList() ?? [];
    return sourceUrls;
  }

  String get icon {
    if (type == Const.LESSON_SECTION_TYPE_VIDEO) return R.drawable.ic_lesson_section_video;
    if (type == Const.LESSON_SECTION_TYPE_AUDIO) return R.drawable.ic_lesson_section_audio;
    if (type == Const.LESSON_SECTION_TYPE_TEXT) return R.drawable.ic_lesson_section_text;
    return '';
  }

  LessonSectionListResponseData.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toString();
    name = json["name"]?.toString();
    type = json["type"]?.toInt();
    content = json["content"]?.toString();
    if (json["quizzes"] != null) {
      final v = json["quizzes"];
      final arr0 = <LessonSectionListResponseDataQuizzes>[];
      v.forEach((v) {
        arr0.add(LessonSectionListResponseDataQuizzes.fromJson(v));
      });
      quizzes = arr0;
    }
    if (json["links"] != null) {
      final v = json["links"];
      final arr0 = <LessonSectionListResponseDataLinks>[];
      v.forEach((v) {
        arr0.add(LessonSectionListResponseDataLinks.fromJson(v));
      });
      links = arr0;
    }
    isComplete = json["isComplete"];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["name"] = name;
    data["type"] = type;
    data["content"] = content;
    if (quizzes != null) {
      final v = quizzes;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["quizzes"] = arr0;
    }
    if (links != null) {
      final v = links;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["links"] = arr0;
    }
    data["isComplete"] = isComplete;
    return data;
  }
}

class LessonSectionListResponse {
/*
{
  "id": "00000000-0000-0000-0000-000000000000",
  "statusCode": 200,
  "message": "Success",
  "data": [
    {
      "id": "fb3e093b-96e8-4bfd-cc4a-08d98d956006",
      "name": "Khóa h?c dinh du?ng",
      "type": 3,
      "content": "Mô t? test",
      "quizzes": [
        {
          "name": "tên quiz ediited",
          "type": 1,
          "explain": "Gi?i thích edited",
          "answers": [
            {
              "id": "00f2200c-60ef-4cdf-01b4-08d98d6c681f",
              "name": "câu tr? l?i s?a - 2",
              "order": 0,
              "isCorrect": false
            }
          ]
        }
      ],
      "links": [
        {
          "id": "21623041-88f2-4a5f-ab28-08d98d5a695e",
          "type": 1,
          "url": "https://zingnews.vn/"
        }
      ],
      "isComplete": true
    }
  ]
} 
*/

  String? id;
  int? statusCode;
  String? message;
  List<LessonSectionListResponseData?>? data;

  LessonSectionListResponse({
    this.id,
    this.statusCode,
    this.message,
    this.data,
  });
  LessonSectionListResponse.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toString();
    statusCode = json["statusCode"]?.toInt();
    message = json["message"]?.toString();
    if (json["data"] != null) {
      final v = json["data"];
      final arr0 = <LessonSectionListResponseData>[];
      v.forEach((v) {
        arr0.add(LessonSectionListResponseData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["statusCode"] = statusCode;
    data["message"] = message;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["data"] = arr0;
    }
    return data;
  }
}
