import 'package:medical/src/modal/base/images.dart';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///

class ListRoadmapResponseDataItemsExerciseMovements {
/*
{
  "id": "16bf8f5d-006a-4fba-50fc-08d99dee6b39",
  "code": "rtx3090",
  "coverId": "487d0d65-bac4-44ef-6946-08d99def6681",
  "roadmapId": "07491c70-28bf-42bf-731c-08d9986eb25e",
  "name": "rtx3090",
  "description": "rtx3090",
  "isFree": false,
  "practiceTime": 55,
  "videoUrl": "String",
  "day": 9,
  "image": {
    "id": "487d0d65-bac4-44ef-6946-08d99def6681",
    "url": "http://diab-api-dev.savvycom.vn/App/Image/487d0d65-bac4-44ef-6946-08d99def6681?expires=1636083505&signature=bd3c4b3f9043544c71e16560a07b69953efb685b6efe639f886e88278d391d31"
  },
  "sections": [
    "String"
  ],
  "reviewSummary": 10
} 
*/

  String? id;
  String? code;
  String? coverId;
  String? roadmapId;
  String? name;
  String? description;
  bool? isFree;
  int? practiceTime;
  String? videoUrl;
  int? day;
  ImagesModel? image;
  List<String?>? sections;
  int? reviewSummary;

  ListRoadmapResponseDataItemsExerciseMovements({
    this.id,
    this.code,
    this.coverId,
    this.roadmapId,
    this.name,
    this.description,
    this.isFree,
    this.practiceTime,
    this.videoUrl,
    this.day,
    this.image,
    this.sections,
    this.reviewSummary,
  });
  ListRoadmapResponseDataItemsExerciseMovements.fromJson(
      Map<String, dynamic> json) {
    id = json['id']?.toString();
    code = json['code']?.toString();
    coverId = json['coverId']?.toString();
    roadmapId = json['roadmapId']?.toString();
    name = json['name']?.toString();
    description = json['description']?.toString();
    isFree = json['isFree'];
    practiceTime = json['practiceTime']?.toInt();
    videoUrl = json['videoUrl']?.toString();
    day = json['day']?.toInt();
    image =
        (json['image'] != null) ? ImagesModel.fromJson(json['image']) : null;
    if (json['sections'] != null) {
      final v = json['sections'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      sections = arr0;
    }
    reviewSummary = json['reviewSummary']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['code'] = code;
    data['coverId'] = coverId;
    data['roadmapId'] = roadmapId;
    data['name'] = name;
    data['description'] = description;
    data['isFree'] = isFree;
    data['practiceTime'] = practiceTime;
    data['videoUrl'] = videoUrl;
    data['day'] = day;
    if (image != null) {
      data['image'] = image!.toJson();
    }
    if (sections != null) {
      final v = sections;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['sections'] = arr0;
    }
    data['reviewSummary'] = reviewSummary;
    return data;
  }
}

class ListRoadmapResponseDataItemsImage {
/*
{
  "id": "002a1a72-80a8-4fa4-54fd-08d93079d098",
  "url": "http://diab-api-dev.savvycom.vn/App/Image/002a1a72-80a8-4fa4-54fd-08d93079d098?expires=1636083505&signature=2b1bc817f8c6c243e61986e69e78eea88c545ef04dc3db0a4e0e37f0d3f36655"
} 
*/

  String? id;
  String? url;

  ListRoadmapResponseDataItemsImage({
    this.id,
    this.url,
  });
  ListRoadmapResponseDataItemsImage.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    url = json['url']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['url'] = url;
    return data;
  }
}

class ListRoadmapResponseDataItems {
/*
{
  "id": "07491c70-28bf-42bf-731c-08d9986eb25e",
  "code": "roadmap2",
  "coverId": "002a1a72-80a8-4fa4-54fd-08d93079d098",
  "name": "L? trình v?n d?ng s? 2",
  "day": 30,
  "openDay": 7,
  "status": 1,
  "description": "mô t?",
  "exerciseIntensitiesId": "3f29e372-1179-477e-b183-33356a28ece5",
  "image": {
    "id": "002a1a72-80a8-4fa4-54fd-08d93079d098",
    "url": "http://diab-api-dev.savvycom.vn/App/Image/002a1a72-80a8-4fa4-54fd-08d93079d098?expires=1636083505&signature=2b1bc817f8c6c243e61986e69e78eea88c545ef04dc3db0a4e0e37f0d3f36655"
  },
  "exerciseMovements": [
    {
      "id": "16bf8f5d-006a-4fba-50fc-08d99dee6b39",
      "code": "rtx3090",
      "coverId": "487d0d65-bac4-44ef-6946-08d99def6681",
      "roadmapId": "07491c70-28bf-42bf-731c-08d9986eb25e",
      "name": "rtx3090",
      "description": "rtx3090",
      "isFree": false,
      "practiceTime": 55,
      "videoUrl": "String",
      "day": 9,
      "image": {
        "id": "487d0d65-bac4-44ef-6946-08d99def6681",
        "url": "http://diab-api-dev.savvycom.vn/App/Image/487d0d65-bac4-44ef-6946-08d99def6681?expires=1636083505&signature=bd3c4b3f9043544c71e16560a07b69953efb685b6efe639f886e88278d391d31"
      },
      "sections": [
        "String"
      ],
      "reviewSummary": 10
    }
  ],
  "selectTags": [
    "String"
  ],
  "exerciseIntensities": [
    "String"
  ],
  "tags": [
    "String"
  ]
} 
*/

  String? id;
  String? code;
  String? coverId;
  String? name;
  int? day;
  int? openDay;
  int? status;
  String? description;
  String? exerciseIntensitiesId;
  ListRoadmapResponseDataItemsImage? image;
  List<ListRoadmapResponseDataItemsExerciseMovements?>? exerciseMovements;
  List<String?>? selectTags;
  List<String?>? exerciseIntensities;
  List<String?>? tags;

  ListRoadmapResponseDataItems({
    this.id,
    this.code,
    this.coverId,
    this.name,
    this.day,
    this.openDay,
    this.status,
    this.description,
    this.exerciseIntensitiesId,
    this.image,
    this.exerciseMovements,
    this.selectTags,
    this.exerciseIntensities,
    this.tags,
  });
  ListRoadmapResponseDataItems.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    code = json['code']?.toString();
    coverId = json['coverId']?.toString();
    name = json['name']?.toString();
    day = json['day']?.toInt();
    openDay = json['openDay']?.toInt();
    status = json['status']?.toInt();
    description = json['description']?.toString();
    exerciseIntensitiesId = json['exerciseIntensitiesId']?.toString();
    image = (json['image'] != null)
        ? ListRoadmapResponseDataItemsImage.fromJson(json['image'])
        : null;
    if (json['exerciseMovements'] != null) {
      final v = json['exerciseMovements'];
      final arr0 = <ListRoadmapResponseDataItemsExerciseMovements>[];
      v.forEach((v) {
        arr0.add(ListRoadmapResponseDataItemsExerciseMovements.fromJson(v));
      });
      exerciseMovements = arr0;
    }
    if (json['selectTags'] != null) {
      final v = json['selectTags'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      selectTags = arr0;
    }
    if (json['exerciseIntensities'] != null) {
      final v = json['exerciseIntensities'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      exerciseIntensities = arr0;
    }
    if (json['tags'] != null) {
      final v = json['tags'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      tags = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['code'] = code;
    data['coverId'] = coverId;
    data['name'] = name;
    data['day'] = day;
    data['openDay'] = openDay;
    data['status'] = status;
    data['description'] = description;
    data['exerciseIntensitiesId'] = exerciseIntensitiesId;
    if (image != null) {
      data['image'] = image!.toJson();
    }
    if (exerciseMovements != null) {
      final v = exerciseMovements;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['exerciseMovements'] = arr0;
    }
    if (selectTags != null) {
      final v = selectTags;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['selectTags'] = arr0;
    }
    if (exerciseIntensities != null) {
      final v = exerciseIntensities;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['exerciseIntensities'] = arr0;
    }
    if (tags != null) {
      final v = tags;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['tags'] = arr0;
    }
    return data;
  }
}

class ListRoadmapResponseData {
/*
{
  "total": 10,
  "page": 1,
  "size": 10,
  "items": [
    {
      "id": "07491c70-28bf-42bf-731c-08d9986eb25e",
      "code": "roadmap2",
      "coverId": "002a1a72-80a8-4fa4-54fd-08d93079d098",
      "name": "L? trình v?n d?ng s? 2",
      "day": 30,
      "openDay": 7,
      "status": 1,
      "description": "mô t?",
      "exerciseIntensitiesId": "3f29e372-1179-477e-b183-33356a28ece5",
      "image": {
        "id": "002a1a72-80a8-4fa4-54fd-08d93079d098",
        "url": "http://diab-api-dev.savvycom.vn/App/Image/002a1a72-80a8-4fa4-54fd-08d93079d098?expires=1636083505&signature=2b1bc817f8c6c243e61986e69e78eea88c545ef04dc3db0a4e0e37f0d3f36655"
      },
      "exerciseMovements": [
        {
          "id": "16bf8f5d-006a-4fba-50fc-08d99dee6b39",
          "code": "rtx3090",
          "coverId": "487d0d65-bac4-44ef-6946-08d99def6681",
          "roadmapId": "07491c70-28bf-42bf-731c-08d9986eb25e",
          "name": "rtx3090",
          "description": "rtx3090",
          "isFree": false,
          "practiceTime": 55,
          "videoUrl": "String",
          "day": 9,
          "image": {
            "id": "487d0d65-bac4-44ef-6946-08d99def6681",
            "url": "http://diab-api-dev.savvycom.vn/App/Image/487d0d65-bac4-44ef-6946-08d99def6681?expires=1636083505&signature=bd3c4b3f9043544c71e16560a07b69953efb685b6efe639f886e88278d391d31"
          },
          "sections": [
            "String"
          ],
          "reviewSummary": 10
        }
      ],
      "selectTags": [
        "String"
      ],
      "exerciseIntensities": [
        "String"
      ],
      "tags": [
        "String"
      ]
    }
  ]
} 
*/

  int? total;
  int? page;
  int? size;
  List<ListRoadmapResponseDataItems?>? items;

  ListRoadmapResponseData({
    this.total,
    this.page,
    this.size,
    this.items,
  });
  ListRoadmapResponseData.fromJson(Map<String, dynamic> json) {
    total = json['total']?.toInt();
    page = json['page']?.toInt();
    size = json['size']?.toInt();
    if (json['items'] != null) {
      final v = json['items'];
      final arr0 = <ListRoadmapResponseDataItems>[];
      v.forEach((v) {
        arr0.add(ListRoadmapResponseDataItems.fromJson(v));
      });
      items = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['total'] = total;
    data['page'] = page;
    data['size'] = size;
    if (items != null) {
      final v = items;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['items'] = arr0;
    }
    return data;
  }
}

class ListRoadmapResponseMeta {
/*
{
  "success": true
} 
*/

  bool? success;

  ListRoadmapResponseMeta({
    this.success,
  });
  ListRoadmapResponseMeta.fromJson(Map<String, dynamic> json) {
    success = json['success'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    return data;
  }
}

class ListRoadmapResponse {
/*
{
  "meta": {
    "success": true
  },
  "data": {
    "total": 10,
    "page": 1,
    "size": 10,
    "items": [
      {
        "id": "07491c70-28bf-42bf-731c-08d9986eb25e",
        "code": "roadmap2",
        "coverId": "002a1a72-80a8-4fa4-54fd-08d93079d098",
        "name": "L? trình v?n d?ng s? 2",
        "day": 30,
        "openDay": 7,
        "status": 1,
        "description": "mô t?",
        "exerciseIntensitiesId": "3f29e372-1179-477e-b183-33356a28ece5",
        "image": {
          "id": "002a1a72-80a8-4fa4-54fd-08d93079d098",
          "url": "http://diab-api-dev.savvycom.vnC/App/Image/002a1a72-80a8-4fa4-54fd-08d93079d098?expires=1636083505&signature=2b1bc817f8c6c243e61986e69e78eea88c545ef04dc3db0a4e0e37f0d3f36655"
        },
        "exerciseMovements": [
          {
            "id": "16bf8f5d-006a-4fba-50fc-08d99dee6b39",
            "code": "rtx3090",
            "coverId": "487d0d65-bac4-44ef-6946-08d99def6681",
            "roadmapId": "07491c70-28bf-42bf-731c-08d9986eb25e",
            "name": "rtx3090",
            "description": "rtx3090",
            "isFree": false,
            "practiceTime": 55,
            "videoUrl": "String",
            "day": 9,
            "image": {
              "id": "487d0d65-bac4-44ef-6946-08d99def6681",
              "url": "http://diab-api-dev.savvycom.vn/App/Image/487d0d65-bac4-44ef-6946-08d99def6681?expires=1636083505&signature=bd3c4b3f9043544c71e16560a07b69953efb685b6efe639f886e88278d391d31"
            },
            "sections": [
              "String"
            ],
            "reviewSummary": 10
          }
        ],
        "selectTags": [
          "String"
        ],
        "exerciseIntensities": [
          "String"
        ],
        "tags": [
          "String"
        ]
      }
    ]
  }
} 
*/

  ListRoadmapResponseMeta? meta;
  ListRoadmapResponseData? data;

  ListRoadmapResponse({
    this.meta,
    this.data,
  });
  ListRoadmapResponse.fromJson(Map<String, dynamic> json) {
    meta = (json['meta'] != null)
        ? ListRoadmapResponseMeta.fromJson(json['meta'])
        : null;
    data = (json['data'] != null)
        ? ListRoadmapResponseData.fromJson(json['data'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (meta != null) {
      data['meta'] = meta!.toJson();
    }
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
