import 'dart:ui';

import 'package:medical/res/R.dart';
import 'package:medical/src/modal/base/images.dart';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ListRoadmapResponseDataItemsTags {
/*
{
  "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "name": "string",
  "type": 1
} 
*/

  String? id;
  String? name;
  int? type;

  ListRoadmapResponseDataItemsTags({
    this.id,
    this.name,
    this.type,
  });
  ListRoadmapResponseDataItemsTags.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    name = json['name']?.toString();
    type = json['type']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['type'] = type;
    return data;
  }
}

class ListRoadmapResponseDataItemsExerciseIntensities {
/*
{
  "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "name": "string"
} 
*/

  String? id;
  String? name;

  ListRoadmapResponseDataItemsExerciseIntensities({
    this.id,
    this.name,
  });
  ListRoadmapResponseDataItemsExerciseIntensities.fromJson(
      Map<String, dynamic> json) {
    id = json['id']?.toString();
    name = json['name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    return data;
  }
}

class ListRoadmapResponseDataItemsExerciseIntensity {
/*
{
  "id": "c13b3b3d-4b25-41a6-bb0a-54770a1f6123",
  "name": "Cường độ cao"
} 
*/

  String? id;
  String? name;

  ListRoadmapResponseDataItemsExerciseIntensity({
    this.id,
    this.name,
  });

  Color get color {
    if (id == '3f29e372-1179-477e-b183-33356a28ece5') return R.color.green;
    if (id == 'c13b3b3d-4b25-41a6-bb0a-54770a1f6123')
      return R.color.attentionText;
    if (id == 'd79b986e-82cf-48ff-aac2-d77cc0c77012') return R.color.orange_1;
    return R.color.textDark;
  }

  ListRoadmapResponseDataItemsExerciseIntensity.fromJson(
      Map<String, dynamic> json) {
    id = json['id']?.toString();
    name = json['name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    return data;
  }
}

class ListRoadmapResponseDataItemsSelectTags {
/*
{
  "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "name": "string",
  "type": 1
} 
*/

  String? id;
  String? name;
  int? type;

  ListRoadmapResponseDataItemsSelectTags({
    this.id,
    this.name,
    this.type,
  });
  ListRoadmapResponseDataItemsSelectTags.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    name = json['name']?.toString();
    type = json['type']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['type'] = type;
    return data;
  }
}

class ListRoadmapResponseDataItemsExerciseMovementsReviewSummary {
/*
{
  "tooLightExercisePercent": 0,
  "tooLightExerciseCount": 0,
  "lightExercisePercent": 0,
  "lightExerciseCount": 0,
  "moderateExercisePercent": 0,
  "moderateExerciseCount": 0,
  "heavyExercisePercent": 0,
  "heavyExerciseCount": 0,
  "tooHeavyExercisePercent": 0,
  "tooHeavyExerciseCount": 0
} 
*/

  int? tooLightExercisePercent;
  int? tooLightExerciseCount;
  int? lightExercisePercent;
  int? lightExerciseCount;
  int? moderateExercisePercent;
  int? moderateExerciseCount;
  int? heavyExercisePercent;
  int? heavyExerciseCount;
  int? tooHeavyExercisePercent;
  int? tooHeavyExerciseCount;

  ListRoadmapResponseDataItemsExerciseMovementsReviewSummary({
    this.tooLightExercisePercent,
    this.tooLightExerciseCount,
    this.lightExercisePercent,
    this.lightExerciseCount,
    this.moderateExercisePercent,
    this.moderateExerciseCount,
    this.heavyExercisePercent,
    this.heavyExerciseCount,
    this.tooHeavyExercisePercent,
    this.tooHeavyExerciseCount,
  });
  ListRoadmapResponseDataItemsExerciseMovementsReviewSummary.fromJson(
      Map<String, dynamic> json) {
    tooLightExercisePercent = json['tooLightExercisePercent']?.toInt();
    tooLightExerciseCount = json['tooLightExerciseCount']?.toInt();
    lightExercisePercent = json['lightExercisePercent']?.toInt();
    lightExerciseCount = json['lightExerciseCount']?.toInt();
    moderateExercisePercent = json['moderateExercisePercent']?.toInt();
    moderateExerciseCount = json['moderateExerciseCount']?.toInt();
    heavyExercisePercent = json['heavyExercisePercent']?.toInt();
    heavyExerciseCount = json['heavyExerciseCount']?.toInt();
    tooHeavyExercisePercent = json['tooHeavyExercisePercent']?.toInt();
    tooHeavyExerciseCount = json['tooHeavyExerciseCount']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['tooLightExercisePercent'] = tooLightExercisePercent;
    data['tooLightExerciseCount'] = tooLightExerciseCount;
    data['lightExercisePercent'] = lightExercisePercent;
    data['lightExerciseCount'] = lightExerciseCount;
    data['moderateExercisePercent'] = moderateExercisePercent;
    data['moderateExerciseCount'] = moderateExerciseCount;
    data['heavyExercisePercent'] = heavyExercisePercent;
    data['heavyExerciseCount'] = heavyExerciseCount;
    data['tooHeavyExercisePercent'] = tooHeavyExercisePercent;
    data['tooHeavyExerciseCount'] = tooHeavyExerciseCount;
    return data;
  }
}

class ListRoadmapResponseDataItemsExerciseMovementsSections {
/*
{
  "id": "37cb824c-569a-4ac7-a296-08d9a326fbbc",
  "code": "lessonwithsections",
  "name": "123",
  "exerciseCategoryId": "795de0cb-8747-42ac-b26e-88e273b3c634",
  "replayTime": 2,
  "videoUrl": "123"
} 
*/

  String? id;
  String? code;
  String? name;
  String? exerciseCategoryId;
  int? replayTime;
  String? videoUrl;

  ListRoadmapResponseDataItemsExerciseMovementsSections({
    this.id,
    this.code,
    this.name,
    this.exerciseCategoryId,
    this.replayTime,
    this.videoUrl,
  });
  ListRoadmapResponseDataItemsExerciseMovementsSections.fromJson(
      Map<String, dynamic> json) {
    id = json['id']?.toString();
    code = json['code']?.toString();
    name = json['name']?.toString();
    exerciseCategoryId = json['exerciseCategoryId']?.toString();
    replayTime = json['replayTime']?.toInt();
    videoUrl = json['videoUrl']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['code'] = code;
    data['name'] = name;
    data['exerciseCategoryId'] = exerciseCategoryId;
    data['replayTime'] = replayTime;
    data['videoUrl'] = videoUrl;
    return data;
  }
}

class ListRoadmapResponseDataItemsExerciseMovements {
/*
{
  "id": "4dc8c48a-cb93-4d43-b94d-08d9a3261ef8",
  "code": "lessonwithsections213123",
  "coverId": "70e23a09-22ce-48c1-87ab-08d9a29b0a24",
  "roadmapId": "07491c70-28bf-42bf-731c-08d9986eb25e",
  "name": "lessonwithsections213123",
  "description": "lessonwithsections213123",
  "isFree": true,
  "practiceTime": 111,
  "videoUrl": "lessonwithsections213123",
  "day": 16,
  "image": {
    "id": "70e23a09-22ce-48c1-87ab-08d9a29b0a24",
    "url": "http://diab-api-dev.savvycom.vn/App/Image/70e23a09-22ce-48c1-87ab-08d9a29b0a24?expires=1637037848&signature=1d0f5a3ca83bed6be44ece172a1d85a4490bdd2a0cbd37b81daf2463f6768467"
  },
  "sections": [
    {
      "id": "37cb824c-569a-4ac7-a296-08d9a326fbbc",
      "code": "lessonwithsections",
      "name": "123",
      "exerciseCategoryId": "795de0cb-8747-42ac-b26e-88e273b3c634",
      "replayTime": 2,
      "videoUrl": "123"
    }
  ],
  "reviewSummary": {
    "tooLightExercisePercent": 0,
    "tooLightExerciseCount": 0,
    "lightExercisePercent": 0,
    "lightExerciseCount": 0,
    "moderateExercisePercent": 0,
    "moderateExerciseCount": 0,
    "heavyExercisePercent": 0,
    "heavyExerciseCount": 0,
    "tooHeavyExercisePercent": 0,
    "tooHeavyExerciseCount": 0
  }
} 
*/

  String? id;
  String? code;
  String? coverId;
  String? roadmapId;
  String? name;
  String? description;
  bool? isFree;
  int? practiceTime;
  String? videoUrl;
  int? day;
  ImagesModel? image;
  List<ListRoadmapResponseDataItemsExerciseMovementsSections?>? sections;
  ListRoadmapResponseDataItemsExerciseMovementsReviewSummary? reviewSummary;

  ListRoadmapResponseDataItemsExerciseMovements({
    this.id,
    this.code,
    this.coverId,
    this.roadmapId,
    this.name,
    this.description,
    this.isFree,
    this.practiceTime,
    this.videoUrl,
    this.day,
    this.image,
    this.sections,
    this.reviewSummary,
  });
  ListRoadmapResponseDataItemsExerciseMovements.fromJson(
      Map<String, dynamic> json) {
    id = json['id']?.toString();
    code = json['code']?.toString();
    coverId = json['coverId']?.toString();
    roadmapId = json['roadmapId']?.toString();
    name = json['name']?.toString();
    description = json['description']?.toString();
    isFree = json['isFree'];
    practiceTime = json['practiceTime']?.toInt();
    videoUrl = json['videoUrl']?.toString();
    day = json['day']?.toInt();
    image =
        (json['image'] != null) ? ImagesModel.fromJson(json['image']) : null;
    if (json['sections'] != null) {
      final v = json['sections'];
      final arr0 = <ListRoadmapResponseDataItemsExerciseMovementsSections>[];
      v.forEach((v) {
        arr0.add(
            ListRoadmapResponseDataItemsExerciseMovementsSections.fromJson(v));
      });
      sections = arr0;
    }
    reviewSummary = (json['reviewSummary'] != null)
        ? ListRoadmapResponseDataItemsExerciseMovementsReviewSummary.fromJson(
            json['reviewSummary'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['code'] = code;
    data['coverId'] = coverId;
    data['roadmapId'] = roadmapId;
    data['name'] = name;
    data['description'] = description;
    data['isFree'] = isFree;
    data['practiceTime'] = practiceTime;
    data['videoUrl'] = videoUrl;
    data['day'] = day;
    if (image != null) {
      data['image'] = image!.toJson();
    }
    if (sections != null) {
      final v = sections;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['sections'] = arr0;
    }
    if (reviewSummary != null) {
      data['reviewSummary'] = reviewSummary!.toJson();
    }
    return data;
  }
}

class ListRoadmapResponseDataItemsImage {
/*
{
  "id": "aac6f859-17af-4eea-86a1-08d9a02fd87a",
  "url": "http://diab-api-dev.savvycom.vn/App/Image/aac6f859-17af-4eea-86a1-08d9a02fd87a?expires=1637037848&signature=ad9fb21c461d56d2bfe90510b2799856d53ac3e96aeaff1c5f4c34f3a17cfacd"
} 
*/

  String? id;
  String? url;

  ListRoadmapResponseDataItemsImage({
    this.id,
    this.url,
  });
  ListRoadmapResponseDataItemsImage.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    url = json['url']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['url'] = url;
    return data;
  }
}

class ListRoadmapResponseDataItems {
/*
{
  "id": "07491c70-28bf-42bf-731c-08d9986eb25e",
  "code": "roadmap2",
  "coverId": "aac6f859-17af-4eea-86a1-08d9a02fd87a",
  "name": "L? trình v?n d?ng s? 2",
  "day": 23,
  "openDay": 7,
  "status": 1,
  "description": "mô t?",
  "exerciseIntensitiesId": "c13b3b3d-4b25-41a6-bb0a-54770a1f6123",
  "image": {
    "id": "aac6f859-17af-4eea-86a1-08d9a02fd87a",
    "url": "http://diab-api-dev.savvycom.vn/App/Image/aac6f859-17af-4eea-86a1-08d9a02fd87a?expires=1637037848&signature=ad9fb21c461d56d2bfe90510b2799856d53ac3e96aeaff1c5f4c34f3a17cfacd"
  },
  "exerciseMovements": [
    {
      "id": "4dc8c48a-cb93-4d43-b94d-08d9a3261ef8",
      "code": "lessonwithsections213123",
      "coverId": "70e23a09-22ce-48c1-87ab-08d9a29b0a24",
      "roadmapId": "07491c70-28bf-42bf-731c-08d9986eb25e",
      "name": "lessonwithsections213123",
      "description": "lessonwithsections213123",
      "isFree": true,
      "practiceTime": 111,
      "videoUrl": "lessonwithsections213123",
      "day": 16,
      "image": {
        "id": "70e23a09-22ce-48c1-87ab-08d9a29b0a24",
        "url": "http://diab-api-dev.savvycom.vn/App/Image/70e23a09-22ce-48c1-87ab-08d9a29b0a24?expires=1637037848&signature=1d0f5a3ca83bed6be44ece172a1d85a4490bdd2a0cbd37b81daf2463f6768467"
      },
      "sections": [
        {
          "id": "37cb824c-569a-4ac7-a296-08d9a326fbbc",
          "code": "lessonwithsections",
          "name": "123",
          "exerciseCategoryId": "795de0cb-8747-42ac-b26e-88e273b3c634",
          "replayTime": 2,
          "videoUrl": "123"
        }
      ],
      "reviewSummary": {
        "tooLightExercisePercent": 0,
        "tooLightExerciseCount": 0,
        "lightExercisePercent": 0,
        "lightExerciseCount": 0,
        "moderateExercisePercent": 0,
        "moderateExerciseCount": 0,
        "heavyExercisePercent": 0,
        "heavyExerciseCount": 0,
        "tooHeavyExercisePercent": 0,
        "tooHeavyExerciseCount": 0
      }
    }
  ],
  "selectTags": [
    {
      "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "name": "string",
      "type": 1
    }
  ],
  "exerciseIntensity": {
    "id": "c13b3b3d-4b25-41a6-bb0a-54770a1f6123",
    "name": "Cường độ cao"
  },
  "exerciseIntensities": [
    {
      "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "name": "string"
    }
  ],
  "tags": [
    {
      "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "name": "string",
      "type": 1
    }
  ],
  "joined": true,
  "enoughExercise": true
} 
*/

  String? id;
  String? code;
  String? coverId;
  String? name;
  int? day;
  int? openDay;
  int? status;
  String? description;
  String? exerciseIntensitiesId;
  ListRoadmapResponseDataItemsImage? image;
  List<ListRoadmapResponseDataItemsExerciseMovements?>? exerciseMovements;
  List<ListRoadmapResponseDataItemsSelectTags?>? selectTags;
  ListRoadmapResponseDataItemsExerciseIntensity? exerciseIntensity;
  List<ListRoadmapResponseDataItemsExerciseIntensities?>? exerciseIntensities;
  List<ListRoadmapResponseDataItemsTags?>? tags;
  bool? joined;
  bool? enoughExercise;

  ListRoadmapResponseDataItems({
    this.id,
    this.code,
    this.coverId,
    this.name,
    this.day,
    this.openDay,
    this.status,
    this.description,
    this.exerciseIntensitiesId,
    this.image,
    this.exerciseMovements,
    this.selectTags,
    this.exerciseIntensity,
    this.exerciseIntensities,
    this.tags,
    this.joined,
    this.enoughExercise,
  });
  ListRoadmapResponseDataItems.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    code = json['code']?.toString();
    coverId = json['coverId']?.toString();
    name = json['name']?.toString();
    day = json['day']?.toInt();
    openDay = json['openDay']?.toInt();
    status = json['status']?.toInt();
    description = json['description']?.toString();
    exerciseIntensitiesId = json['exerciseIntensitiesId']?.toString();
    image = (json['image'] != null)
        ? ListRoadmapResponseDataItemsImage.fromJson(json['image'])
        : null;
    if (json['exerciseMovements'] != null) {
      final v = json['exerciseMovements'];
      final arr0 = <ListRoadmapResponseDataItemsExerciseMovements>[];
      v.forEach((v) {
        arr0.add(ListRoadmapResponseDataItemsExerciseMovements.fromJson(v));
      });
      exerciseMovements = arr0;
    }
    if (json['selectTags'] != null) {
      final v = json['selectTags'];
      final arr0 = <ListRoadmapResponseDataItemsSelectTags>[];
      v.forEach((v) {
        arr0.add(ListRoadmapResponseDataItemsSelectTags.fromJson(v));
      });
      selectTags = arr0;
    }
    exerciseIntensity = (json['exerciseIntensity'] != null)
        ? ListRoadmapResponseDataItemsExerciseIntensity.fromJson(
            json['exerciseIntensity'])
        : null;
    if (json['exerciseIntensities'] != null) {
      final v = json['exerciseIntensities'];
      final arr0 = <ListRoadmapResponseDataItemsExerciseIntensities>[];
      v.forEach((v) {
        arr0.add(ListRoadmapResponseDataItemsExerciseIntensities.fromJson(v));
      });
      exerciseIntensities = arr0;
    }
    if (json['tags'] != null) {
      final v = json['tags'];
      final arr0 = <ListRoadmapResponseDataItemsTags>[];
      v.forEach((v) {
        arr0.add(ListRoadmapResponseDataItemsTags.fromJson(v));
      });
      tags = arr0;
    }
    joined = json['joined'];
    enoughExercise = json['enoughExercise'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['code'] = code;
    data['coverId'] = coverId;
    data['name'] = name;
    data['day'] = day;
    data['openDay'] = openDay;
    data['status'] = status;
    data['description'] = description;
    data['exerciseIntensitiesId'] = exerciseIntensitiesId;
    if (image != null) {
      data['image'] = image!.toJson();
    }
    if (exerciseMovements != null) {
      final v = exerciseMovements;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['exerciseMovements'] = arr0;
    }
    if (selectTags != null) {
      final v = selectTags;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['selectTags'] = arr0;
    }
    if (exerciseIntensity != null) {
      data['exerciseIntensity'] = exerciseIntensity!.toJson();
    }
    if (exerciseIntensities != null) {
      final v = exerciseIntensities;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['exerciseIntensities'] = arr0;
    }
    if (tags != null) {
      final v = tags;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['tags'] = arr0;
    }
    data['joined'] = joined;
    data['enoughExercise'] = enoughExercise;
    return data;
  }
}

class ListRoadmapResponseData {
/*
{
  "total": 26,
  "page": 1,
  "size": 1,
  "items": [
    {
      "id": "07491c70-28bf-42bf-731c-08d9986eb25e",
      "code": "roadmap2",
      "coverId": "aac6f859-17af-4eea-86a1-08d9a02fd87a",
      "name": "L? trình v?n d?ng s? 2",
      "day": 23,
      "openDay": 7,
      "status": 1,
      "description": "mô t?",
      "exerciseIntensitiesId": "c13b3b3d-4b25-41a6-bb0a-54770a1f6123",
      "image": {
        "id": "aac6f859-17af-4eea-86a1-08d9a02fd87a",
        "url": "http://diab-api-dev.savvycom.vn/App/Image/aac6f859-17af-4eea-86a1-08d9a02fd87a?expires=1637037848&signature=ad9fb21c461d56d2bfe90510b2799856d53ac3e96aeaff1c5f4c34f3a17cfacd"
      },
      "exerciseMovements": [
        {
          "id": "4dc8c48a-cb93-4d43-b94d-08d9a3261ef8",
          "code": "lessonwithsections213123",
          "coverId": "70e23a09-22ce-48c1-87ab-08d9a29b0a24",
          "roadmapId": "07491c70-28bf-42bf-731c-08d9986eb25e",
          "name": "lessonwithsections213123",
          "description": "lessonwithsections213123",
          "isFree": true,
          "practiceTime": 111,
          "videoUrl": "lessonwithsections213123",
          "day": 16,
          "image": {
            "id": "70e23a09-22ce-48c1-87ab-08d9a29b0a24",
            "url": "http://diab-api-dev.savvycom.vn/App/Image/70e23a09-22ce-48c1-87ab-08d9a29b0a24?expires=1637037848&signature=1d0f5a3ca83bed6be44ece172a1d85a4490bdd2a0cbd37b81daf2463f6768467"
          },
          "sections": [
            {
              "id": "37cb824c-569a-4ac7-a296-08d9a326fbbc",
              "code": "lessonwithsections",
              "name": "123",
              "exerciseCategoryId": "795de0cb-8747-42ac-b26e-88e273b3c634",
              "replayTime": 2,
              "videoUrl": "123"
            }
          ],
          "reviewSummary": {
            "tooLightExercisePercent": 0,
            "tooLightExerciseCount": 0,
            "lightExercisePercent": 0,
            "lightExerciseCount": 0,
            "moderateExercisePercent": 0,
            "moderateExerciseCount": 0,
            "heavyExercisePercent": 0,
            "heavyExerciseCount": 0,
            "tooHeavyExercisePercent": 0,
            "tooHeavyExerciseCount": 0
          }
        }
      ],
      "selectTags": [
        {
          "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
          "name": "string",
          "type": 1
        }
      ],
      "exerciseIntensity": {
        "id": "c13b3b3d-4b25-41a6-bb0a-54770a1f6123",
        "name": "Cường độ cao"
      },
      "exerciseIntensities": [
        {
          "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
          "name": "string"
        }
      ],
      "tags": [
        {
          "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
          "name": "string",
          "type": 1
        }
      ],
      "joined": true,
      "enoughExercise": true
    }
  ]
} 
*/

  int? total;
  int? page;
  int? size;
  List<ListRoadmapResponseDataItems?>? items;

  ListRoadmapResponseData({
    this.total,
    this.page,
    this.size,
    this.items,
  });
  ListRoadmapResponseData.fromJson(Map<String, dynamic> json) {
    total = json['total']?.toInt();
    page = json['page']?.toInt();
    size = json['size']?.toInt();
    if (json['items'] != null) {
      final v = json['items'];
      final arr0 = <ListRoadmapResponseDataItems>[];
      v.forEach((v) {
        arr0.add(ListRoadmapResponseDataItems.fromJson(v));
      });
      items = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['total'] = total;
    data['page'] = page;
    data['size'] = size;
    if (items != null) {
      final v = items;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['items'] = arr0;
    }
    return data;
  }
}

class ListRoadmapResponseMeta {
/*
{
  "success": true
} 
*/

  bool? success;

  ListRoadmapResponseMeta({
    this.success,
  });
  ListRoadmapResponseMeta.fromJson(Map<String, dynamic> json) {
    success = json['success'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    return data;
  }
}

class ListRoadmapResponse {
/*
{
  "meta": {
    "success": true
  },
  "data": {
    "total": 26,
    "page": 1,
    "size": 1,
    "items": [
      {
        "id": "07491c70-28bf-42bf-731c-08d9986eb25e",
        "code": "roadmap2",
        "coverId": "aac6f859-17af-4eea-86a1-08d9a02fd87a",
        "name": "L? trình v?n d?ng s? 2",
        "day": 23,
        "openDay": 7,
        "status": 1,
        "description": "mô t?",
        "exerciseIntensitiesId": "c13b3b3d-4b25-41a6-bb0a-54770a1f6123",
        "image": {
          "id": "aac6f859-17af-4eea-86a1-08d9a02fd87a",
          "url": "http://diab-api-dev.savvycom.vn/App/Image/aac6f859-17af-4eea-86a1-08d9a02fd87a?expires=1637037848&signature=ad9fb21c461d56d2bfe90510b2799856d53ac3e96aeaff1c5f4c34f3a17cfacd"
        },
        "exerciseMovements": [
          {
            "id": "4dc8c48a-cb93-4d43-b94d-08d9a3261ef8",
            "code": "lessonwithsections213123",
            "coverId": "70e23a09-22ce-48c1-87ab-08d9a29b0a24",
            "roadmapId": "07491c70-28bf-42bf-731c-08d9986eb25e",
            "name": "lessonwithsections213123",
            "description": "lessonwithsections213123",
            "isFree": true,
            "practiceTime": 111,
            "videoUrl": "lessonwithsections213123",
            "day": 16,
            "image": {
              "id": "70e23a09-22ce-48c1-87ab-08d9a29b0a24",
              "url": "http://diab-api-dev.savvycom.vn/App/Image/70e23a09-22ce-48c1-87ab-08d9a29b0a24?expires=1637037848&signature=1d0f5a3ca83bed6be44ece172a1d85a4490bdd2a0cbd37b81daf2463f6768467"
            },
            "sections": [
              {
                "id": "37cb824c-569a-4ac7-a296-08d9a326fbbc",
                "code": "lessonwithsections",
                "name": "123",
                "exerciseCategoryId": "795de0cb-8747-42ac-b26e-88e273b3c634",
                "replayTime": 2,
                "videoUrl": "123"
              }
            ],
            "reviewSummary": {
              "tooLightExercisePercent": 0,
              "tooLightExerciseCount": 0,
              "lightExercisePercent": 0,
              "lightExerciseCount": 0,
              "moderateExercisePercent": 0,
              "moderateExerciseCount": 0,
              "heavyExercisePercent": 0,
              "heavyExerciseCount": 0,
              "tooHeavyExercisePercent": 0,
              "tooHeavyExerciseCount": 0
            }
          }
        ],
        "selectTags": [
          {
            "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
            "name": "string",
            "type": 1
          }
        ],
        "exerciseIntensity": {
          "id": "c13b3b3d-4b25-41a6-bb0a-54770a1f6123",
          "name": "Cường độ cao"
        },
        "exerciseIntensities": [
          {
            "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
            "name": "string"
          }
        ],
        "tags": [
          {
            "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
            "name": "string",
            "type": 1
          }
        ],
        "joined": true,
        "enoughExercise": true
      }
    ]
  }
} 
*/

  ListRoadmapResponseMeta? meta;
  ListRoadmapResponseData? data;

  ListRoadmapResponse({
    this.meta,
    this.data,
  });
  ListRoadmapResponse.fromJson(Map<String, dynamic> json) {
    meta = (json['meta'] != null)
        ? ListRoadmapResponseMeta.fromJson(json['meta'])
        : null;
    data = (json['data'] != null)
        ? ListRoadmapResponseData.fromJson(json['data'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (meta != null) {
      data['meta'] = meta!.toJson();
    }
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
