import 'dart:ui';

import 'package:medical/res/R.dart';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ListRoadmapResponseDataItemsExerciseIntensity {
/*
{
  "id": "3f29e372-1179-477e-b183-33356a28ece5",
  "name": "Cường độ trung bình"
} 
*/

  String? id;
  String? name;

  ListRoadmapResponseDataItemsExerciseIntensity({
    this.id,
    this.name,
  });

  Color get color {
    if (id == '3f29e372-1179-477e-b183-33356a28ece5') return R.color.textDark;
    if (id == 'c13b3b3d-4b25-41a6-bb0a-54770a1f6123') return R.color.attentionText;
    if (id == 'd79b986e-82cf-48ff-aac2-d77cc0c77012') return R.color.orange_1;
    return R.color.black;
  }

  ListRoadmapResponseDataItemsExerciseIntensity.fromJson(
      Map<String, dynamic> json) {
    id = json['id']?.toString();
    name = json['name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    return data;
  }
}

class ListRoadmapResponseDataItemsSelectTags {
/*
{
  "id": "228f84bf-7490-4b32-d170-08d9a4f34a61",
  "name": "Lộ trình 19",
  "type": 2
} 
*/

  String? id;
  String? name;
  int? type;

  ListRoadmapResponseDataItemsSelectTags({
    this.id,
    this.name,
    this.type,
  });
  ListRoadmapResponseDataItemsSelectTags.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    name = json['name']?.toString();
    type = json['type']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['type'] = type;
    return data;
  }
}

class ListRoadmapResponseDataItemsImage {
/*
{
  "id": "1d5e3414-7708-428c-1faf-08d9a4f8ca49",
  "url": "http://diab-api-dev.savvycom.vn/App/Image/1d5e3414-7708-428c-1faf-08d9a4f8ca49?expires=1636904471&signature=0f6d3cc18c3f585ad7fa583d89ec8744f119787ba337c4e62ae12150490fba6d",
  "title": "wp3703420-iron-man-4k-wallpapers.jpg"
} 
*/

  String? id;
  String? url;
  String? title;

  ListRoadmapResponseDataItemsImage({
    this.id,
    this.url,
    this.title,
  });
  ListRoadmapResponseDataItemsImage.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    url = json['url']?.toString();
    title = json['title']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['url'] = url;
    data['title'] = title;
    return data;
  }
}

class ListRoadmapResponseDataItems {
/*
{
  "id": "8538590e-1b0b-42e0-02ac-08d9a4f8ca86",
  "code": "LT20",
  "coverId": "1d5e3414-7708-428c-1faf-08d9a4f8ca49",
  "name": "Lộ trình 20",
  "day": 1,
  "openDay": 0,
  "status": 2,
  "description": "123123",
  "exerciseIntensitiesId": "3f29e372-1179-477e-b183-33356a28ece5",
  "image": {
    "id": "1d5e3414-7708-428c-1faf-08d9a4f8ca49",
    "url": "http://diab-api-dev.savvycom.vn/App/Image/1d5e3414-7708-428c-1faf-08d9a4f8ca49?expires=1636904471&signature=0f6d3cc18c3f585ad7fa583d89ec8744f119787ba337c4e62ae12150490fba6d",
    "title": "wp3703420-iron-man-4k-wallpapers.jpg"
  },
  "selectTags": [
    {
      "id": "228f84bf-7490-4b32-d170-08d9a4f34a61",
      "name": "Lộ trình 19",
      "type": 2
    }
  ],
  "exerciseIntensity": {
    "id": "3f29e372-1179-477e-b183-33356a28ece5",
    "name": "Cường độ trung bình"
  },
  "exerciseIntensities": [
    "String"
  ],
  "tags": [
    "String"
  ]
} 
*/

  String? id;
  String? code;
  String? coverId;
  String? name;
  int? day;
  int? openDay;
  int? status;
  String? description;
  String? exerciseIntensitiesId;
  ListRoadmapResponseDataItemsImage? image;
  List<ListRoadmapResponseDataItemsSelectTags?>? selectTags;
  ListRoadmapResponseDataItemsExerciseIntensity? exerciseIntensity;
  List<String?>? exerciseIntensities;
  List<String?>? tags;

  ListRoadmapResponseDataItems({
    this.id,
    this.code,
    this.coverId,
    this.name,
    this.day,
    this.openDay,
    this.status,
    this.description,
    this.exerciseIntensitiesId,
    this.image,
    this.selectTags,
    this.exerciseIntensity,
    this.exerciseIntensities,
    this.tags,
  });
  ListRoadmapResponseDataItems.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    code = json['code']?.toString();
    coverId = json['coverId']?.toString();
    name = json['name']?.toString();
    day = json['day']?.toInt();
    openDay = json['openDay']?.toInt();
    status = json['status']?.toInt();
    description = json['description']?.toString();
    exerciseIntensitiesId = json['exerciseIntensitiesId']?.toString();
    image = (json['image'] != null)
        ? ListRoadmapResponseDataItemsImage.fromJson(json['image'])
        : null;
    if (json['selectTags'] != null) {
      final v = json['selectTags'];
      final arr0 = <ListRoadmapResponseDataItemsSelectTags>[];
      v.forEach((v) {
        arr0.add(ListRoadmapResponseDataItemsSelectTags.fromJson(v));
      });
      selectTags = arr0;
    }
    exerciseIntensity = (json['exerciseIntensity'] != null)
        ? ListRoadmapResponseDataItemsExerciseIntensity.fromJson(
            json['exerciseIntensity'])
        : null;
    if (json['exerciseIntensities'] != null) {
      final v = json['exerciseIntensities'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      exerciseIntensities = arr0;
    }
    if (json['tags'] != null) {
      final v = json['tags'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      tags = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['code'] = code;
    data['coverId'] = coverId;
    data['name'] = name;
    data['day'] = day;
    data['openDay'] = openDay;
    data['status'] = status;
    data['description'] = description;
    data['exerciseIntensitiesId'] = exerciseIntensitiesId;
    if (image != null) {
      data['image'] = image!.toJson();
    }
    if (selectTags != null) {
      final v = selectTags;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['selectTags'] = arr0;
    }
    if (exerciseIntensity != null) {
      data['exerciseIntensity'] = exerciseIntensity!.toJson();
    }
    if (exerciseIntensities != null) {
      final v = exerciseIntensities;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['exerciseIntensities'] = arr0;
    }
    if (tags != null) {
      final v = tags;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['tags'] = arr0;
    }
    return data;
  }
}

class ListRoadmapResponseData {
/*
{
  "total": 21,
  "page": 1,
  "size": 1,
  "items": [
    {
      "id": "8538590e-1b0b-42e0-02ac-08d9a4f8ca86",
      "code": "LT20",
      "coverId": "1d5e3414-7708-428c-1faf-08d9a4f8ca49",
      "name": "Lộ trình 20",
      "day": 1,
      "openDay": 0,
      "status": 2,
      "description": "123123",
      "exerciseIntensitiesId": "3f29e372-1179-477e-b183-33356a28ece5",
      "image": {
        "id": "1d5e3414-7708-428c-1faf-08d9a4f8ca49",
        "url": "http://diab-api-dev.savvycom.vn/App/Image/1d5e3414-7708-428c-1faf-08d9a4f8ca49?expires=1636904471&signature=0f6d3cc18c3f585ad7fa583d89ec8744f119787ba337c4e62ae12150490fba6d",
        "title": "wp3703420-iron-man-4k-wallpapers.jpg"
      },
      "selectTags": [
        {
          "id": "228f84bf-7490-4b32-d170-08d9a4f34a61",
          "name": "Lộ trình 19",
          "type": 2
        }
      ],
      "exerciseIntensity": {
        "id": "3f29e372-1179-477e-b183-33356a28ece5",
        "name": "Cường độ trung bình"
      },
      "exerciseIntensities": [
        "String"
      ],
      "tags": [
        "String"
      ]
    }
  ]
} 
*/

  int? total;
  int? page;
  int? size;
  List<ListRoadmapResponseDataItems?>? items;

  ListRoadmapResponseData({
    this.total,
    this.page,
    this.size,
    this.items,
  });
  ListRoadmapResponseData.fromJson(Map<String, dynamic> json) {
    total = json['total']?.toInt();
    page = json['page']?.toInt();
    size = json['size']?.toInt();
    if (json['items'] != null) {
      final v = json['items'];
      final arr0 = <ListRoadmapResponseDataItems>[];
      v.forEach((v) {
        arr0.add(ListRoadmapResponseDataItems.fromJson(v));
      });
      items = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['total'] = total;
    data['page'] = page;
    data['size'] = size;
    if (items != null) {
      final v = items;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['items'] = arr0;
    }
    return data;
  }
}

class ListRoadmapResponseMeta {
/*
{
  "success": true
} 
*/

  bool? success;

  ListRoadmapResponseMeta({
    this.success,
  });
  ListRoadmapResponseMeta.fromJson(Map<String, dynamic> json) {
    success = json['success'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    return data;
  }
}

class ListRoadmapResponse {
/*
{
  "meta": {
    "success": true
  },
  "data": {
    "total": 21,
    "page": 1,
    "size": 1,
    "items": [
      {
        "id": "8538590e-1b0b-42e0-02ac-08d9a4f8ca86",
        "code": "LT20",
        "coverId": "1d5e3414-7708-428c-1faf-08d9a4f8ca49",
        "name": "Lộ trình 20",
        "day": 1,
        "openDay": 0,
        "status": 2,
        "description": "123123",
        "exerciseIntensitiesId": "3f29e372-1179-477e-b183-33356a28ece5",
        "image": {
          "id": "1d5e3414-7708-428c-1faf-08d9a4f8ca49",
          "url": "http://diab-api-dev.savvycom.vn/App/Image/1d5e3414-7708-428c-1faf-08d9a4f8ca49?expires=1636904471&signature=0f6d3cc18c3f585ad7fa583d89ec8744f119787ba337c4e62ae12150490fba6d",
          "title": "wp3703420-iron-man-4k-wallpapers.jpg"
        },
        "selectTags": [
          {
            "id": "228f84bf-7490-4b32-d170-08d9a4f34a61",
            "name": "Lộ trình 19",
            "type": 2
          }
        ],
        "exerciseIntensity": {
          "id": "3f29e372-1179-477e-b183-33356a28ece5",
          "name": "Cường độ trung bình"
        },
        "exerciseIntensities": [
          "String"
        ],
        "tags": [
          "String"
        ]
      }
    ]
  }
} 
*/

  ListRoadmapResponseMeta? meta;
  ListRoadmapResponseData? data;

  ListRoadmapResponse({
    this.meta,
    this.data,
  });
  ListRoadmapResponse.fromJson(Map<String, dynamic> json) {
    meta = (json['meta'] != null)
        ? ListRoadmapResponseMeta.fromJson(json['meta'])
        : null;
    data = (json['data'] != null)
        ? ListRoadmapResponseData.fromJson(json['data'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (meta != null) {
      data['meta'] = meta!.toJson();
    }
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
