import 'package:easy_localization/easy_localization.dart';
import 'package:medical/res/R.dart';
import 'package:medical/src/modal/base/images.dart';
import 'package:medical/src/modal/food/food_model.dart';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class MenuResponseListdayfoodTimeGroupsDefaultFood {
/*
{
  "id": "16b1ea16-f607-4073-8b8c-08d98bb8e489",
  "foodMenuCode": "TD26",
  "dateCode": "T2",
  "timeCode": 1,
  "foodId": "02821a58-50cb-4290-7797-08d945b50f3d",
  "foodCategoryId": "8eff87be-cecd-43e2-300d-08d945b3544f",
  "foodUnitId": "4fd993d2-ebf1-4b5b-ad89-5e0058ab5896",
  "foodUnitName": "Phần",
  "foodName": "Ức gà nướng ớt chuông",
  "portion": 2,
  "calorie": 150.9,
  "glucose": 2.6,
  "lipid": 4.6,
  "protein": 23.2,
  "fibre": 0.8,
  "note": "Món chính b?a sáng",
  "foodType": 0,
  "foodTemplateId": "4ad4a446-edb6-467d-aba3-08d9818e3467",
  "accountId": "5ccfcf0a-b0b6-4edc-b71f-affa666283ff",
  "image": {
    "id": "7acf6d9b-700a-4573-b5ce-08d945b50f35",
    "url": "http://diab-api-dev.savvycom.vn/App/Image/7acf6d9b-700a-4573-b5ce-08d945b50f35?expires=1633923882&signature=74884512306e7ef8742fe307512d397889c6cd922b4b024fcd21dde854987f2c"
  },
  "liked": false
} 
*/

  String? id;
  String? foodMenuCode;
  String? dateCode;
  int? timeCode;
  String? foodId;
  String? foodCategoryId;
  String? foodUnitId;
  String? foodUnitName;
  String? foodName;
  int? portion;
  double? calorie;
  double? glucose;
  double? lipid;
  double? protein;
  double? fibre;
  String? note;
  int? foodType;
  String? foodTemplateId;
  String? accountId;
  ImagesModel? image;
  bool? liked;

  MenuResponseListdayfoodTimeGroupsDefaultFood({
    this.id,
    this.foodMenuCode,
    this.dateCode,
    this.timeCode,
    this.foodId,
    this.foodCategoryId,
    this.foodUnitId,
    this.foodUnitName,
    this.foodName,
    this.portion,
    this.calorie,
    this.glucose,
    this.lipid,
    this.protein,
    this.fibre,
    this.note,
    this.foodType,
    this.foodTemplateId,
    this.accountId,
    this.image,
    this.liked,
  });

  bool get isDessert => foodType != null && 4 <= foodType! && foodType! <= 6;

  FoodModel get foodModel => FoodModel(
      id: this.foodId,
      name: this.foodName,
      portion: this.portion?.toDouble() ?? 0.0,
      unit: this.foodUnitName,
      calorie: this.calorie,
      glucose: this.glucose,
      lipid: this.lipid,
      protein: this.protein,
      fibre: this.fibre,
      image: this.image,
      liked: false,
      text: null,
      description: null,
      foodCategoryId: this.foodCategoryId,
      );

  MenuResponseListdayfoodTimeGroupsDefaultFood.fromJson(
      Map<String, dynamic> json) {
    id = json["id"]?.toString();
    foodMenuCode = json["foodMenuCode"]?.toString();
    dateCode = json["dateCode"]?.toString();
    timeCode = json["timeCode"]?.toInt();
    foodId = json["foodId"]?.toString();
    foodCategoryId = json["foodCategoryId"]?.toString();
    foodUnitId = json["foodUnitId"]?.toString();
    foodUnitName = json["foodUnitName"]?.toString();
    foodName = json["foodName"]?.toString();
    portion = json["portion"]?.toInt();
    calorie = json["calorie"]?.toDouble();
    glucose = json["glucose"]?.toDouble();
    lipid = json["lipid"]?.toDouble();
    protein = json["protein"]?.toDouble();
    fibre = json["fibre"]?.toDouble();
    note = json["note"]?.toString();
    foodType = json["foodType"]?.toInt();
    foodTemplateId = json["foodTemplateId"]?.toString();
    accountId = json["accountId"]?.toString();
    image =
        (json["image"] != null) ? ImagesModel.fromJson(json["image"]) : null;
    liked = json["liked"];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["foodMenuCode"] = foodMenuCode;
    data["dateCode"] = dateCode;
    data["timeCode"] = timeCode;
    data["foodId"] = foodId;
    data["foodCategoryId"] = foodCategoryId;
    data["foodUnitId"] = foodUnitId;
    data["foodUnitName"] = foodUnitName;
    data["foodName"] = foodName;
    data["portion"] = portion;
    data["calorie"] = calorie;
    data["glucose"] = glucose;
    data["lipid"] = lipid;
    data["protein"] = protein;
    data["fibre"] = fibre;
    data["note"] = note;
    data["foodType"] = foodType;
    data["foodTemplateId"] = foodTemplateId;
    data["accountId"] = accountId;
    if (image != null) {
      data["image"] = image!.toJson();
    }
    data["liked"] = liked;
    return data;
  }
}

class MenuResponseListdayfoodTimeGroups {
/*
{
  "timeCode": 1,
  "timeName": "Bữa Sáng",
  "totalKcal": 150.9,
  "totalGlucose": 0,
  "defaultFood": [
    {
      "id": "16b1ea16-f607-4073-8b8c-08d98bb8e489",
      "foodMenuCode": "TD26",
      "dateCode": "T2",
      "timeCode": 1,
      "foodId": "02821a58-50cb-4290-7797-08d945b50f3d",
      "foodCategoryId": "8eff87be-cecd-43e2-300d-08d945b3544f",
      "foodUnitId": "4fd993d2-ebf1-4b5b-ad89-5e0058ab5896",
      "foodUnitName": "Phần",
      "foodName": "Ức gà nướng ớt chuông",
      "portion": 2,
      "calorie": 150.9,
      "glucose": 2.6,
      "lipid": 4.6,
      "protein": 23.2,
      "fibre": 0.8,
      "note": "Món chính b?a sáng",
      "foodType": 0,
      "foodTemplateId": "4ad4a446-edb6-467d-aba3-08d9818e3467",
      "accountId": "5ccfcf0a-b0b6-4edc-b71f-affa666283ff",
      "image": {
        "id": "7acf6d9b-700a-4573-b5ce-08d945b50f35",
        "url": "http://diab-api-dev.savvycom.vn/App/Image/7acf6d9b-700a-4573-b5ce-08d945b50f35?expires=1633923882&signature=74884512306e7ef8742fe307512d397889c6cd922b4b024fcd21dde854987f2c"
      },
      "liked": false
    }
  ]
} 
*/

  int? timeCode;
  String? timeName;
  double? totalKcal;
  double? totalGlucose;
  List<MenuResponseListdayfoodTimeGroupsDefaultFood?>? defaultFood;

  MenuResponseListdayfoodTimeGroups({
    this.timeCode,
    this.timeName,
    this.totalKcal,
    this.totalGlucose,
    this.defaultFood,
  });

  List<FoodModel> get listFoods {
    final List<FoodModel> foods = [];
    for (final defaultFood in defaultFood ?? []) {
      foods.add(defaultFood.foodModel);
    }
    return foods;
  }

  String? get mealName {
    if (timeCode == 4) return R.string.breakfast_sub_meal.tr();
    if (timeCode == 5) return R.string.lunch_sub_meal.tr();
    if (timeCode == 6) return R.string.dinner_sub_meal.tr();
    return this.timeName;
  }

  MenuResponseListdayfoodTimeGroups.fromJson(Map<String, dynamic> json) {
    timeCode = json["timeCode"]?.toInt();
    timeName = json["timeName"]?.toString();
    totalKcal = json["totalKcal"]?.toDouble();
    totalGlucose = json["totalGlucose"]?.toDouble();
    if (json["defaultFood"] != null) {
      final v = json["defaultFood"];
      final arr0 = <MenuResponseListdayfoodTimeGroupsDefaultFood>[];
      v.forEach((v) {
        arr0.add(MenuResponseListdayfoodTimeGroupsDefaultFood.fromJson(v));
      });
      defaultFood = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["timeCode"] = timeCode;
    data["timeName"] = timeName;
    data["totalKcal"] = totalKcal;
    data["totalGlucose"] = totalGlucose;
    if (defaultFood != null) {
      final v = defaultFood;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["defaultFood"] = arr0;
    }
    return data;
  }
}

class MenuResponseListdayfood {
/*
{
  "dateCode": "T2",
  "totalKcal": 256.9,
  "totalGlucose": 26.6,
  "timeGroups": [
    {
      "timeCode": 1,
      "timeName": "Bữa Sáng",
      "totalKcal": 150.9,
      "totalGlucose": 0,
      "defaultFood": [
        {
          "id": "16b1ea16-f607-4073-8b8c-08d98bb8e489",
          "foodMenuCode": "TD26",
          "dateCode": "T2",
          "timeCode": 1,
          "foodId": "02821a58-50cb-4290-7797-08d945b50f3d",
          "foodCategoryId": "8eff87be-cecd-43e2-300d-08d945b3544f",
          "foodUnitId": "4fd993d2-ebf1-4b5b-ad89-5e0058ab5896",
          "foodUnitName": "Phần",
          "foodName": "Ức gà nướng ớt chuông",
          "portion": 2,
          "calorie": 150.9,
          "glucose": 2.6,
          "lipid": 4.6,
          "protein": 23.2,
          "fibre": 0.8,
          "note": "Món chính b?a sáng",
          "foodType": 0,
          "foodTemplateId": "4ad4a446-edb6-467d-aba3-08d9818e3467",
          "accountId": "5ccfcf0a-b0b6-4edc-b71f-affa666283ff",
          "image": {
            "id": "7acf6d9b-700a-4573-b5ce-08d945b50f35",
            "url": "http://diab-api-dev.savvycom.vn/App/Image/7acf6d9b-700a-4573-b5ce-08d945b50f35?expires=1633923882&signature=74884512306e7ef8742fe307512d397889c6cd922b4b024fcd21dde854987f2c"
          },
          "liked": false
        }
      ]
    }
  ]
} 
*/

  String? dateCode;
  double? totalKcal;
  double? totalGlucose;
  List<MenuResponseListdayfoodTimeGroups?>? timeGroups;

  MenuResponseListdayfood({
    this.dateCode,
    this.totalKcal,
    this.totalGlucose,
    this.timeGroups,
  });
  MenuResponseListdayfood.fromJson(Map<String, dynamic> json) {
    dateCode = json["dateCode"]?.toString();
    totalKcal = json["totalKcal"]?.toDouble();
    totalGlucose = json["totalGlucose"]?.toDouble();
    if (json["timeGroups"] != null) {
      final v = json["timeGroups"];
      final arr0 = <MenuResponseListdayfoodTimeGroups>[];
      v.forEach((v) {
        arr0.add(MenuResponseListdayfoodTimeGroups.fromJson(v));
      });
      timeGroups = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["dateCode"] = dateCode;
    data["totalKcal"] = totalKcal;
    data["totalGlucose"] = totalGlucose;
    if (timeGroups != null) {
      final v = timeGroups;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["timeGroups"] = arr0;
    }
    return data;
  }
}

class MenuResponseFood {
/*
{
  "menuTitle": "Thuc don 26",
  "kCal": 1200,
  "note": ""
} 
*/

  String? menuTitle;
  int? kCal;
  String? note;

  MenuResponseFood({
    this.menuTitle,
    this.kCal,
    this.note,
  });
  MenuResponseFood.fromJson(Map<String, dynamic> json) {
    menuTitle = json["menuTitle"]?.toString();
    kCal = json["kCal"]?.toInt();
    note = json["note"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["menuTitle"] = menuTitle;
    data["kCal"] = kCal;
    data["note"] = note;
    return data;
  }
}

class MenuResponse {
/*
{
  "totalKcal": 404.9,
  "totalGlucose": 56.6,
  "food": {
    "menuTitle": "Thuc don 26",
    "kCal": 1200,
    "note": ""
  },
  "listdayfood": [
    {
      "dateCode": "T2",
      "totalKcal": 256.9,
      "totalGlucose": 26.6,
      "timeGroups": [
        {
          "timeCode": 1,
          "timeName": "Bữa Sáng",
          "totalKcal": 150.9,
          "totalGlucose": 0,
          "defaultFood": [
            {
              "id": "16b1ea16-f607-4073-8b8c-08d98bb8e489",
              "foodMenuCode": "TD26",
              "dateCode": "T2",
              "timeCode": 1,
              "foodId": "02821a58-50cb-4290-7797-08d945b50f3d",
              "foodCategoryId": "8eff87be-cecd-43e2-300d-08d945b3544f",
              "foodUnitId": "4fd993d2-ebf1-4b5b-ad89-5e0058ab5896",
              "foodUnitName": "Phần",
              "foodName": "Ức gà nướng ớt chuông",
              "portion": 2,
              "calorie": 150.9,
              "glucose": 2.6,
              "lipid": 4.6,
              "protein": 23.2,
              "fibre": 0.8,
              "note": "Món chính b?a sáng",
              "foodType": 0,
              "foodTemplateId": "4ad4a446-edb6-467d-aba3-08d9818e3467",
              "accountId": "5ccfcf0a-b0b6-4edc-b71f-affa666283ff",
              "image": {
                "id": "7acf6d9b-700a-4573-b5ce-08d945b50f35",
                "url": "http://diab-api-dev.savvycom.vn/App/Image/7acf6d9b-700a-4573-b5ce-08d945b50f35?expires=1633923882&signature=74884512306e7ef8742fe307512d397889c6cd922b4b024fcd21dde854987f2c"
              },
              "liked": false
            }
          ]
        }
      ]
    }
  ],
  "message": ""
} 
*/

  double? totalKcal;
  double? totalGlucose;
  MenuResponseFood? food;
  List<MenuResponseListdayfood?>? listdayfood;
  String? message;

  MenuResponse({
    this.totalKcal,
    this.totalGlucose,
    this.food,
    this.listdayfood,
    this.message,
  });

  String idInTime({required DateTime time, required int timeCode}) {
    final MenuResponseListdayfoodTimeGroups? timeGroups =
        _timeGroupsFromDateTime(time: time, timeCode: timeCode);
    final MenuResponseListdayfoodTimeGroupsDefaultFood? food = timeGroups
        ?.defaultFood
        ?.firstWhere((element) => element?.timeCode == timeCode);
    return food?.id ?? '';
  }

  List<FoodModel>? foodListInTime({required DateTime time, required  int timeCode}) {
    return _timeGroupsFromDateTime(time: time, timeCode: timeCode)?.listFoods;
  } 

  MenuResponseListdayfoodTimeGroups? _timeGroupsFromDateTime({required DateTime time, required  int timeCode}) {
    final String dateCode = 'T${time.weekday + 1}';
    if (listdayfood != null) {
      for (int index = 0; index < listdayfood!.length; index++) {
        if (listdayfood![index]?.dateCode == dateCode) {
          final MenuResponseListdayfoodTimeGroups? foods = listdayfood![index]
              ?.timeGroups
              ?.firstWhere((mealDetail) => mealDetail?.timeCode == timeCode);
          return foods;
        }
      }
    }
  }

  void sortListDayFood() {
    if (listdayfood != null) {
      for (int index = 0; index < listdayfood!.length; index++) {
        listdayfood![index]?.timeGroups =
            _sortSingleTimeGroup(listdayfood![index]?.timeGroups);
      }
    }
  }

  List<MenuResponseListdayfoodTimeGroups?>? _sortSingleTimeGroup(
      List<MenuResponseListdayfoodTimeGroups?>? mealList) {
    if (mealList == null) return null;
    final List<MenuResponseListdayfoodTimeGroups?> newMealList = [];
    newMealList.addAll(mealList.where((meal) => meal?.timeCode == 1));
    newMealList.addAll(mealList.where((meal) => meal?.timeCode == 4));
    newMealList.addAll(mealList.where((meal) => meal?.timeCode == 2));
    newMealList.addAll(mealList.where((meal) => meal?.timeCode == 5));
    newMealList.addAll(mealList.where((meal) => meal?.timeCode == 3));
    newMealList.addAll(mealList.where((meal) => meal?.timeCode == 6));
    return newMealList;
  }

  MenuResponse.fromJson(Map<String, dynamic> json) {
    totalKcal = json["totalKcal"]?.toDouble();
    totalGlucose = json["totalGlucose"]?.toDouble();
    food =
        (json["food"] != null) ? MenuResponseFood.fromJson(json["food"]) : null;
    if (json["listdayfood"] != null) {
      final v = json["listdayfood"];
      final arr0 = <MenuResponseListdayfood>[];
      v.forEach((v) {
        arr0.add(MenuResponseListdayfood.fromJson(v));
      });
      listdayfood = arr0;
    }
    message = json["message"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["totalKcal"] = totalKcal;
    data["totalGlucose"] = totalGlucose;
    if (food != null) {
      data["food"] = food!.toJson();
    }
    if (listdayfood != null) {
      final v = listdayfood;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["listdayfood"] = arr0;
    }
    data["message"] = message;
    return data;
  }
}
