///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class MenuResponseListdayfoodTimeGroupsDefaultFood {
/*
{
  "id": "5b525d8a-61f7-4f17-2e50-08d981116b4e",
  "foodMenuCode": "TD17",
  "dateCode": "T2",
  "timeCode": 1,
  "foodId": "02821a58-50cb-4290-7797-08d945b50f3d",
  "foodCategoryId": "8eff87be-cecd-43e2-300d-08d945b3544f",
  "foodUnitId": "4fd993d2-ebf1-4b5b-ad89-5e0058ab5896",
  "foodUnitName": "Phần",
  "foodName": "Ức gà nướng ớt chuông",
  "portion": 2,
  "calorie": 150.9,
  "glucose": 2.6,
  "lipid": 4.6,
  "protein": 23.2,
  "fibre": 0.8,
  "note": "T2 food",
  "foodSubstitute": null
} 
*/

  String? id;
  String? foodMenuCode;
  String? dateCode;
  int? timeCode;
  String? foodId;
  String? foodCategoryId;
  String? foodUnitId;
  String? foodUnitName;
  String? foodName;
  int? portion;
  double? calorie;
  double? glucose;
  double? lipid;
  double? protein;
  double? fibre;
  String? note;
  List<MenuResponseListdayfoodTimeGroupsDefaultFood?>? foodSubstitute;

  MenuResponseListdayfoodTimeGroupsDefaultFood({
    this.id,
    this.foodMenuCode,
    this.dateCode,
    this.timeCode,
    this.foodId,
    this.foodCategoryId,
    this.foodUnitId,
    this.foodUnitName,
    this.foodName,
    this.portion,
    this.calorie,
    this.glucose,
    this.lipid,
    this.protein,
    this.fibre,
    this.note,
    this.foodSubstitute,
  });
  MenuResponseListdayfoodTimeGroupsDefaultFood.fromJson(
      Map<String, dynamic> json) {
    id = json["id"]?.toString();
    foodMenuCode = json["foodMenuCode"]?.toString();
    dateCode = json["dateCode"]?.toString();
    timeCode = json["timeCode"]?.toInt();
    foodId = json["foodId"]?.toString();
    foodCategoryId = json["foodCategoryId"]?.toString();
    foodUnitId = json["foodUnitId"]?.toString();
    foodUnitName = json["foodUnitName"]?.toString();
    foodName = json["foodName"]?.toString();
    portion = json["portion"]?.toInt();
    calorie = json["calorie"]?.toDouble();
    glucose = json["glucose"]?.toDouble();
    lipid = json["lipid"]?.toDouble();
    protein = json["protein"]?.toDouble();
    fibre = json["fibre"]?.toDouble();
    note = json["note"]?.toString();
    if (json["foodSubstitute"] != null) {
      final v = json["foodSubstitute"];
      final arr0 = <MenuResponseListdayfoodTimeGroupsDefaultFood>[];
      v.forEach((v) {
        arr0.add(MenuResponseListdayfoodTimeGroupsDefaultFood.fromJson(v));
      });
      foodSubstitute = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["foodMenuCode"] = foodMenuCode;
    data["dateCode"] = dateCode;
    data["timeCode"] = timeCode;
    data["foodId"] = foodId;
    data["foodCategoryId"] = foodCategoryId;
    data["foodUnitId"] = foodUnitId;
    data["foodUnitName"] = foodUnitName;
    data["foodName"] = foodName;
    data["portion"] = portion;
    data["calorie"] = calorie;
    data["glucose"] = glucose;
    data["lipid"] = lipid;
    data["protein"] = protein;
    data["fibre"] = fibre;
    data["note"] = note;
    data["foodSubstitute"] = foodSubstitute;
    return data;
  }
}

class MenuResponseListdayfoodTimeGroups {
/*
{
  "timeCode": 1,
  "timeName": "Bữa Sáng",
  "totalKcal": 603.6,
  "defaultFood": [
    {
      "id": "5b525d8a-61f7-4f17-2e50-08d981116b4e",
      "foodMenuCode": "TD17",
      "dateCode": "T2",
      "timeCode": 1,
      "foodId": "02821a58-50cb-4290-7797-08d945b50f3d",
      "foodCategoryId": "8eff87be-cecd-43e2-300d-08d945b3544f",
      "foodUnitId": "4fd993d2-ebf1-4b5b-ad89-5e0058ab5896",
      "foodUnitName": "Phần",
      "foodName": "Ức gà nướng ớt chuông",
      "portion": 2,
      "calorie": 150.9,
      "glucose": 2.6,
      "lipid": 4.6,
      "protein": 23.2,
      "fibre": 0.8,
      "note": "T2 food",
      "foodSubstitute": null
    }
  ]
} 
*/

  int? timeCode;
  String? timeName;
  double? totalKcal;
  List<MenuResponseListdayfoodTimeGroupsDefaultFood?>? defaultFood;

  MenuResponseListdayfoodTimeGroups({
    this.timeCode,
    this.timeName,
    this.totalKcal,
    this.defaultFood,
  });
  MenuResponseListdayfoodTimeGroups.fromJson(Map<String, dynamic> json) {
    timeCode = json["timeCode"]?.toInt();
    timeName = json["timeName"]?.toString();
    totalKcal = json["totalKcal"]?.toDouble();
    if (json["defaultFood"] != null) {
      final v = json["defaultFood"];
      final arr0 = <MenuResponseListdayfoodTimeGroupsDefaultFood>[];
      v.forEach((v) {
        arr0.add(MenuResponseListdayfoodTimeGroupsDefaultFood.fromJson(v));
      });
      defaultFood = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["timeCode"] = timeCode;
    data["timeName"] = timeName;
    data["totalKcal"] = totalKcal;
    if (defaultFood != null) {
      final v = defaultFood;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["defaultFood"] = arr0;
    }
    return data;
  }
}

class MenuResponseListdayfood {
/*
{
  "dateCode": "T2",
  "totalKcal": 905.4000000000001,
  "timeGroups": [
    {
      "timeCode": 1,
      "timeName": "Bữa Sáng",
      "totalKcal": 603.6,
      "defaultFood": [
        {
          "id": "5b525d8a-61f7-4f17-2e50-08d981116b4e",
          "foodMenuCode": "TD17",
          "dateCode": "T2",
          "timeCode": 1,
          "foodId": "02821a58-50cb-4290-7797-08d945b50f3d",
          "foodCategoryId": "8eff87be-cecd-43e2-300d-08d945b3544f",
          "foodUnitId": "4fd993d2-ebf1-4b5b-ad89-5e0058ab5896",
          "foodUnitName": "Phần",
          "foodName": "Ức gà nướng ớt chuông",
          "portion": 2,
          "calorie": 150.9,
          "glucose": 2.6,
          "lipid": 4.6,
          "protein": 23.2,
          "fibre": 0.8,
          "note": "T2 food",
          "foodSubstitute": null
        }
      ]
    }
  ]
} 
*/

  String? dateCode;
  double? totalKcal;
  List<MenuResponseListdayfoodTimeGroups?>? timeGroups;

  MenuResponseListdayfood({
    this.dateCode,
    this.totalKcal,
    this.timeGroups,
  });
  MenuResponseListdayfood.fromJson(Map<String, dynamic> json) {
    dateCode = json["dateCode"]?.toString();
    totalKcal = json["totalKcal"]?.toDouble();
    if (json["timeGroups"] != null) {
      final v = json["timeGroups"];
      final arr0 = <MenuResponseListdayfoodTimeGroups>[];
      v.forEach((v) {
        arr0.add(MenuResponseListdayfoodTimeGroups.fromJson(v));
      });
      timeGroups = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["dateCode"] = dateCode;
    data["totalKcal"] = totalKcal;
    if (timeGroups != null) {
      final v = timeGroups;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["timeGroups"] = arr0;
    }
    return data;
  }
}

class MenuResponse {
/*
{
  "totalKcal": 905.4,
  "listdayfood": [
    {
      "dateCode": "T2",
      "totalKcal": 905.4000000000001,
      "timeGroups": [
        {
          "timeCode": 1,
          "timeName": "Bữa Sáng",
          "totalKcal": 603.6,
          "defaultFood": [
            {
              "id": "5b525d8a-61f7-4f17-2e50-08d981116b4e",
              "foodMenuCode": "TD17",
              "dateCode": "T2",
              "timeCode": 1,
              "foodId": "02821a58-50cb-4290-7797-08d945b50f3d",
              "foodCategoryId": "8eff87be-cecd-43e2-300d-08d945b3544f",
              "foodUnitId": "4fd993d2-ebf1-4b5b-ad89-5e0058ab5896",
              "foodUnitName": "Phần",
              "foodName": "Ức gà nướng ớt chuông",
              "portion": 2,
              "calorie": 150.9,
              "glucose": 2.6,
              "lipid": 4.6,
              "protein": 23.2,
              "fibre": 0.8,
              "note": "T2 food",
              "foodSubstitute": null
            }
          ]
        }
      ]
    }
  ],
  "message": "null"
} 
*/

  double? totalKcal;
  List<MenuResponseListdayfood?>? listdayfood;
  String? message;

  MenuResponse({
    this.totalKcal,
    this.listdayfood,
    this.message,
  });
  MenuResponse.fromJson(Map<String, dynamic> json) {
    totalKcal = json["totalKcal"]?.toDouble();
    if (json["listdayfood"] != null) {
      final v = json["listdayfood"];
      final arr0 = <MenuResponseListdayfood>[];
      v.forEach((v) {
        arr0.add(MenuResponseListdayfood.fromJson(v));
      });
      listdayfood = arr0;
    }
    message = json["message"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["totalKcal"] = totalKcal;
    if (listdayfood != null) {
      final v = listdayfood;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["listdayfood"] = arr0;
    }
    data["message"] = message;
    return data;
  }
}
