import 'package:medical/src/modal/base/images.dart';
import 'package:medical/src/modal/food/food_model.dart';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class MenuResponseListdayfoodTimeGroupsDefaultFood {
/*
{
  "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "foodMenuCode": "string",
  "dateCode": "string",
  "timeCode": 1,
  "foodId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "foodCategoryId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "foodUnitId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "foodUnitName": "string",
  "foodName": "string",
  "portion": 12.3,
  "calorie": 13.2,
  "glucose": 1.4,
  "lipid": 3.6,
  "protein": 2.5,
  "fibre": 1.3,
  "note": "string",
  "foodType": 0,
  "foodTemplateId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "accountId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "foodImgUrl": "string"
} 
*/

  String? id;
  String? foodMenuCode;
  String? dateCode;
  int? timeCode;
  String? foodId;
  String? foodCategoryId;
  String? foodUnitId;
  String? foodUnitName;
  String? foodName;
  double? portion;
  double? calorie;
  double? glucose;
  double? lipid;
  double? protein;
  double? fibre;
  String? note;
  int? foodType;
  String? foodTemplateId;
  String? accountId;
  String? foodImgUrl;

  MenuResponseListdayfoodTimeGroupsDefaultFood({
    this.id,
    this.foodMenuCode,
    this.dateCode,
    this.timeCode,
    this.foodId,
    this.foodCategoryId,
    this.foodUnitId,
    this.foodUnitName,
    this.foodName,
    this.portion,
    this.calorie,
    this.glucose,
    this.lipid,
    this.protein,
    this.fibre,
    this.note,
    this.foodType,
    this.foodTemplateId,
    this.accountId,
    this.foodImgUrl,
  });

  bool get isDessert => foodType != null && 4 <= foodType! && foodType! <= 6;

  FoodModel get foodModel => FoodModel(
      id: this.id,
      name: this.foodName,
      portion: this.portion ?? 0.0,
      unit: this.foodUnitName,
      calorie: this.calorie,
      glucose: this.glucose,
      lipid: this.lipid,
      protein: this.protein,
      fibre: this.fibre,
      image: ImagesModel(
        id: '',
        url: this.foodImgUrl,
      ),
      liked: false,
      text: null,
      description: null,
      foodCategoryId: this.foodCategoryId,
      quantity: 0.0);

  MenuResponseListdayfoodTimeGroupsDefaultFood.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toString();
    foodMenuCode = json["foodMenuCode"]?.toString();
    dateCode = json["dateCode"]?.toString();
    timeCode = json["timeCode"]?.toInt();
    foodId = json["foodId"]?.toString();
    foodCategoryId = json["foodCategoryId"]?.toString();
    foodUnitId = json["foodUnitId"]?.toString();
    foodUnitName = json["foodUnitName"]?.toString();
    foodName = json["foodName"]?.toString();
    portion = json["portion"]?.toDouble();
    calorie = json["calorie"]?.toDouble();
    glucose = json["glucose"]?.toDouble();
    lipid = json["lipid"]?.toDouble();
    protein = json["protein"]?.toDouble();
    fibre = json["fibre"]?.toDouble();
    note = json["note"]?.toString();
    foodType = json["foodType"]?.toInt();
    foodTemplateId = json["foodTemplateId"]?.toString();
    accountId = json["accountId"]?.toString();
    foodImgUrl = json["foodImgUrl"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["foodMenuCode"] = foodMenuCode;
    data["dateCode"] = dateCode;
    data["timeCode"] = timeCode;
    data["foodId"] = foodId;
    data["foodCategoryId"] = foodCategoryId;
    data["foodUnitId"] = foodUnitId;
    data["foodUnitName"] = foodUnitName;
    data["foodName"] = foodName;
    data["portion"] = portion;
    data["calorie"] = calorie;
    data["glucose"] = glucose;
    data["lipid"] = lipid;
    data["protein"] = protein;
    data["fibre"] = fibre;
    data["note"] = note;
    data["foodType"] = foodType;
    data["foodTemplateId"] = foodTemplateId;
    data["accountId"] = accountId;
    data["foodImgUrl"] = foodImgUrl;
    return data;
  }
}

class MenuResponseListdayfoodTimeGroups {
/*
{
  "timeCode": 1,
  "timeName": "string",
  "totalKcal": 2.5,
  "totalGlucose": 2.4,
  "defaultFood": [
    {
      "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "foodMenuCode": "string",
      "dateCode": "string",
      "timeCode": 1,
      "foodId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "foodCategoryId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "foodUnitId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "foodUnitName": "string",
      "foodName": "string",
      "portion": 12.3,
      "calorie": 13.2,
      "glucose": 1.4,
      "lipid": 3.6,
      "protein": 2.5,
      "fibre": 1.3,
      "note": "string",
      "foodType": 0,
      "foodTemplateId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "accountId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "foodImgUrl": "string"
    }
  ]
} 
*/

  int? timeCode;
  String? timeName;
  double? totalKcal;
  double? totalGlucose;
  List<MenuResponseListdayfoodTimeGroupsDefaultFood?>? defaultFood;

  MenuResponseListdayfoodTimeGroups({
    this.timeCode,
    this.timeName,
    this.totalKcal,
    this.totalGlucose,
    this.defaultFood,
  });
  MenuResponseListdayfoodTimeGroups.fromJson(Map<String, dynamic> json) {
    timeCode = json["timeCode"]?.toInt();
    timeName = json["timeName"]?.toString();
    totalKcal = json["totalKcal"]?.toDouble();
    totalGlucose = json["totalGlucose"]?.toDouble();
  if (json["defaultFood"] != null) {
  final v = json["defaultFood"];
  final arr0 = <MenuResponseListdayfoodTimeGroupsDefaultFood>[];
  v.forEach((v) {
  arr0.add(MenuResponseListdayfoodTimeGroupsDefaultFood.fromJson(v));
  });
    defaultFood = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["timeCode"] = timeCode;
    data["timeName"] = timeName;
    data["totalKcal"] = totalKcal;
    data["totalGlucose"] = totalGlucose;
    if (defaultFood != null) {
      final v = defaultFood;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data["defaultFood"] = arr0;
    }
    return data;
  }
}

class MenuResponseListdayfood {
/*
{
  "dateCode": "string",
  "totalKcal": 1.7,
  "totalGlucose": 2.8,
  "timeGroups": [
    {
      "timeCode": 1,
      "timeName": "string",
      "totalKcal": 2.5,
      "totalGlucose": 2.4,
      "defaultFood": [
        {
          "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
          "foodMenuCode": "string",
          "dateCode": "string",
          "timeCode": 1,
          "foodId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
          "foodCategoryId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
          "foodUnitId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
          "foodUnitName": "string",
          "foodName": "string",
          "portion": 12.3,
          "calorie": 13.2,
          "glucose": 1.4,
          "lipid": 3.6,
          "protein": 2.5,
          "fibre": 1.3,
          "note": "string",
          "foodType": 0,
          "foodTemplateId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
          "accountId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
          "foodImgUrl": "string"
        }
      ]
    }
  ]
} 
*/

  String? dateCode;
  double? totalKcal;
  double? totalGlucose;
  List<MenuResponseListdayfoodTimeGroups?>? timeGroups;

  MenuResponseListdayfood({
    this.dateCode,
    this.totalKcal,
    this.totalGlucose,
    this.timeGroups,
  });
  MenuResponseListdayfood.fromJson(Map<String, dynamic> json) {
    dateCode = json["dateCode"]?.toString();
    totalKcal = json["totalKcal"]?.toDouble();
    totalGlucose = json["totalGlucose"]?.toDouble();
  if (json["timeGroups"] != null) {
  final v = json["timeGroups"];
  final arr0 = <MenuResponseListdayfoodTimeGroups>[];
  v.forEach((v) {
  arr0.add(MenuResponseListdayfoodTimeGroups.fromJson(v));
  });
    timeGroups = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["dateCode"] = dateCode;
    data["totalKcal"] = totalKcal;
    data["totalGlucose"] = totalGlucose;
    if (timeGroups != null) {
      final v = timeGroups;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data["timeGroups"] = arr0;
    }
    return data;
  }
}

class MenuResponseFood {
/*
{
  "menuTitle": "string",
  "kCal": 6.1,
  "status": 1,
  "note": "string"
} 
*/

  String? menuTitle;
  double? kCal;
  int? status;
  String? note;

  MenuResponseFood({
    this.menuTitle,
    this.kCal,
    this.status,
    this.note,
  });
  MenuResponseFood.fromJson(Map<String, dynamic> json) {
    menuTitle = json["menuTitle"]?.toString();
    kCal = json["kCal"]?.toDouble();
    status = json["status"]?.toInt();
    note = json["note"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["menuTitle"] = menuTitle;
    data["kCal"] = kCal;
    data["status"] = status;
    data["note"] = note;
    return data;
  }
}

class MenuResponse {
/*
{
  "totalKcal": 130.5,
  "totalGlucose": 6.7,
  "food": {
    "menuTitle": "string",
    "kCal": 6.1,
    "status": 1,
    "note": "string"
  },
  "listdayfood": [
    {
      "dateCode": "string",
      "totalKcal": 1.7,
      "totalGlucose": 2.8,
      "timeGroups": [
        {
          "timeCode": 1,
          "timeName": "string",
          "totalKcal": 2.5,
          "totalGlucose": 2.4,
          "defaultFood": [
            {
              "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
              "foodMenuCode": "string",
              "dateCode": "string",
              "timeCode": 1,
              "foodId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
              "foodCategoryId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
              "foodUnitId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
              "foodUnitName": "string",
              "foodName": "string",
              "portion": 12.3,
              "calorie": 13.2,
              "glucose": 1.4,
              "lipid": 3.6,
              "protein": 2.5,
              "fibre": 1.3,
              "note": "string",
              "foodType": 0,
              "foodTemplateId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
              "accountId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
              "foodImgUrl": "string"
            }
          ]
        }
      ]
    }
  ],
  "message": "string"
} 
*/

  double? totalKcal;
  double? totalGlucose;
  MenuResponseFood? food;
  List<MenuResponseListdayfood?>? listdayfood;
  String? message;

  MenuResponse({
    this.totalKcal,
    this.totalGlucose,
    this.food,
    this.listdayfood,
    this.message,
  });
  MenuResponse.fromJson(Map<String, dynamic> json) {
    totalKcal = json["totalKcal"]?.toDouble();
    totalGlucose = json["totalGlucose"]?.toDouble();
    food = (json["food"] != null) ? MenuResponseFood.fromJson(json["food"]) : null;
  if (json["listdayfood"] != null) {
  final v = json["listdayfood"];
  final arr0 = <MenuResponseListdayfood>[];
  v.forEach((v) {
  arr0.add(MenuResponseListdayfood.fromJson(v));
  });
    listdayfood = arr0;
    }
    message = json["message"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["totalKcal"] = totalKcal;
    data["totalGlucose"] = totalGlucose;
    if (food != null) {
      data["food"] = food!.toJson();
    }
    if (listdayfood != null) {
      final v = listdayfood;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data["listdayfood"] = arr0;
    }
    data["message"] = message;
    return data;
  }
}