///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class MyLessonResponseData {
/*
{
  "id": "0c8c3920-dd49-41ad-aa1b-08d987ed41f9",
  "name": "Khóa h?c dinh du?ng 3",
  "level": "",
  "module": "Vận động",
  "learningStatus": 0,
  "percentComplete": 0,
  "order": 2,
  "lessonLevelOrder": 1
} 
*/

  String? id;
  String? name;
  String? level;
  String? module;
  int? learningStatus;
  int? percentComplete;
  int? order;
  int? lessonLevelOrder;

  MyLessonResponseData({
    this.id,
    this.name,
    this.level,
    this.module,
    this.learningStatus,
    this.percentComplete,
    this.order,
    this.lessonLevelOrder,
  });
  MyLessonResponseData.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toString();
    name = json["name"]?.toString();
    level = json["level"]?.toString();
    module = json["module"]?.toString();
    learningStatus = json["learningStatus"]?.toInt();
    percentComplete = json["percentComplete"]?.toInt();
    order = json["order"]?.toInt();
    lessonLevelOrder = json["lessonLevelOrder"]?.toInt();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["name"] = name;
    data["level"] = level;
    data["module"] = module;
    data["learningStatus"] = learningStatus;
    data["percentComplete"] = percentComplete;
    data["order"] = order;
    data["lessonLevelOrder"] = lessonLevelOrder;
    return data;
  }
}

class MyLessonResponse {
/*
{
  "id": "00000000-0000-0000-0000-000000000000",
  "statusCode": 200,
  "message": "Success",
  "data": [
    {
      "id": "0c8c3920-dd49-41ad-aa1b-08d987ed41f9",
      "name": "Khóa h?c dinh du?ng 3",
      "level": "",
      "module": "Vận động",
      "learningStatus": 0,
      "percentComplete": 0,
      "order": 2,
      "lessonLevelOrder": 1
    }
  ]
} 
*/

  String? id;
  int? statusCode;
  String? message;
  List<MyLessonResponseData?>? data;

  MyLessonResponse({
    this.id,
    this.statusCode,
    this.message,
    this.data,
  });
  MyLessonResponse.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toString();
    statusCode = json["statusCode"]?.toInt();
    message = json["message"]?.toString();
  if (json["data"] != null) {
  final v = json["data"];
  final arr0 = <MyLessonResponseData>[];
  v.forEach((v) {
  arr0.add(MyLessonResponseData.fromJson(v));
  });
    this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["statusCode"] = statusCode;
    data["message"] = message;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data["data"] = arr0;
    }
    return data;
  }
}