import 'package:medical/src/modal/base/images.dart';
import 'package:medical/src/utils/const.dart';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class MyLessonResponseDataLessonTagMappingsTag {
/*
{
  "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "name": "string",
  "type": 1
} 
*/

  String? id;
  String? name;
  int? type;

  MyLessonResponseDataLessonTagMappingsTag({
    this.id,
    this.name,
    this.type,
  });
  MyLessonResponseDataLessonTagMappingsTag.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    name = json['name']?.toString();
    type = json['type']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['type'] = type;
    return data;
  }
}

class MyLessonResponseDataLessonTagMappings {
/*
{
  "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "lessonId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "lessonTagId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "tag": {
    "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
    "name": "string",
    "type": 1
  }
} 
*/

  String? id;
  String? lessonId;
  String? lessonTagId;
  MyLessonResponseDataLessonTagMappingsTag? tag;

  MyLessonResponseDataLessonTagMappings({
    this.id,
    this.lessonId,
    this.lessonTagId,
    this.tag,
  });

  MyLessonResponseDataLessonTagMappings.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    lessonId = json['lessonId']?.toString();
    lessonTagId = json['lessonTagId']?.toString();
    tag = (json['tag'] != null)
        ? MyLessonResponseDataLessonTagMappingsTag.fromJson(json['tag'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['lessonId'] = lessonId;
    data['lessonTagId'] = lessonTagId;
    if (tag != null) {
      data['tag'] = tag!.toJson();
    }
    return data;
  }
}

class MyLessonResponseData {
/*
{
  "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "name": "string",
  "status": 0,
  "type": 1,
  "level": "string",
  "module": "string",
  "learningStatus": 0,
  "percentComplete": 0,
  "order": 0,
  "levelOrder": 0,
  "isNew": true,
  "activeDateTime": 0,
  "lessonTagMappings": [
    {
      "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "lessonId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "lessonTagId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "tag": {
        "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
        "name": "string",
        "type": 1
      }
    }
  ],
  "image": {
    "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
    "url": "string"
  },
  "lessonLevelOrder": 0
} 
*/

  String? id;
  String? name;
  int? status;
  int? type;
  String? level;
  String? module;
  int? learningStatus;
  int? percentComplete;
  int? order;
  int? levelOrder;
  bool? isNew;
  int? activeDateTime;
  List<MyLessonResponseDataLessonTagMappings?>? lessonTagMappings;
  ImagesModel? image;
  int? lessonLevelOrder;

  MyLessonResponseData({
    this.id,
    this.name,
    this.status,
    this.type,
    this.level,
    this.module,
    this.learningStatus,
    this.percentComplete,
    this.order,
    this.levelOrder,
    this.isNew,
    this.activeDateTime,
    this.lessonTagMappings,
    this.image,
    this.lessonLevelOrder,
  });

  String get tagName {
    if (lessonTagMappings?.isNotEmpty != true) return '';
    return lessonTagMappings?.first?.tag?.name ?? '';
  }

  MyLessonResponseData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    name = json['name']?.toString();
    status = json['status']?.toInt();
    type = json['type']?.toInt();
    level = json['level']?.toString();
    module = json['module']?.toString();
    learningStatus = json['learningStatus']?.toInt();
    percentComplete = json['percentComplete']?.toInt();
    order = json['order']?.toInt();
    levelOrder = json['levelOrder']?.toInt();
    isNew = json['isNew'];
    activeDateTime = json['activeDateTime']?.toInt();
    if (json['lessonTagMappings'] != null) {
      final v = json['lessonTagMappings'];
      final arr0 = <MyLessonResponseDataLessonTagMappings>[];
      v.forEach((v) {
        arr0.add(MyLessonResponseDataLessonTagMappings.fromJson(v));
      });
      lessonTagMappings = arr0;
    }
    image =
        (json['image'] != null) ? ImagesModel.fromJson(json['image']) : null;
    lessonLevelOrder = json['lessonLevelOrder']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['status'] = status;
    data['type'] = type;
    data['level'] = level;
    data['module'] = module;
    data['learningStatus'] = learningStatus;
    data['percentComplete'] = percentComplete;
    data['order'] = order;
    data['levelOrder'] = levelOrder;
    data['isNew'] = isNew;
    data['activeDateTime'] = activeDateTime;
    if (lessonTagMappings != null) {
      final v = lessonTagMappings;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['lessonTagMappings'] = arr0;
    }
    if (image != null) {
      data['image'] = image!.toJson();
    }
    data['lessonLevelOrder'] = lessonLevelOrder;
    return data;
  }
}

class MyLessonResponseMeta {
/*
{
  "success": true
} 
*/

  bool? success;

  MyLessonResponseMeta({
    this.success,
  });
  MyLessonResponseMeta.fromJson(Map<String, dynamic> json) {
    success = json['success'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    return data;
  }
}

class MyLessonResponse {
/*
{
  "meta": {
    "success": true
  },
  "data": [
    {
      "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "name": "string",
      "status": 0,
      "level": "string",
      "module": "string",
      "learningStatus": 0,
      "percentComplete": 0,
      "order": 0,
      "levelOrder": 0,
      "isNew": true,
      "activeDateTime": 0,
      "lessonTagMappings": [
        {
          "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
          "lessonId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
          "lessonTagId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
          "tag": {
            "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
            "name": "string",
            "type": 1
          }
        }
      ],
      "image": {
        "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
        "url": "string"
      },
      "lessonLevelOrder": 0
    }
  ]
} 
*/

  MyLessonResponseMeta? meta;
  List<MyLessonResponseData?>? data;

  MyLessonResponse({
    this.meta,
    this.data,
  });

  int get firstLessonIndex {
    if (data?.isNotEmpty != true) return 0;
    for (int index = 0; index < (data?.length ?? 0); index++) {
      if (data?[index]?.learningStatus != null &&
          data?[index]?.learningStatus != Const.LESSON_LEARNT) {
        return index;
      }
    }
    return 0;
  }

  MyLessonResponse.fromJson(Map<String, dynamic> json) {
    meta = (json['meta'] != null)
        ? MyLessonResponseMeta.fromJson(json['meta'])
        : null;
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <MyLessonResponseData>[];
      v.forEach((v) {
        arr0.add(MyLessonResponseData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (meta != null) {
      data['meta'] = meta!.toJson();
    }
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }
}
