///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///

class MyProgressResponseChartData {
/*
{
  "completed": 0,
  "unlocked": 0,
  "total": 0
} 
*/

  int? inTimeCompleted;
  int? inTime;
  int? allTime;

  MyProgressResponseChartData({
    this.inTimeCompleted,
    this.inTime,
    this.allTime,
  });
  MyProgressResponseChartData.fromJson(Map<String, dynamic> json) {
    inTimeCompleted = json['inTimeCompleted']?.toInt();
    inTime = json['inTime']?.toInt();
    allTime = json['allTime']?.toInt() ?? 0;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['inTimeCompleted'] = inTimeCompleted;
    data['inTime'] = inTime;
    data['allTime'] = allTime;
    return data;
  }
}

class MyProgressResponseData {
/*
{
  "lesson": {
    "completed": 0,
    "unlocked": 0,
    "total": 0
  },
  "exerciseMovement": {
    "completed": 0,
    "unlocked": 0,
    "total": 0
  },
  "target": {
    "completed": 0,
    "unlocked": 0,
    "total": 0
  },
  "coach11": {
    "completed": 0,
    "unlocked": 0,
    "total": 0
  },
  "coach1N": {
    "completed": 0,
    "unlocked": 0,
    "total": 0
  }
} 
*/

  MyProgressResponseChartData? lesson;
  MyProgressResponseChartData? exerciseMovement;
  MyProgressResponseChartData? target;
  MyProgressResponseChartData? coach11;
  MyProgressResponseChartData? coach1N;

  MyProgressResponseData({
    this.lesson,
    this.exerciseMovement,
    this.target,
    this.coach11,
    this.coach1N,
  });
  MyProgressResponseData.fromJson(Map<String, dynamic> json) {
    lesson = (json['lesson'] != null)
        ? MyProgressResponseChartData.fromJson(json['lesson'])
        : null;
    exerciseMovement = (json['exerciseMovement'] != null)
        ? MyProgressResponseChartData.fromJson(json['exerciseMovement'])
        : null;
    target = (json['target'] != null)
        ? MyProgressResponseChartData.fromJson(json['target'])
        : null;
    coach11 = (json['coach11'] != null)
        ? MyProgressResponseChartData.fromJson(json['coach11'])
        : null;
    coach1N = (json['coach1N'] != null)
        ? MyProgressResponseChartData.fromJson(json['coach1N'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (lesson != null) {
      data['lesson'] = lesson!.toJson();
    }
    if (exerciseMovement != null) {
      data['exerciseMovement'] = exerciseMovement!.toJson();
    }
    if (target != null) {
      data['target'] = target!.toJson();
    }
    if (coach11 != null) {
      data['coach11'] = coach11!.toJson();
    }
    if (coach1N != null) {
      data['coach1N'] = coach1N!.toJson();
    }
    return data;
  }
}

class MyProgressResponseMeta {
/*
{
  "success": true
} 
*/

  bool? success;

  MyProgressResponseMeta({
    this.success,
  });
  MyProgressResponseMeta.fromJson(Map<String, dynamic> json) {
    success = json['success'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    return data;
  }
}

class MyProgressResponse {
/*
{
  "meta": {
    "success": true
  },
  "data": {
    "lesson": {
      "completed": 0,
      "unlocked": 0,
      "total": 0
    },
    "exerciseMovement": {
      "completed": 0,
      "unlocked": 0,
      "total": 0
    },
    "target": {
      "completed": 0,
      "unlocked": 0,
      "total": 0
    },
    "coach11": {
      "completed": 0,
      "unlocked": 0,
      "total": 0
    },
    "coach1N": {
      "completed": 0,
      "unlocked": 0,
      "total": 0
    }
  }
} 
*/

  MyProgressResponseMeta? meta;
  MyProgressResponseData? data;

  MyProgressResponse({
    this.meta,
    this.data,
  });
  MyProgressResponse.fromJson(Map<String, dynamic> json) {
    meta = (json['meta'] != null)
        ? MyProgressResponseMeta.fromJson(json['meta'])
        : null;
    data = (json['data'] != null)
        ? MyProgressResponseData.fromJson(json['data'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (meta != null) {
      data['meta'] = meta!.toJson();
    }
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
