///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class PatientInfoResponseData {
/*
{
  "fullName": "Đặng Tiểu Cường"
} 
*/

  String? fullName;

  PatientInfoResponseData({
    this.fullName,
  });
  PatientInfoResponseData.fromJson(Map<String, dynamic> json) {
    fullName = json['fullName']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['fullName'] = fullName;
    return data;
  }
}

class PatientInfoResponseMeta {
/*
{
  "success": true
} 
*/

  bool? success;

  PatientInfoResponseMeta({
    this.success,
  });
  PatientInfoResponseMeta.fromJson(Map<String, dynamic> json) {
    success = json['success'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    return data;
  }
}

class PatientInfoResponse {
/*
{
  "meta": {
    "success": true
  },
  "data": [
    {
      "fullName": "Đặng Tiểu Cường"
    }
  ]
} 
*/

  PatientInfoResponseMeta? meta;
  List<PatientInfoResponseData?>? data;

  PatientInfoResponse({
    this.meta,
    this.data,
  });
  PatientInfoResponse.fromJson(Map<String, dynamic> json) {
    meta = (json['meta'] != null)
        ? PatientInfoResponseMeta.fromJson(json['meta'])
        : null;
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <PatientInfoResponseData>[];
      v.forEach((v) {
        arr0.add(PatientInfoResponseData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (meta != null) {
      data['meta'] = meta!.toJson();
    }
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }
}
