import 'package:medical/src/modal/base/images.dart';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class PatientInfoResponseData {
/*
{
  "fullName": "Đặng Tiểu Cường",
  "referralCode": "Coach 0121345456",
  "referalDate": 1640323167,
  "nameOfAgency": "bv hong ngoc",
  "avatar": {
    "id": "4abea788-2dc0-4117-bc8d-08d9bee5a69c",
    "url": "https://localhost:44329/App/Image/4abea788-2dc0-4117-bc8d-08d9bee5a69c?expires=1640538464&signature=e055eabc23298af25a52f442014f1259fc4cda061ec0614d97c1bd7069073256"
    },
} 
*/

  String? fullName;
  String? referralCode;
  int? referalDate;
  String? nameOfAgency;
  ImagesModel? avatar;

  PatientInfoResponseData({
    this.fullName,
    this.referralCode,
    this.referalDate,
    this.nameOfAgency,
    this.avatar,
  });

  DateTime get sharedDate =>
      DateTime.fromMillisecondsSinceEpoch((referalDate ?? 0) * 1000);

  PatientInfoResponseData.fromJson(Map<String, dynamic> json) {
    fullName = json['fullName']?.toString();
    referralCode = json['referralCode']?.toString();
    referalDate = json['referalDate']?.toInt();
    nameOfAgency = json['nameOfAgency']?.toString();
    if (json['avatar'] != null) {
      avatar = ImagesModel.fromJson(json['avatar']);
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['fullName'] = fullName;
    data['referralCode'] = referralCode;
    data['referalDate'] = referalDate;
    data['nameOfAgency'] = nameOfAgency;
    data['avatar'] = avatar?.toJson();
    return data;
  }
}

class PatientInfoResponseMeta {
/*
{
  "success": true
} 
*/

  bool? success;

  PatientInfoResponseMeta({
    this.success,
  });
  PatientInfoResponseMeta.fromJson(Map<String, dynamic> json) {
    success = json['success'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    return data;
  }
}

class PatientInfoResponse {
/*
{
  "meta": {
    "success": true
  },
  "data": [
    {
      "fullName": "Đặng Tiểu Cường"
    }
  ]
} 
*/

  PatientInfoResponseMeta? meta;
  List<PatientInfoResponseData?>? data;

  PatientInfoResponse({
    this.meta,
    this.data,
  });
  PatientInfoResponse.fromJson(Map<String, dynamic> json) {
    meta = (json['meta'] != null)
        ? PatientInfoResponseMeta.fromJson(json['meta'])
        : null;
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <PatientInfoResponseData>[];
      v.forEach((v) {
        arr0.add(PatientInfoResponseData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (meta != null) {
      data['meta'] = meta!.toJson();
    }
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }
}
