///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class QuizLessonQuizQuizAnswers {
/*
{
  "name": "string",
  "isCorrect": true,
  "order": 0,
  "quizId": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
} 
*/

  String? name;
  bool? isCorrect;
  int? order;
  String? quizId;

  QuizLessonQuizQuizAnswers({
    this.name,
    this.isCorrect,
    this.order,
    this.quizId,
  });
  QuizLessonQuizQuizAnswers.fromJson(Map<String, dynamic> json) {
    name = json['name']?.toString();
    isCorrect = json['isCorrect'];
    order = json['order']?.toInt();
    quizId = json['quizId']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['name'] = name;
    data['isCorrect'] = isCorrect;
    data['order'] = order;
    data['quizId'] = quizId;
    return data;
  }
}

class QuizLessonQuiz {
/*
{
  "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "code": "string",
  "name": "string",
  "status": 0,
  "type": "string",
  "lessonLevel": "string",
  "lesson": "string",
  "quizAnswers": [
    {
      "name": "string",
      "isCorrect": true,
      "order": 0,
      "quizId": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
    }
  ]
} 
*/

  String? id;
  String? code;
  String? name;
  int? status;
  String? type;
  String? lessonLevel;
  String? lesson;
  String? explain;
  List<QuizLessonQuizQuizAnswers?>? quizAnswers;

  QuizLessonQuiz({
    this.id,
    this.code,
    this.name,
    this.status,
    this.type,
    this.lessonLevel,
    this.lesson,
    this.explain,
    this.quizAnswers,
  });
  QuizLessonQuiz.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    code = json['code']?.toString();
    name = json['name']?.toString();
    status = json['status']?.toInt();
    type = json['type']?.toString();
    lessonLevel = json['lessonLevel']?.toString();
    lesson = json['lesson']?.toString();
    explain = json['explain']?.toString();
    if (json['quizAnswers'] != null) {
      final v = json['quizAnswers'];
      final arr0 = <QuizLessonQuizQuizAnswers>[];
      v.forEach((v) {
        arr0.add(QuizLessonQuizQuizAnswers.fromJson(v));
      });
      quizAnswers = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['code'] = code;
    data['name'] = name;
    data['status'] = status;
    data['type'] = type;
    data['lessonLevel'] = lessonLevel;
    data['lesson'] = lesson;
    data['explain'] = explain;
    if (quizAnswers != null) {
      final v = quizAnswers;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['quizAnswers'] = arr0;
    }
    return data;
  }
}

class QuizLesson {
/*
{
  "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "quizId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "lessonSectionId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "quiz": {
    "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
    "code": "string",
    "name": "string",
    "status": 0,
    "type": "string",
    "lessonLevel": "string",
    "lesson": "string",
    "quizAnswers": [
      {
        "name": "string",
        "isCorrect": true,
        "order": 0,
        "quizId": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
      }
    ]
  }
} 
*/

  String? id;
  String? quizId;
  String? lessonSectionId;
  QuizLessonQuiz? quiz;

  QuizLesson({
    this.id,
    this.quizId,
    this.lessonSectionId,
    this.quiz,
  });

  List<QuizLessonQuizQuizAnswers?> get answers => this.quiz?.quizAnswers ?? [];

  String get type => this.quiz?.type ?? '';

  String get name => this.quiz?.name ?? '';

  QuizLesson.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    quizId = json['quizId']?.toString();
    lessonSectionId = json['lessonSectionId']?.toString();
    quiz =
        (json['quiz'] != null) ? QuizLessonQuiz.fromJson(json['quiz']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['quizId'] = quizId;
    data['lessonSectionId'] = lessonSectionId;
    if (quiz != null) {
      data['quiz'] = quiz!.toJson();
    }
    return data;
  }
}
