import 'package:medical/src/model/response/week_states_response.dart';
import 'package:medical/src/utils/utils.dart';
import 'package:medical/src/widget/my_plan_screens/my_plan/models/completion_status.dart';
import 'package:medical/src/widgets/day_in_week_widget.dart';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class DayStatesResponseData {
/*
{
  "day": 1638144000,
  "dayTitle": "T2",
  "state": 1
} 
*/

  int? day;
//  String? dayTitle;
  int? state;

  DayStatesResponseData({
    this.day,
 //   this.dayTitle,
    this.state,
  });

  CompletionStatus get completionStatus {
    if (state == 0) return CompletionStatus.not_completed;
    if (state == 1) return CompletionStatus.completed;
    if (state == 2) return CompletionStatus.studying;
    return CompletionStatus.not_start_yet;
  }

  DayStatesResponseData.fromJson(Map<String, dynamic> json) {
    day = json['day']?.toInt();
//    dayTitle = json['dayTitle']?.toString();
    state = json['state']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['day'] = day;
 //   data['dayTitle'] = dayTitle;
    data['state'] = state;
    return data;
  }
}

class SmartGoalStatisticResponseData {
/*
{
  "weeks": [
    {
      "week": 1,
      "weekTitle": "Tuần 1",
      "state": 1
    }
  ],
  "daysInCurrentWeek": [
    {
      "day": 1638144000,
      "dayTitle": "T2",
      "state": 1
    }
  ]
} 
*/

  List<WeekStatesResponseData?>? weeks;
  List<DayStatesResponseData?>? daysInCurrentWeek;

  SmartGoalStatisticResponseData({
    this.weeks,
    this.daysInCurrentWeek,
  });

  List<DayInWeekData> get dayInWeekList {
    if (daysInCurrentWeek?.isNotEmpty != true) return [];
    final List<DayInWeekData> dayInWeekList = [];
    int dayIndex = 7;
    for (int index = (daysInCurrentWeek?.length ?? 0) - 1; index >= 0; index--) {
      if (dayIndex - 1 >= 0) {
        dayIndex -= 1;
      } else {
        dayIndex = 6;
      }
      dayInWeekList.insert(
        0,
        DayInWeekData(
          title: Utils.getDayInWeekTitle(dayIndex),
          dayStatus: daysInCurrentWeek?[index]?.completionStatus ?? CompletionStatus.not_start_yet,
          dateTime: daysInCurrentWeek?[index]?.day,
        ),
      );
    }
    return dayInWeekList;
  }

  int get initDayIndex {
    for (int index = 0; index < (daysInCurrentWeek?.length ?? 0); index++) {
      if (daysInCurrentWeek?[index]?.completionStatus == CompletionStatus.studying) {
        return index;
      }
    }
    return 0;
  }

  int getCompletedMarkIndex({required int? currentWeek, required int? userCurrentWeek}) {
    if (currentWeek == null || userCurrentWeek == null) return 0;
    if (currentWeek < userCurrentWeek) return 14;
    if (currentWeek > userCurrentWeek) return 0;
    return initDayIndex;
  }

  SmartGoalStatisticResponseData.fromJson(Map<String, dynamic> json) {
    if (json['weeks'] != null) {
      final v = json['weeks'];
      final arr0 = <WeekStatesResponseData>[];
      v.forEach((v) {
        arr0.add(WeekStatesResponseData.fromJson(v));
      });
      weeks = arr0;
    }
    if (json['daysInCurrentWeek'] != null) {
      final v = json['daysInCurrentWeek'];
      final arr0 = <DayStatesResponseData>[];
      v.forEach((v) {
        arr0.add(DayStatesResponseData.fromJson(v));
      });
      daysInCurrentWeek = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (weeks != null) {
      final v = weeks;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['weeks'] = arr0;
    }
    if (daysInCurrentWeek != null) {
      final v = daysInCurrentWeek;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['daysInCurrentWeek'] = arr0;
    }
    return data;
  }
}

class SmartGoalStatisticResponseMeta {
/*
{
  "success": true
} 
*/

  bool? success;

  SmartGoalStatisticResponseMeta({
    this.success,
  });
  SmartGoalStatisticResponseMeta.fromJson(Map<String, dynamic> json) {
    success = json['success'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    return data;
  }
}

class SmartGoalStatisticResponse {
/*
{
  "meta": {
    "success": true
  },
  "data": {
    "weeks": [
      {
        "week": 1,
        "weekTitle": "Tuần 1",
        "state": 1
      }
    ],
    "daysInCurrentWeek": [
      {
        "day": 1638144000,
        "dayTitle": "T2",
        "state": 1
      }
    ]
  }
} 
*/

  SmartGoalStatisticResponseMeta? meta;
  SmartGoalStatisticResponseData? data;

  SmartGoalStatisticResponse({
    this.meta,
    this.data,
  });

  int get initDayIndex {
    for (int index = 0; index < (data?.daysInCurrentWeek?.length ?? 0); index++) {
      if (data?.daysInCurrentWeek?[index]?.completionStatus == CompletionStatus.studying) {
        return index;
      }
    }
    return 0;
  }

  int getCompletedMarkIndex({required int? currentWeek, required int? userCurrentWeek}) {
    if (currentWeek == null || userCurrentWeek == null) return 0;
    if (currentWeek < userCurrentWeek) return 14;
    if (currentWeek > userCurrentWeek) return 0;
    return initDayIndex;
  }

  SmartGoalStatisticResponse.fromJson(Map<String, dynamic> json) {
    meta = (json['meta'] != null) ? SmartGoalStatisticResponseMeta.fromJson(json['meta']) : null;
    data = (json['data'] != null) ? SmartGoalStatisticResponseData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (meta != null) {
      data['meta'] = meta!.toJson();
    }
    if (this.data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
