///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class SmartGoalListReponseDataDailyTargetSchedulerTargetSchedulerWeeks {
/*
{
  "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "dayInWeek": 0,
  "targetSchedulerId": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
} 
*/

  String? id;
  int? dayInWeek;
  String? targetSchedulerId;

  SmartGoalListReponseDataDailyTargetSchedulerTargetSchedulerWeeks({
    this.id,
    this.dayInWeek,
    this.targetSchedulerId,
  });
  SmartGoalListReponseDataDailyTargetSchedulerTargetSchedulerWeeks.fromJson(
      Map<String, dynamic> json) {
    id = json['id']?.toString();
    dayInWeek = json['dayInWeek']?.toInt();
    targetSchedulerId = json['targetSchedulerId']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['dayInWeek'] = dayInWeek;
    data['targetSchedulerId'] = targetSchedulerId;
    return data;
  }
}

class SmartGoalListReponseDataDailyTargetScheduler {
/*
{
  "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "repeatTime": 0,
  "repeatType": 0,
  "endDate": 0,
  "targetSchedulerWeeks": [
    {
      "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "dayInWeek": 0,
      "targetSchedulerId": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
    }
  ]
} 
*/

  String? id;
  int? repeatTime;
  int? repeatType;
  int? endDate;
  List<SmartGoalListReponseDataDailyTargetSchedulerTargetSchedulerWeeks?>?
      targetSchedulerWeeks;

  SmartGoalListReponseDataDailyTargetScheduler({
    this.id,
    this.repeatTime,
    this.repeatType,
    this.endDate,
    this.targetSchedulerWeeks,
  });
  SmartGoalListReponseDataDailyTargetScheduler.fromJson(
      Map<String, dynamic> json) {
    id = json['id']?.toString();
    repeatTime = json['repeatTime']?.toInt();
    repeatType = json['repeatType']?.toInt();
    endDate = json['endDate']?.toInt();
    if (json['targetSchedulerWeeks'] != null) {
      final v = json['targetSchedulerWeeks'];
      final arr0 =
          <SmartGoalListReponseDataDailyTargetSchedulerTargetSchedulerWeeks>[];
      v.forEach((v) {
        arr0.add(
            SmartGoalListReponseDataDailyTargetSchedulerTargetSchedulerWeeks
                .fromJson(v));
      });
      targetSchedulerWeeks = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['repeatTime'] = repeatTime;
    data['repeatType'] = repeatType;
    data['endDate'] = endDate;
    if (targetSchedulerWeeks != null) {
      final v = targetSchedulerWeeks;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['targetSchedulerWeeks'] = arr0;
    }
    return data;
  }
}

class SmartGoalList {
/*
{
  "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "name": "string",
  "type": 0,
  "appointmentDate": 0,
  "targetSchedulerId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "executeType": 0,
  "executeDayTimes": 0,
  "actualExecuteDayTimes": 0,
  "description": "string",
  "targetScheduler": {
    "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
    "repeatTime": 0,
    "repeatType": 0,
    "endDate": 0,
    "targetSchedulerWeeks": [
      {
        "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
        "dayInWeek": 0,
        "targetSchedulerId": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
      }
    ]
  }
} 
*/

  String? id;
  String? name;
  int? type;
  int? appointmentDate;
  String? targetSchedulerId;
  int? executeType;
  int? executeDayTimes;
  int? actualExecuteDayTimes;
  String? description;
  SmartGoalListReponseDataDailyTargetScheduler? targetScheduler;

  SmartGoalList({
    this.id,
    this.name,
    this.type,
    this.appointmentDate,
    this.targetSchedulerId,
    this.executeType,
    this.executeDayTimes,
    this.actualExecuteDayTimes,
    this.description,
    this.targetScheduler,
  });

  double get progress {
    if (actualExecuteDayTimes == null) return 0;
    if (executeDayTimes == null || executeDayTimes == 0) return 1;
    final double progress = actualExecuteDayTimes! / executeDayTimes!;
    if (progress < 0) return 0;
    if (progress > 1) return 1;
    return progress;
  }

  bool get isCompleted => progress >= 1;

  SmartGoalList.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    name = json['name']?.toString();
    type = json['type']?.toInt();
    appointmentDate = json['appointmentDate']?.toInt();
    targetSchedulerId = json['targetSchedulerId']?.toString();
    executeType = json['executeType']?.toInt();
    executeDayTimes = json['executeDayTimes']?.toInt();
    actualExecuteDayTimes = json['actualExecuteDayTimes']?.toInt();
    description = json['description']?.toString();
    targetScheduler = (json['targetScheduler'] != null)
        ? SmartGoalListReponseDataDailyTargetScheduler.fromJson(
            json['targetScheduler'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['type'] = type;
    data['appointmentDate'] = appointmentDate;
    data['targetSchedulerId'] = targetSchedulerId;
    data['executeType'] = executeType;
    data['executeDayTimes'] = executeDayTimes;
    data['actualExecuteDayTimes'] = actualExecuteDayTimes;
    data['description'] = description;
    if (targetScheduler != null) {
      data['targetScheduler'] = targetScheduler!.toJson();
    }
    return data;
  }
}

class SmartGoalListReponseData {
/*
{
  "daily": [
    {
      "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "name": "string",
      "type": 0,
      "appointmentDate": 0,
      "targetSchedulerId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "executeType": 0,
      "executeDayTimes": 0,
      "actualExecuteDayTimes": 0,
      "description": "string",
      "targetScheduler": {
        "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
        "repeatTime": 0,
        "repeatType": 0,
        "endDate": 0,
        "targetSchedulerWeeks": [
          {
            "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
            "dayInWeek": 0,
            "targetSchedulerId": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
          }
        ]
      }
    }
  ],
  "weekly": [
    {
      "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "name": "string",
      "type": 0,
      "appointmentDate": 0,
      "targetSchedulerId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "executeType": 0,
      "executeDayTimes": 0,
      "actualExecuteDayTimes": 0,
      "description": "string",
      "targetScheduler": {
        "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
        "repeatTime": 0,
        "repeatType": 0,
        "endDate": 0,
        "targetSchedulerWeeks": [
          {
            "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
            "dayInWeek": 0,
            "targetSchedulerId": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
          }
        ]
      }
    }
  ]
} 
*/

  List<SmartGoalList?>? daily;
  List<SmartGoalList?>? weekly;

  SmartGoalListReponseData({
    this.daily,
    this.weekly,
  });
  SmartGoalListReponseData.fromJson(Map<String, dynamic> json) {
    if (json['daily'] != null) {
      final v = json['daily'];
      final arr0 = <SmartGoalList>[];
      v.forEach((v) {
        arr0.add(SmartGoalList.fromJson(v));
      });
      daily = arr0;
    }
    if (json['weekly'] != null) {
      final v = json['weekly'];
      final arr0 = <SmartGoalList>[];
      v.forEach((v) {
        arr0.add(SmartGoalList.fromJson(v));
      });
      weekly = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (daily != null) {
      final v = daily;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['daily'] = arr0;
    }
    if (weekly != null) {
      final v = weekly;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['weekly'] = arr0;
    }
    return data;
  }
}

class SmartGoalListReponseMeta {
/*
{
  "success": true
} 
*/

  bool? success;

  SmartGoalListReponseMeta({
    this.success,
  });
  SmartGoalListReponseMeta.fromJson(Map<String, dynamic> json) {
    success = json['success'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    return data;
  }
}

class SmartGoalListReponse {
/*
{
  "meta": {
    "success": true
  },
  "data": {
    "daily": [
      {
        "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
        "name": "string",
        "type": 0,
        "appointmentDate": 0,
        "targetSchedulerId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
        "executeType": 0,
        "executeDayTimes": 0,
        "actualExecuteDayTimes": 0,
        "description": "string",
        "targetScheduler": {
          "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
          "repeatTime": 0,
          "repeatType": 0,
          "endDate": 0,
          "targetSchedulerWeeks": [
            {
              "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
              "dayInWeek": 0,
              "targetSchedulerId": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
            }
          ]
        }
      }
    ],
    "weekly": [
      {
        "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
        "name": "string",
        "type": 0,
        "appointmentDate": 0,
        "targetSchedulerId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
        "executeType": 0,
        "executeDayTimes": 0,
        "actualExecuteDayTimes": 0,
        "description": "string",
        "targetScheduler": {
          "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
          "repeatTime": 0,
          "repeatType": 0,
          "endDate": 0,
          "targetSchedulerWeeks": [
            {
              "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
              "dayInWeek": 0,
              "targetSchedulerId": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
            }
          ]
        }
      }
    ]
  }
} 
*/

  SmartGoalListReponseMeta? meta;
  SmartGoalListReponseData? data;

  SmartGoalListReponse({
    this.meta,
    this.data,
  });

  bool get isWeeklyGoalCompleted {
    for(final SmartGoalList? data in data?.weekly ?? []) {
      if (data?.progress != 1) return false; 
    }
    return true;
  }

  bool get isDailyGoalCompleted {
    for(final SmartGoalList? data in data?.daily ?? []) {
      if (data?.progress != 1) return false; 
    }
    return true;
  }

  SmartGoalListReponse.fromJson(Map<String, dynamic> json) {
    meta = (json['meta'] != null)
        ? SmartGoalListReponseMeta.fromJson(json['meta'])
        : null;
    data = (json['data'] != null)
        ? SmartGoalListReponseData.fromJson(json['data'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (meta != null) {
      data['meta'] = meta!.toJson();
    }
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
