///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class SmartGoalStatisticResponseDataWeeks {
/*
{
  "week": 0,
  "weekTitle": "string",
  "state": 0
} 
*/

  int? week;
  String? weekTitle;
  int? state;

  SmartGoalStatisticResponseDataWeeks({
    this.week,
    this.weekTitle,
    this.state,
  });
  SmartGoalStatisticResponseDataWeeks.fromJson(Map<String, dynamic> json) {
    week = json['week']?.toInt();
    weekTitle = json['weekTitle']?.toString();
    state = json['state']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['week'] = week;
    data['weekTitle'] = weekTitle;
    data['state'] = state;
    return data;
  }
}

class SmartGoalStatisticResponseData {
/*
{
  "weeks": [
    {
      "week": 0,
      "weekTitle": "string",
      "state": 0
    }
  ],
  "daysInCurrentWeek": [
    0
  ]
} 
*/

  List<SmartGoalStatisticResponseDataWeeks?>? weeks;
  List<int?>? daysInCurrentWeek;

  SmartGoalStatisticResponseData({
    this.weeks,
    this.daysInCurrentWeek,
  });
  SmartGoalStatisticResponseData.fromJson(Map<String, dynamic> json) {
    if (json['weeks'] != null) {
      final v = json['weeks'];
      final arr0 = <SmartGoalStatisticResponseDataWeeks>[];
      v.forEach((v) {
        arr0.add(SmartGoalStatisticResponseDataWeeks.fromJson(v));
      });
      weeks = arr0;
    }
    if (json['daysInCurrentWeek'] != null) {
      final v = json['daysInCurrentWeek'];
      final arr0 = <int>[];
      v.forEach((v) {
        arr0.add(v.toInt());
      });
      daysInCurrentWeek = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (weeks != null) {
      final v = weeks;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['weeks'] = arr0;
    }
    if (daysInCurrentWeek != null) {
      final v = daysInCurrentWeek;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['daysInCurrentWeek'] = arr0;
    }
    return data;
  }
}

class SmartGoalStatisticResponseMeta {
/*
{
  "success": true
} 
*/

  bool? success;

  SmartGoalStatisticResponseMeta({
    this.success,
  });
  SmartGoalStatisticResponseMeta.fromJson(Map<String, dynamic> json) {
    success = json['success'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    return data;
  }
}

class SmartGoalStatisticResponse {
/*
{
  "meta": {
    "success": true
  },
  "data": {
    "weeks": [
      {
        "week": 0,
        "weekTitle": "string",
        "state": 0
      }
    ],
    "daysInCurrentWeek": [
      0
    ]
  }
} 
*/

  SmartGoalStatisticResponseMeta? meta;
  SmartGoalStatisticResponseData? data;

  SmartGoalStatisticResponse({
    this.meta,
    this.data,
  });
  SmartGoalStatisticResponse.fromJson(Map<String, dynamic> json) {
    meta = (json['meta'] != null)
        ? SmartGoalStatisticResponseMeta.fromJson(json['meta'])
        : null;
    data = (json['data'] != null)
        ? SmartGoalStatisticResponseData.fromJson(json['data'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (meta != null) {
      data['meta'] = meta!.toJson();
    }
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
