import 'package:medical/src/widget/my_plan_screens/activity_tab/activity_tab/models/schedule_type.dart';
import 'package:medical/src/widget/my_plan_screens/activity_tab/create_goal/models/day_in_week.dart';
import 'package:medical/src/widget/my_plan_screens/activity_tab/create_goal/models/goal_record_type.dart';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class SmartGoalListReponseDataTargetSchedulerTargetSchedulerWeeks {
/*
{
  "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "dayInWeek": 0,
  "targetSchedulerId": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
} 
*/

  String? id;
  int? dayInWeek;
  String? targetSchedulerId;

  SmartGoalListReponseDataTargetSchedulerTargetSchedulerWeeks({
    this.id,
    this.dayInWeek,
    this.targetSchedulerId,
  });
  SmartGoalListReponseDataTargetSchedulerTargetSchedulerWeeks.fromJson(
      Map<String, dynamic> json) {
    id = json['id']?.toString();
    dayInWeek = json['dayInWeek']?.toInt();
    targetSchedulerId = json['targetSchedulerId']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['dayInWeek'] = dayInWeek;
    data['targetSchedulerId'] = targetSchedulerId;
    return data;
  }
}

class SmartGoalListReponseDataTargetScheduler {
/*
{
  "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "repeatTime": 0,
  "repeatType": 0,
  "endDate": 0,
  "targetSchedulerWeeks": [
    {
      "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "dayInWeek": 0,
      "targetSchedulerId": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
    }
  ]
} 
*/

  String? id;
  int? repeatTime;
  int? repeatType;
  int? endDate;
  List<SmartGoalListReponseDataTargetSchedulerTargetSchedulerWeeks?>?
      targetSchedulerWeeks;

  SmartGoalListReponseDataTargetScheduler({
    this.id,
    this.repeatTime,
    this.repeatType,
    this.endDate,
    this.targetSchedulerWeeks,
  });

  SmartGoalListReponseDataTargetScheduler.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    repeatTime = json['repeatTime']?.toInt();
    repeatType = json['repeatType']?.toInt();
    endDate = json['endDate']?.toInt();
    if (json['targetSchedulerWeeks'] != null) {
      final v = json['targetSchedulerWeeks'];
      final arr0 =
          <SmartGoalListReponseDataTargetSchedulerTargetSchedulerWeeks>[];
      v.forEach((v) {
        arr0.add(SmartGoalListReponseDataTargetSchedulerTargetSchedulerWeeks
            .fromJson(v));
      });
      targetSchedulerWeeks = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['repeatTime'] = repeatTime;
    data['repeatType'] = repeatType;
    data['endDate'] = endDate;
    if (targetSchedulerWeeks != null) {
      final v = targetSchedulerWeeks;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['targetSchedulerWeeks'] = arr0;
    }
    return data;
  }
}

class SmartGoalListReponseData {
/*
{
  "id": "c51a41a8-1a0f-4acd-1122-08d9b4995a82",
  "name": "Mục tiêu mới 1",
  "type": 1,
  "appointmentDate": 1638757009,
  "targetSchedulerId": "17159898-e55f-4fd2-14d9-08d9b4995a6e",
  "executeType": 1,
  "executeDayTimes": 3,
  "actualExecuteDayTimes": 0,
  "targetScheduler": {
    "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
    "repeatTime": 0,
    "repeatType": 0,
    "endDate": 0,
    "targetSchedulerWeeks": [
      {
        "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
        "dayInWeek": 0,
        "targetSchedulerId": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
      }
    ]
  }
} 
*/

  String? id;
  String? name;
  int? type;
  int? appointmentDate;
  String? targetSchedulerId;
  int? executeType;
  int? executeDayTimes;
  int? actualExecuteDayTimes;
  SmartGoalListReponseDataTargetScheduler? targetScheduler;

  List<DayInWeek> get repeatDayList =>
      targetScheduler?.targetSchedulerWeeks
          ?.map((day) => DayInWeekExtend.getDayInWeekFromIndex(day?.dayInWeek))
          .toList() ??
      [];

  double get progress {
    if (actualExecuteDayTimes == null) return 0;
    if (executeDayTimes == null || executeDayTimes == 0) return 1;
    final double progress = actualExecuteDayTimes! / executeDayTimes!;
    if (progress < 0) return 0;
    if (progress > 1) return 1;
    return progress;
  }

  bool get isCompleted => progress >= 1;

  ScheduleType get goalType => ScheduleTypeExtend.getTypeFromIndex(type);

  DateTime? get startDate => appointmentDate == null
      ? null
      : DateTime.fromMillisecondsSinceEpoch(appointmentDate! * 1000);

  GoalRecordType get goalRecordType => executeType == null
      ? GoalRecordType.time
      : GoalRecordTypeExtend.getGoalRecordTypeFromIndex(executeType!);

  SmartGoalListReponseData({
    this.id,
    this.name,
    this.type,
    this.appointmentDate,
    this.targetSchedulerId,
    this.executeType,
    this.executeDayTimes,
    this.actualExecuteDayTimes,
    this.targetScheduler,
  });
  SmartGoalListReponseData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    name = json['name']?.toString();
    type = json['type']?.toInt();
    appointmentDate = json['appointmentDate']?.toInt();
    targetSchedulerId = json['targetSchedulerId']?.toString();
    executeType = json['executeType']?.toInt();
    executeDayTimes = json['executeDayTimes']?.toInt();
    actualExecuteDayTimes = json['actualExecuteDayTimes']?.toInt();
    targetScheduler = (json['targetScheduler'] != null)
        ? SmartGoalListReponseDataTargetScheduler.fromJson(
            json['targetScheduler'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['type'] = type;
    data['appointmentDate'] = appointmentDate;
    data['targetSchedulerId'] = targetSchedulerId;
    data['executeType'] = executeType;
    data['executeDayTimes'] = executeDayTimes;
    data['actualExecuteDayTimes'] = actualExecuteDayTimes;
    if (targetScheduler != null) {
      data['targetScheduler'] = targetScheduler!.toJson();
    }
    return data;
  }
}

class SmartGoalListReponseMeta {
/*
{
  "success": true
} 
*/

  bool? success;

  SmartGoalListReponseMeta({
    this.success,
  });
  SmartGoalListReponseMeta.fromJson(Map<String, dynamic> json) {
    success = json['success'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    return data;
  }
}

class SmartGoalListReponse {
/*
{
  "meta": {
    "success": true
  },
  "data": [
    {
      "id": "c51a41a8-1a0f-4acd-1122-08d9b4995a82",
      "name": "Mục tiêu mới 1",
      "type": 1,
      "appointmentDate": 1638757009,
      "targetSchedulerId": "17159898-e55f-4fd2-14d9-08d9b4995a6e",
      "executeType": 1,
      "executeDayTimes": 3,
      "actualExecuteDayTimes": 0,
      "targetScheduler": {
        "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
        "repeatTime": 0,
        "repeatType": 0,
        "endDate": 0,
        "targetSchedulerWeeks": [
          {
            "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
            "dayInWeek": 0,
            "targetSchedulerId": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
          }
        ]
      }
    }
  ]
} 
*/

  SmartGoalListReponseMeta? meta;
  List<SmartGoalListReponseData?>? data;

  SmartGoalListReponse({
    this.meta,
    this.data,
  });

  double get progressOfDay {
    if (data?.isNotEmpty != true) return 0; 
    double progressOfDay = 0;
    for (final SmartGoalListReponseData? smartGoal in data ?? []) {
      progressOfDay += smartGoal?.progress ?? 0;
    }
    return progressOfDay / (data?.length.toDouble() ?? 1);
  }

  SmartGoalListReponse.fromJson(Map<String, dynamic> json) {
    meta = (json['meta'] != null)
        ? SmartGoalListReponseMeta.fromJson(json['meta'])
        : null;
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <SmartGoalListReponseData>[];
      v.forEach((v) {
        arr0.add(SmartGoalListReponseData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (meta != null) {
      data['meta'] = meta!.toJson();
    }
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }
}
