import 'package:medical/src/model/response/exercise_movement_target.dart';
import 'package:medical/src/model/response/survey_target.dart';
import 'package:medical/src/widget/my_plan_screens/activity_tab/activity_tab/models/schedule_type.dart';
import 'package:medical/src/widget/my_plan_screens/activity_tab/create_goal/models/day_in_week.dart';

import 'calendar_target.dart';
import 'exercise_movement_response.dart';
import 'lesson_section_list_response.dart';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class RepeatDayData {
/*
{
  "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "dayInWeek": 0,
  "targetSchedulerId": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
} 
*/

  String? id;
  int? dayInWeek;
  String? targetSchedulerId;

  RepeatDayData({
    this.id,
    this.dayInWeek,
    this.targetSchedulerId,
  });
  RepeatDayData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    dayInWeek = json['dayInWeek']?.toInt();
    targetSchedulerId = json['targetSchedulerId']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['dayInWeek'] = dayInWeek;
    data['targetSchedulerId'] = targetSchedulerId;
    return data;
  }
}

class SmartGoalListReponseDataDailyTargetScheduler {
/*
{
  "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "repeatTime": 0,
  "repeatType": 0,
  "endDate": 0,
  "targetSchedulerWeeks": [
    {
      "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "dayInWeek": 0,
      "targetSchedulerId": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
    }
  ]
} 
*/

  String? id;
  int? repeatTime;
  int? repeatType;
  int? endDate;
  List<RepeatDayData?>? targetSchedulerWeeks;

  SmartGoalListReponseDataDailyTargetScheduler({
    this.id,
    this.repeatTime,
    this.repeatType,
    this.endDate,
    this.targetSchedulerWeeks,
  });

  List<DayInWeek> get repeatDayList {
    if (targetSchedulerWeeks?.isNotEmpty != true) return [];
    final List<DayInWeek> repeatDayList = [];
    for (final RepeatDayData? day in targetSchedulerWeeks ?? []) {
      if (day?.dayInWeek != null) {
        repeatDayList
            .add(DayInWeekExtend.getDayInWeekFromIndex(day?.dayInWeek));
      }
    }
    return repeatDayList;
  }

  SmartGoalListReponseDataDailyTargetScheduler.fromJson(
      Map<String, dynamic> json) {
    id = json['id']?.toString();
    repeatTime = json['repeatTime']?.toInt();
    repeatType = json['repeatType']?.toInt();
    endDate = json['endDate']?.toInt();
    if (json['targetSchedulerWeeks'] != null) {
      final v = json['targetSchedulerWeeks'];
      final arr0 = <RepeatDayData>[];
      v.forEach((v) {
        arr0.add(RepeatDayData.fromJson(v));
      });
      targetSchedulerWeeks = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['repeatTime'] = repeatTime;
    data['repeatType'] = repeatType;
    data['endDate'] = endDate;
    if (targetSchedulerWeeks != null) {
      final v = targetSchedulerWeeks;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['targetSchedulerWeeks'] = arr0;
    }
    return data;
  }
}

class SmartGoalList {
/*
{
  "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "name": "string",
  "type": 0,
  "appointmentDate": 0,
  "targetSchedulerId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "executeType": 0,
  "executeDayTimes": 0,
  "actualExecuteDayTimes": 0,
  "description": "string",
  "targetScheduler": {
    "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
    "repeatTime": 0,
    "repeatType": 0,
    "endDate": 0,
    "targetSchedulerWeeks": [
      {
        "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
        "dayInWeek": 0,
        "targetSchedulerId": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
      }
    ]
  }
} 
*/

  String? id;
  String? name;
  int? type;
  int? appointmentDate;
  String? targetSchedulerId;
  int? executeType;
  int? executeDayTimes;
  int? actualExecuteDayTimes;
  String? description;
  String? surveyId;
  String? calendarId;
  int? state;
  dynamic data;
  SmartGoalListReponseDataDailyTargetScheduler? targetScheduler;
  ExerciseMovementTarget? exerciseMovement;
  SurveyTarget? survey;
  CalendarTarget? calendar;

  SmartGoalList({
    this.id,
    this.name,
    this.type,
    this.appointmentDate,
    this.targetSchedulerId,
    this.executeType,
    this.executeDayTimes,
    this.actualExecuteDayTimes,
    this.description,
    this.surveyId,
    this.calendarId,
    this.state,
    this.data,
    this.targetScheduler,
    this.calendar,
  });

  double get progress {
    if(state == 1) return 1;
    return 0;
    // if (actualExecuteDayTimes == null) return 0;
    // if (executeDayTimes == null || executeDayTimes == 0) return 1;
    // final double progress = actualExecuteDayTimes! / executeDayTimes!;
    // if (progress < 0) return 0;
    // if (progress > 1) return 1;
    // return progress;
  }

  bool get isCompleted => progress >= 1;

  ExerciseMovementResponseData? get exerciseData =>
      data is ExerciseMovementResponseData
          ? data as ExerciseMovementResponseData
          : null;

  LessonSectionListResponseData? get lessonData =>
      data is LessonSectionListResponseData
          ? data as LessonSectionListResponseData
          : null;

  SmartGoalList.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    name = json['name']?.toString();
    type = json['type']?.toInt();
    appointmentDate = json['appointmentDate']?.toInt();
    targetSchedulerId = json['targetSchedulerId']?.toString();
    executeType = json['executeType']?.toInt();
    executeDayTimes = json['executeDayTimes']?.toInt();
    actualExecuteDayTimes = json['actualExecuteDayTimes']?.toInt();
    description = json['description']?.toString();
    state = json['state']?.toInt();
    surveyId = json['surveyId']?.toString();
    calendarId = json['calendarId']?.toString();
    if (json['data'] != null &&
        type == ScheduleType.exercise_movement.typeIndex) {
      data = ExerciseMovementResponseData.fromJson(json['data']);
    }
    if (json['data'] != null && type == ScheduleType.lesson.typeIndex) {
      data = LessonSectionListResponseData.fromJson(json['data']);
    }
    targetScheduler = (json['targetScheduler'] != null)
        ? SmartGoalListReponseDataDailyTargetScheduler.fromJson(
            json['targetScheduler'])
        : null;
    calendar = (json['calendar'] != null)
        ? CalendarTarget.fromJson(
            json['calendar'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['type'] = type;
    data['appointmentDate'] = appointmentDate;
    data['targetSchedulerId'] = targetSchedulerId;
    data['executeType'] = executeType;
    data['executeDayTimes'] = executeDayTimes;
    data['actualExecuteDayTimes'] = actualExecuteDayTimes;
    data['description'] = description;
    data['surveyId'] = surveyId;
    data['calendarId'] = calendarId;
    data['state'] = state;
    data['data'] = data.toString();
    if (targetScheduler != null) {
      data['targetScheduler'] = targetScheduler!.toJson();
    }
    if (calendar != null) {
      data['calendar'] = calendar!.toJson();
    }
    return data;
  }
}

class SmartGoalListReponseData {
/*
{
  "daily": [
    {
      "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "name": "string",
      "type": 0,
      "appointmentDate": 0,
      "targetSchedulerId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "executeType": 0,
      "executeDayTimes": 0,
      "actualExecuteDayTimes": 0,
      "description": "string",
      "targetScheduler": {
        "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
        "repeatTime": 0,
        "repeatType": 0,
        "endDate": 0,
        "targetSchedulerWeeks": [
          {
            "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
            "dayInWeek": 0,
            "targetSchedulerId": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
          }
        ]
      }
    }
  ],
  "weekly": [
    {
      "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "name": "string",
      "type": 0,
      "appointmentDate": 0,
      "targetSchedulerId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "executeType": 0,
      "executeDayTimes": 0,
      "actualExecuteDayTimes": 0,
      "description": "string",
      "targetScheduler": {
        "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
        "repeatTime": 0,
        "repeatType": 0,
        "endDate": 0,
        "targetSchedulerWeeks": [
          {
            "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
            "dayInWeek": 0,
            "targetSchedulerId": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
          }
        ]
      }
    }
  ]
} 
*/

  List<SmartGoalList?>? daily;
  List<SmartGoalList?>? weekly;

  SmartGoalListReponseData({
    this.daily,
    this.weekly,
  });
  SmartGoalListReponseData.fromJson(Map<String, dynamic> json) {
    if (json['daily'] != null) {
      final v = json['daily'];
      final arr0 = <SmartGoalList>[];
      v.forEach((v) {
        arr0.add(SmartGoalList.fromJson(v));
      });
      daily = arr0;
    }
    if (json['weekly'] != null) {
      final v = json['weekly'];
      final arr0 = <SmartGoalList>[];
      v.forEach((v) {
        arr0.add(SmartGoalList.fromJson(v));
      });
      weekly = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (daily != null) {
      final v = daily;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['daily'] = arr0;
    }
    if (weekly != null) {
      final v = weekly;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['weekly'] = arr0;
    }
    return data;
  }
}

class SmartGoalListReponseMeta {
/*
{
  "success": true
} 
*/

  bool? success;

  SmartGoalListReponseMeta({
    this.success,
  });
  SmartGoalListReponseMeta.fromJson(Map<String, dynamic> json) {
    success = json['success'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    return data;
  }
}

class SmartGoalListReponse {
/*
{
  "meta": {
    "success": true
  },
  "data": {
    "daily": [
      {
        "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
        "name": "string",
        "type": 0,
        "appointmentDate": 0,
        "targetSchedulerId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
        "executeType": 0,
        "executeDayTimes": 0,
        "actualExecuteDayTimes": 0,
        "description": "string",
        "targetScheduler": {
          "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
          "repeatTime": 0,
          "repeatType": 0,
          "endDate": 0,
          "targetSchedulerWeeks": [
            {
              "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
              "dayInWeek": 0,
              "targetSchedulerId": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
            }
          ]
        }
      }
    ],
    "weekly": [
      {
        "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
        "name": "string",
        "type": 0,
        "appointmentDate": 0,
        "targetSchedulerId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
        "executeType": 0,
        "executeDayTimes": 0,
        "actualExecuteDayTimes": 0,
        "description": "string",
        "targetScheduler": {
          "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
          "repeatTime": 0,
          "repeatType": 0,
          "endDate": 0,
          "targetSchedulerWeeks": [
            {
              "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
              "dayInWeek": 0,
              "targetSchedulerId": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
            }
          ]
        }
      }
    ]
  }
} 
*/

  SmartGoalListReponseMeta? meta;
  SmartGoalListReponseData? data;

  SmartGoalListReponse({
    this.meta,
    this.data,
  });

  bool get isWeeklyGoalCompleted {
    if (data?.weekly?.isNotEmpty != true) return false;
    for (final SmartGoalList? data in data?.weekly ?? []) {
      if (data?.progress != 1) return false;
    }
    return true;
  }

  bool get isDailyGoalCompleted {
    if (data?.daily?.isNotEmpty != true) return false;
    for (final SmartGoalList? data in data?.daily ?? []) {
      if (data?.progress != 1) return false;
    }
    return true;
  }

  SmartGoalListReponse.fromJson(Map<String, dynamic> json) {
    meta = (json['meta'] != null)
        ? SmartGoalListReponseMeta.fromJson(json['meta'])
        : null;
    data = (json['data'] != null)
        ? SmartGoalListReponseData.fromJson(json['data'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (meta != null) {
      data['meta'] = meta!.toJson();
    }
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
