import 'smart_goal_list_reponse.dart';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///

class SmartGoalDetailResponseMeta {
/*
{
  "success": true
} 
*/

  bool? success;

  SmartGoalDetailResponseMeta({
    this.success,
  });
  SmartGoalDetailResponseMeta.fromJson(Map<String, dynamic> json) {
    success = json['success'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    return data;
  }
}

class SmartGoalDetailResponse {
/*
{
  "meta": {
    "success": true
  },
  "data": {
    "id": "6b6d30fd-4796-491a-02a6-08d9b4bab912",
    "name": "Hoạt động siêu mới 1",
    "type": 0,
    "appointmentDate": 1638356796,
    "targetSchedulerId": "e9d30b05-2bfd-4bcd-c109-08d9b4bab8fa",
    "executeType": 0,
    "executeDayTimes": 17,
    "actualExecuteDayTimes": 0,
    "targetScheduler": {
      "id": "e9d30b05-2bfd-4bcd-c109-08d9b4bab8fa",
      "repeatTime": 1,
      "repeatType": 1,
      "endDate": 1638378000,
      "targetSchedulerWeeks": [
        {
          "id": "36b71dc8-b380-4aed-54ef-08d9b4bab905",
          "dayInWeek": 0,
          "targetSchedulerId": "e9d30b05-2bfd-4bcd-c109-08d9b4bab8fa"
        }
      ]
    }
  }
} 
*/

  SmartGoalDetailResponseMeta? meta;
  SmartGoalListReponseData? data;

  SmartGoalDetailResponse({
    this.meta,
    this.data,
  });
  SmartGoalDetailResponse.fromJson(Map<String, dynamic> json) {
    meta = (json['meta'] != null)
        ? SmartGoalDetailResponseMeta.fromJson(json['meta'])
        : null;
    data = (json['data'] != null)
        ? SmartGoalListReponseData.fromJson(json['data'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (meta != null) {
      data['meta'] = meta!.toJson();
    }
    if (this.data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
