///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class UpdateLessonSectionResponse {
/*
{
  "id": "85053c2a-8e08-4216-55a0-08d994ff3042",
  "statusCode": 200,
  "message": "Success",
  "data": "85053c2a-8e08-4216-55a0-08d994ff3042"
} 
*/

  String? id;
  int? statusCode;
  String? message;
  String? data;

  UpdateLessonSectionResponse({
    this.id,
    this.statusCode,
    this.message,
    this.data,
  });
  UpdateLessonSectionResponse.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toString();
    statusCode = json["statusCode"]?.toInt();
    message = json["message"]?.toString();
    data = json["data"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["statusCode"] = statusCode;
    data["message"] = message;
    data["data"] = this.data;
    return data;
  }
}
