///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class UserPosition {
/*
{
  "id": "78b7338c-10ad-44c3-80fe-98fbe5c47211",
  "code": "Doctor",
  "name": "Bác sĩ"
} 
*/

  String? id;
  String? code;
  String? name;

  UserPosition({
    this.id,
    this.code,
    this.name,
  });
  UserPosition.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    code = json['code']?.toString();
    name = json['name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['code'] = code;
    data['name'] = name;
    return data;
  }
}

class UserPositionMappings {
/*
{
  "id": "08d77cb2-1d02-4ef8-31e2-08d9c5fa88cb",
  "accountId": "e3408df9-9d7a-4e3d-88b8-1fe22b809830",
  "positionId": "78b7338c-10ad-44c3-80fe-98fbe5c47211",
  "position": {
    "id": "78b7338c-10ad-44c3-80fe-98fbe5c47211",
    "code": "Doctor",
    "name": "Bác sĩ"
  }
} 
*/

  String? id;
  String? accountId;
  String? positionId;
  UserPosition? position;

  UserPositionMappings({
    this.id,
    this.accountId,
    this.positionId,
    this.position,
  });
  UserPositionMappings.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    accountId = json['accountId']?.toString();
    positionId = json['positionId']?.toString();
    position = (json['position'] != null) ? UserPosition.fromJson(json['position']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['accountId'] = accountId;
    data['positionId'] = positionId;
    if (position != null) {
      data['position'] = position!.toJson();
    }
    return data;
  }
}

class UserInfoReferralCodeResponseData {
/*
{
  "id": "e3408df9-9d7a-4e3d-88b8-1fe22b809830",
  "username": "0121345456",
  "fullName": "Đặng Tiểu Cường",
  "age": 39,
  "phoneNumber": "+84121345456",
  "secondPhoneNumber": null,
  "gender": 1,
  "createDatetime": 1640319108,
  "active": true,
  "nation": "Việt Nam",
  "province": "Bà Rịa Vũng Tàu",
  "district": "Huyện Long Điền",
  "ward": "Thị trấn Long Hải",
  "nationId": "2857c61e-d5d2-4a7c-810c-1e7ab9e25d86",
  "provinceId": "24e7a947-7783-4d8f-87e7-f94301fc0e89",
  "districtId": "47cbc6b3-2492-4c9d-8f9e-e05ba4d1f093",
  "wardId": "7bb46db9-d9b8-4491-a4e6-7d3d16945576",
  "avatar": null,
  "coverId": "66265ee4-d347-44a3-7e97-08d9c5f86f42",
  "updateDatetime": 1640319108,
  "creatorId": "00000000-0000-0500-0000-000000000000",
  "updaterId": "00000000-0000-0500-0000-000000000000",
  "email": "bacsithuy@gmeo.com",
  "dateOfBirth": 382294800,
  "address": "Láng Cát",
  "level": null,
  "typeOfWork": null,
  "facebookUrl": "facebook.com/dangtieucuong",
  "url": null,
  "introduction": "Đã có hơn 30 năm kinh nghiệm làm bác sĩ thú y",
  "code": "Coach 0121345456",
  "education": null,
  "managerId": null,
  "referralCode": "21iG90",
  "referalDate": null,
  "nameOfAgency": null,
  "manager": null,
  "accountRule": null,
  "accountRoles": null,
  "accountPositionMappings": [
    {
      "id": "08d77cb2-1d02-4ef8-31e2-08d9c5fa88cb",
      "accountId": "e3408df9-9d7a-4e3d-88b8-1fe22b809830",
      "positionId": "78b7338c-10ad-44c3-80fe-98fbe5c47211",
      "position": {
        "id": "78b7338c-10ad-44c3-80fe-98fbe5c47211",
        "code": "Doctor",
        "name": "Bác sĩ"
      }
    }
  ]
} 
*/

  String? id;
  String? username;
  String? fullName;
  int? age;
  String? phoneNumber;
  String? secondPhoneNumber;
  int? gender;
  int? createDatetime;
  bool? active;
  String? nation;
  String? province;
  String? district;
  String? ward;
  String? nationId;
  String? provinceId;
  String? districtId;
  String? wardId;
  String? avatar;
  String? coverId;
  int? updateDatetime;
  String? creatorId;
  String? updaterId;
  String? email;
  int? dateOfBirth;
  String? address;
  String? level;
  String? typeOfWork;
  String? facebookUrl;
  String? url;
  String? introduction;
  String? code;
  String? education;
  String? managerId;
  String? referralCode;
  String? referalDate;
  String? nameOfAgency;
  String? manager;
  String? accountRule;
  String? accountRoles;
  List<UserPositionMappings?>? accountPositionMappings;
  Avatar? creatorUrl;
  bool? hasShare;

  UserInfoReferralCodeResponseData({
    this.id,
    this.username,
    this.fullName,
    this.age,
    this.phoneNumber,
    this.secondPhoneNumber,
    this.gender,
    this.createDatetime,
    this.active,
    this.nation,
    this.province,
    this.district,
    this.ward,
    this.nationId,
    this.provinceId,
    this.districtId,
    this.wardId,
    this.avatar,
    this.coverId,
    this.updateDatetime,
    this.creatorId,
    this.updaterId,
    this.email,
    this.dateOfBirth,
    this.address,
    this.level,
    this.typeOfWork,
    this.facebookUrl,
    this.url,
    this.introduction,
    this.code,
    this.education,
    this.managerId,
    this.referralCode,
    this.referalDate,
    this.nameOfAgency,
    this.manager,
    this.accountRule,
    this.accountRoles,
    this.accountPositionMappings,
    this.creatorUrl,
    this.hasShare,
  });
  UserInfoReferralCodeResponseData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    username = json['username']?.toString();
    fullName = json['fullName']?.toString();
    age = json['age']?.toInt();
    phoneNumber = json['phoneNumber']?.toString();
    secondPhoneNumber = json['secondPhoneNumber']?.toString();
    gender = json['gender']?.toInt();
    createDatetime = json['createDatetime']?.toInt();
    active = json['active'];
    nation = json['nation']?.toString();
    province = json['province']?.toString();
    district = json['district']?.toString();
    ward = json['ward']?.toString();
    nationId = json['nationId']?.toString();
    provinceId = json['provinceId']?.toString();
    districtId = json['districtId']?.toString();
    wardId = json['wardId']?.toString();
    avatar = json['avatar']?.toString();
    coverId = json['coverId']?.toString();
    updateDatetime = json['updateDatetime']?.toInt();
    creatorId = json['creatorId']?.toString();
    updaterId = json['updaterId']?.toString();
    email = json['email']?.toString();
    dateOfBirth = json['dateOfBirth']?.toInt();
    address = json['address']?.toString();
    level = json['level']?.toString();
    typeOfWork = json['typeOfWork']?.toString();
    facebookUrl = json['facebookUrl']?.toString();
    url = json['url']?.toString();
    introduction = json['introduction']?.toString();
    code = json['code']?.toString();
    education = json['education']?.toString();
    managerId = json['managerId']?.toString();
    referralCode = json['referralCode']?.toString();
    referalDate = json['referalDate']?.toString();
    nameOfAgency = json['nameOfAgency']?.toString();
    manager = json['manager']?.toString();
    accountRule = json['accountRule']?.toString();
    accountRoles = json['accountRoles']?.toString();
    hasShare = json['hasShare'] ?? false;
    if (json['accountPositionMappings'] != null) {
      final v = json['accountPositionMappings'];
      final arr0 = <UserPositionMappings>[];
      v.forEach((v) {
        arr0.add(UserPositionMappings.fromJson(v));
      });
      accountPositionMappings = arr0;
    }
    creatorUrl = json['creatorUrl'] == null ? null : Avatar.fromJson(json['creatorUrl']);
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['username'] = username;
    data['fullName'] = fullName;
    data['age'] = age;
    data['phoneNumber'] = phoneNumber;
    data['secondPhoneNumber'] = secondPhoneNumber;
    data['gender'] = gender;
    data['createDatetime'] = createDatetime;
    data['active'] = active;
    data['nation'] = nation;
    data['province'] = province;
    data['district'] = district;
    data['ward'] = ward;
    data['nationId'] = nationId;
    data['provinceId'] = provinceId;
    data['districtId'] = districtId;
    data['wardId'] = wardId;
    data['avatar'] = avatar;
    data['coverId'] = coverId;
    data['updateDatetime'] = updateDatetime;
    data['creatorId'] = creatorId;
    data['updaterId'] = updaterId;
    data['email'] = email;
    data['dateOfBirth'] = dateOfBirth;
    data['address'] = address;
    data['level'] = level;
    data['typeOfWork'] = typeOfWork;
    data['facebookUrl'] = facebookUrl;
    data['url'] = url;
    data['introduction'] = introduction;
    data['code'] = code;
    data['hasShare'] = hasShare;
    data['education'] = education;
    data['managerId'] = managerId;
    data['referralCode'] = referralCode;
    data['referalDate'] = referalDate;
    data['nameOfAgency'] = nameOfAgency;
    data['manager'] = manager;
    data['accountRule'] = accountRule;
    data['accountRoles'] = accountRoles;
    if (accountPositionMappings != null) {
      final v = accountPositionMappings;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['accountPositionMappings'] = arr0;
    }
    if (creatorUrl != null) {
      data['creatorUrl'] = creatorUrl!.toJson();
    }

    return data;
  }
}

class UserInfoReferralCodeResponseMeta {
/*
{
  "success": true
} 
*/

  bool? success;

  UserInfoReferralCodeResponseMeta({
    this.success,
  });
  UserInfoReferralCodeResponseMeta.fromJson(Map<String, dynamic> json) {
    success = json['success'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    return data;
  }
}

class Avatar {
  Avatar({
    this.id,
    this.url,
  });

  String? id;
  String? url;

  factory Avatar.fromJson(Map<String, dynamic> json) => Avatar(
        id: json["id"],
        url: json["url"],
      );

  Map<String, dynamic> toJson() => {
        "id": id,
        "url": url,
      };
}

class UserInfoReferralCodeResponse {
/*
{
  "meta": {
    "success": true
  },
  "data": {
    "id": "e3408df9-9d7a-4e3d-88b8-1fe22b809830",
    "username": "0121345456",
    "fullName": "Đặng Tiểu Cường",
    "age": 39,
    "phoneNumber": "+84121345456",
    "secondPhoneNumber": null,
    "gender": 1,
    "createDatetime": 1640319108,
    "active": true,
    "nation": "Việt Nam",
    "province": "Bà Rịa Vũng Tàu",
    "district": "Huyện Long Điền",
    "ward": "Thị trấn Long Hải",
    "nationId": "2857c61e-d5d2-4a7c-810c-1e7ab9e25d86",
    "provinceId": "24e7a947-7783-4d8f-87e7-f94301fc0e89",
    "districtId": "47cbc6b3-2492-4c9d-8f9e-e05ba4d1f093",
    "wardId": "7bb46db9-d9b8-4491-a4e6-7d3d16945576",
    "avatar": null,
    "coverId": "66265ee4-d347-44a3-7e97-08d9c5f86f42",
    "updateDatetime": 1640319108,
    "creatorId": "00000000-0000-0500-0000-000000000000",
    "updaterId": "00000000-0000-0500-0000-000000000000",
    "email": "bacsithuy@gmeo.com",
    "dateOfBirth": 382294800,
    "address": "Láng Cát",
    "level": null,
    "typeOfWork": null,
    "facebookUrl": "facebook.com/dangtieucuong",
    "url": null,
    "introduction": "Đã có hơn 30 năm kinh nghiệm làm bác sĩ thú y",
    "code": "Coach 0121345456",
    "education": null,
    "managerId": null,
    "referralCode": "21iG90",
    "referalDate": null,
    "nameOfAgency": null,
    "manager": null,
    "accountRule": null,
    "accountRoles": null,
    "accountPositionMappings": [
      {
        "id": "08d77cb2-1d02-4ef8-31e2-08d9c5fa88cb",
        "accountId": "e3408df9-9d7a-4e3d-88b8-1fe22b809830",
        "positionId": "78b7338c-10ad-44c3-80fe-98fbe5c47211",
        "position": {
          "id": "78b7338c-10ad-44c3-80fe-98fbe5c47211",
          "code": "Doctor",
          "name": "Bác sĩ"
        }
      }
    ]
  }
} 
*/

  UserInfoReferralCodeResponseMeta? meta;
  UserInfoReferralCodeResponseData? data;

  UserInfoReferralCodeResponse({
    this.meta,
    this.data,
  });

  bool get isUserExists =>
      data?.fullName != null && data?.username != null && data?.phoneNumber != null;

  bool get hasShare => data?.hasShare == true;

  bool get notValidPosition {
    if (data?.accountPositionMappings != null) {
      for (var account in data!.accountPositionMappings!) {
        if (account?.position?.code != null) {
          if (account!.position!.code!.toUpperCase() == 'COACH' ||
              account.position!.code!.toUpperCase() == 'COACHMANAGER' ||
              account.position!.code!.toUpperCase() == 'HEADCOACH') {
            return true;
          }
        }
      }
    }
    return false;
  }

  UserInfoReferralCodeResponse.fromJson(Map<String, dynamic> json) {
    meta = (json['meta'] != null) ? UserInfoReferralCodeResponseMeta.fromJson(json['meta']) : null;
    data = (json['data'] != null) ? UserInfoReferralCodeResponseData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (meta != null) {
      data['meta'] = meta!.toJson();
    }
    if (this.data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
