///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class UserInfoResponseData {
/*
{
  "packageCode": "pro",
  "packageTimeExpired": "11/01/2022 17:16:34",
  "bloodSugarTemplates": "NONE",
  "hasFoodMenu": true,
  "roadmapId": "07491c70-28bf-42bf-731c-08d9986eb25e",
  "currentStudyWeek": 3
} 
*/

  String? packageCode;
  String? packageTimeExpired;
  String? bloodSugarTemplates;
  bool? hasFoodMenu;
  String? roadmapId;
  int? currentStudyWeek;

  UserInfoResponseData({
    this.packageCode,
    this.packageTimeExpired,
    this.bloodSugarTemplates,
    this.hasFoodMenu,
    this.roadmapId,
    this.currentStudyWeek,
  });
  UserInfoResponseData.fromJson(Map<String, dynamic> json) {
    packageCode = json['packageCode']?.toString();
    packageTimeExpired = json['packageTimeExpired']?.toString();
    bloodSugarTemplates = json['bloodSugarTemplates']?.toString();
    hasFoodMenu = json['hasFoodMenu'];
    roadmapId = json['roadmapId']?.toString();
    currentStudyWeek = json['currentStudyWeek']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['packageCode'] = packageCode;
    data['packageTimeExpired'] = packageTimeExpired;
    data['bloodSugarTemplates'] = bloodSugarTemplates;
    data['hasFoodMenu'] = hasFoodMenu;
    data['roadmapId'] = roadmapId;
    data['currentStudyWeek'] = currentStudyWeek;
    return data;
  }
}

class UserInfoResponse {
/*
{
  "id": "00000000-0000-0000-0000-000000000000",
  "statusCode": 200,
  "message": "Success",
  "data": {
    "packageCode": "pro",
    "packageTimeExpired": "11/01/2022 17:16:34",
    "bloodSugarTemplates": "NONE",
    "hasFoodMenu": true,
    "roadmapId": "07491c70-28bf-42bf-731c-08d9986eb25e",
    "currentStudyWeek": 3
  }
} 
*/

  String? id;
  int? statusCode;
  String? message;
  UserInfoResponseData? data;

  UserInfoResponse({
    this.id,
    this.statusCode,
    this.message,
    this.data,
  });
  UserInfoResponse.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    statusCode = json['statusCode']?.toInt();
    message = json['message']?.toString();
    data = (json['data'] != null)
        ? UserInfoResponseData.fromJson(json['data'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['statusCode'] = statusCode;
    data['message'] = message;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
