///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
enum PackageType {
  free,
  no_road_map,
  has_road_map,
}

class UserInfoResponseDataOwnPackageOwnRoadmap {
/*
{
  "startWeek": 1,
  "endWeek": 8,
  "currentDay": 21,
  "currentWeek": 4,
  "firstDayInWeek": 20,
  "lastDayInWeek": 27
} 
*/

  int? startWeek;
  int? endWeek;
  int? currentDay;
  int? currentWeek;
  int? firstDayInWeek;
  int? lastDayInWeek;

  UserInfoResponseDataOwnPackageOwnRoadmap({
    this.startWeek,
    this.endWeek,
    this.currentDay,
    this.currentWeek,
    this.firstDayInWeek,
    this.lastDayInWeek,
  });
  UserInfoResponseDataOwnPackageOwnRoadmap.fromJson(Map<String, dynamic> json) {
    startWeek = json['startWeek']?.toInt();
    endWeek = json['endWeek']?.toInt();
    currentDay = json['currentDay']?.toInt();
    currentWeek = json['currentWeek']?.toInt();
    firstDayInWeek = json['firstDayInWeek']?.toInt();
    lastDayInWeek = json['lastDayInWeek']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['startWeek'] = startWeek;
    data['endWeek'] = endWeek;
    data['currentDay'] = currentDay;
    data['currentWeek'] = currentWeek;
    data['firstDayInWeek'] = firstDayInWeek;
    data['lastDayInWeek'] = lastDayInWeek;
    return data;
  }
}

class UserInfoResponseDataOwnPackage {
/*
{
  "code": "HLV",
  "duration": 8,
  "durationType": 0,
  "activationDate": 1638888013,
  "expirationDate": 1643899213,
  "ownRoadmap": {
    "startWeek": 1,
    "endWeek": 8,
    "currentDay": 21,
    "currentWeek": 4,
    "firstDayInWeek": 20,
    "lastDayInWeek": 27
  }
} 
*/

  String? code;
  int? duration;
  int? durationType;
  int? activationDate;
  int? expirationDate;
  UserInfoResponseDataOwnPackageOwnRoadmap? ownRoadmap;

  UserInfoResponseDataOwnPackage({
    this.code,
    this.duration,
    this.durationType,
    this.activationDate,
    this.expirationDate,
    this.ownRoadmap,
  });
  UserInfoResponseDataOwnPackage.fromJson(Map<String, dynamic> json) {
    code = json['code']?.toString();
    duration = json['duration']?.toInt();
    durationType = json['durationType']?.toInt();
    activationDate = json['activationDate']?.toInt();
    expirationDate = json['expirationDate']?.toInt();
    ownRoadmap = (json['ownRoadmap'] != null)
        ? UserInfoResponseDataOwnPackageOwnRoadmap.fromJson(json['ownRoadmap'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['code'] = code;
    data['duration'] = duration;
    data['durationType'] = durationType;
    data['activationDate'] = activationDate;
    data['expirationDate'] = expirationDate;
    if (ownRoadmap != null) {
      data['ownRoadmap'] = ownRoadmap!.toJson();
    }
    return data;
  }
}

class UserInfoResponseData {
/*
{
  "bloodSugarTemplates": "OP",
  "hasFoodMenu": true,
  "roadmapId": "07491c70-28bf-42bf-731c-08d9986eb25e",
  "ownPackage": {
    "code": "HLV",
    "duration": 8,
    "durationType": 0,
    "activationDate": 1638888013,
    "expirationDate": 1643899213,
    "ownRoadmap": {
      "startWeek": 1,
      "endWeek": 8,
      "currentDay": 21,
      "currentWeek": 4,
      "firstDayInWeek": 20,
      "lastDayInWeek": 27
    }
  }
} 
*/

  String? bloodSugarTemplates;
  bool? hasFoodMenu;
  String? roadmapId;
  UserInfoResponseDataOwnPackage? ownPackage;

  UserInfoResponseData({
    this.bloodSugarTemplates,
    this.hasFoodMenu,
    this.roadmapId,
    this.ownPackage,
  });

  PackageType get packageType {
    if (this.ownPackage == null) return PackageType.free;
    if (this.ownPackage?.ownRoadmap == null) return PackageType.no_road_map;
    return PackageType.has_road_map;
  }

  UserInfoResponseData.fromJson(Map<String, dynamic> json) {
    bloodSugarTemplates = json['bloodSugarTemplates']?.toString();
    hasFoodMenu = json['hasFoodMenu'];
    roadmapId = json['roadmapId']?.toString();
    ownPackage = (json['ownPackage'] != null)
        ? UserInfoResponseDataOwnPackage.fromJson(json['ownPackage'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['bloodSugarTemplates'] = bloodSugarTemplates;
    data['hasFoodMenu'] = hasFoodMenu;
    data['roadmapId'] = roadmapId;
    if (ownPackage != null) {
      data['ownPackage'] = ownPackage!.toJson();
    }
    return data;
  }
}

class UserInfoResponse {
/*
{
  "id": "00000000-0000-0000-0000-000000000000",
  "statusCode": 200,
  "message": "Success",
  "data": {
    "bloodSugarTemplates": "OP",
    "hasFoodMenu": true,
    "roadmapId": "07491c70-28bf-42bf-731c-08d9986eb25e",
    "ownPackage": {
      "code": "HLV",
      "duration": 8,
      "durationType": 0,
      "activationDate": 1638888013,
      "expirationDate": 1643899213,
      "ownRoadmap": {
        "startWeek": 1,
        "endWeek": 8,
        "currentDay": 21,
        "currentWeek": 4,
        "firstDayInWeek": 20,
        "lastDayInWeek": 27
      }
    }
  }
} 
*/

  String? id;
  int? statusCode;
  String? message;
  UserInfoResponseData? data;

  UserInfoResponse({
    this.id,
    this.statusCode,
    this.message,
    this.data,
  });
  UserInfoResponse.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    statusCode = json['statusCode']?.toInt();
    message = json['message']?.toString();
    data = (json['data'] != null)
        ? UserInfoResponseData.fromJson(json['data'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['statusCode'] = statusCode;
    data['message'] = message;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
