///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
enum PackageType {
  free,
  no_road_map,
  has_road_map,
}

Map<String, String> packageMapping = {
  "NC1": "Nâng cao Coach 1-1",
  "TN": "Thử nghiệm",
  "MNLE": "Manulife - Tiền đái tháo đường",
  "PVIP": "VIP - Tiền đái tháo đường",
  "TDTD": "Tiền đái tháo đường",
  "VIP": "VIP",
  "DT-2": "Duy trì lối sống 2",
  "MEGA": "Mega - Tiền đái tháo đường",
  "PVVIP": "VVIP - Tiền đái tháo đường",
  "CB1": "Cơ bản Coach 1-1",
  "AB1": "CGM 14 ngày",
  "NC2": "Nâng cao Coach 1-N",
  "NVIP": "VIP - Dinh Dưỡng",
  "MVIP": "VIP - Tinh thần",
  "EVIP": "EVIP - Vận động",
  "ROBIN": "ROBIN",
  "ABC": "TEST Tiền Đái tháo đường 1-N",
  "P1N": "Tiền Đái tháo đường 1-N",
  "CB2": "Cơ bản Coach 1-N",
  "VVIP": "VVIP",
  "TK1": "Gói thai kỳ Coach 1-1",
  "TN1": "Thay đổi lối sống – 14N",
  "DT-1": "Duy trì lối sống 1",
  "TK2": "Gói thai kỳ Coach 1-N",
};

class UserInfoResponseDataOwnPackageOwnRoadmap {
/*
{
  "startWeek": 1,
  "endWeek": 8,
  "currentDay": 21,
  "currentWeek": 4,
  "firstDayInWeek": 20,
  "lastDayInWeek": 27
} 
*/

  int? startWeek;
  int? endWeek;
  int? currentDay;
  int? currentWeek;
  int? firstDayInWeek;
  int? lastDayInWeek;

  UserInfoResponseDataOwnPackageOwnRoadmap({
    this.startWeek,
    this.endWeek,
    this.currentDay,
    this.currentWeek,
    this.firstDayInWeek,
    this.lastDayInWeek,
  });
  UserInfoResponseDataOwnPackageOwnRoadmap.fromJson(Map<String, dynamic> json) {
    startWeek = json['startWeek']?.toInt();
    endWeek = json['endWeek']?.toInt();
    currentDay = json['currentDay']?.toInt();
    currentWeek = json['currentWeek']?.toInt();
    firstDayInWeek = json['firstDayInWeek']?.toInt();
    lastDayInWeek = json['lastDayInWeek']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['startWeek'] = startWeek;
    data['endWeek'] = endWeek;
    data['currentDay'] = currentDay;
    data['currentWeek'] = currentWeek;
    data['firstDayInWeek'] = firstDayInWeek;
    data['lastDayInWeek'] = lastDayInWeek;
    return data;
  }
}

class UserInfoResponseDataOwnPackage {
/*
{
  "code": "HLV",
  "duration": 8,
  "durationType": 0,
  "activationDate": 1638888013,
  "expirationDate": 1643899213,
  "ownRoadmap": {
    "startWeek": 1,
    "endWeek": 8,
    "currentDay": 21,
    "currentWeek": 4,
    "firstDayInWeek": 20,
    "lastDayInWeek": 27
  }
} 
*/

  String? code;
  int? duration;
  int? durationType;
  int? activationDate;
  int? expirationDate;
  int? endDateFirst;
  String? logo;
  UserInfoResponseDataOwnPackageOwnRoadmap? ownRoadmap;

  UserInfoResponseDataOwnPackage({
    this.code,
    this.duration,
    this.durationType,
    this.activationDate,
    this.expirationDate,
    this.endDateFirst,
    this.ownRoadmap,
    this.logo,
  });
  UserInfoResponseDataOwnPackage.fromJson(Map<String, dynamic> json) {
    code = json['code']?.toString();
    duration = json['duration']?.toInt();
    durationType = json['durationType']?.toInt();
    activationDate = json['activationDate']?.toInt();
    expirationDate = json['expirationDate']?.toInt();
    endDateFirst = json['endDateFirst']?.toInt();
    logo = json['logo']?.toString();
    ownRoadmap = (json['ownRoadmap'] != null)
        ? UserInfoResponseDataOwnPackageOwnRoadmap.fromJson(json['ownRoadmap'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['code'] = code;
    data['duration'] = duration;
    data['durationType'] = durationType;
    data['activationDate'] = activationDate;
    data['expirationDate'] = expirationDate;
    data['endDateFirst'] = endDateFirst;
    data['logo'] = logo;
    if (ownRoadmap != null) {
      data['ownRoadmap'] = ownRoadmap!.toJson();
    }
    return data;
  }
}

class UserInfoResponseData {
/*
{
  "bloodSugarTemplates": "OP",
  "hasFoodMenu": true,
  "roadmapId": "07491c70-28bf-42bf-731c-08d9986eb25e",
  "ownPackage": {
    "code": "HLV",
    "duration": 8,
    "durationType": 0,
    "activationDate": 1638888013,
    "expirationDate": 1643899213,
    "ownRoadmap": {
      "startWeek": 1,
      "endWeek": 8,
      "currentDay": 21,
      "currentWeek": 4,
      "firstDayInWeek": 20,
      "lastDayInWeek": 27
    }
  }
} 
*/

  String? bloodSugarTemplates;
  bool? hasFoodMenu;
  String? roadmapId;
  UserInfoResponseDataOwnPackage? ownPackage;
  int? currentDateTime;

  UserInfoResponseData({
    this.bloodSugarTemplates,
    this.hasFoodMenu,
    this.roadmapId,
    this.ownPackage,
    this.currentDateTime,
  });

  PackageType get packageType {
    if (this.ownPackage == null) return PackageType.free;
    if (this.ownPackage?.ownRoadmap == null) return PackageType.no_road_map;
    return PackageType.has_road_map;
  }

  UserInfoResponseData.fromJson(Map<String, dynamic> json) {
    bloodSugarTemplates = json['bloodSugarTemplates']?.toString();
    hasFoodMenu = json['hasFoodMenu'];
    currentDateTime = json['currentDateTime'];
    roadmapId = json['roadmapId']?.toString();
    ownPackage = (json['ownPackage'] != null)
        ? UserInfoResponseDataOwnPackage.fromJson(json['ownPackage'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['bloodSugarTemplates'] = bloodSugarTemplates;
    data['hasFoodMenu'] = hasFoodMenu;
    data['roadmapId'] = roadmapId;
    data['currentDateTime'] = currentDateTime;
    if (ownPackage != null) {
      data['ownPackage'] = ownPackage!.toJson();
    }
    return data;
  }
}

class UserInfoResponse {
/*
{
  "id": "00000000-0000-0000-0000-000000000000",
  "statusCode": 200,
  "message": "Success",
  "data": {
    "bloodSugarTemplates": "OP",
    "hasFoodMenu": true,
    "roadmapId": "07491c70-28bf-42bf-731c-08d9986eb25e",
    "ownPackage": {
      "code": "HLV",
      "duration": 8,
      "durationType": 0,
      "activationDate": 1638888013,
      "expirationDate": 1643899213,
      "ownRoadmap": {
        "startWeek": 1,
        "endWeek": 8,
        "currentDay": 21,
        "currentWeek": 4,
        "firstDayInWeek": 20,
        "lastDayInWeek": 27
      }
    }
  }
} 
*/

  String? id;
  int? statusCode;
  String? message;
  UserInfoResponseData? data;

  UserInfoResponse({
    this.id,
    this.statusCode,
    this.message,
    this.data,
  });
  UserInfoResponse.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    statusCode = json['statusCode']?.toInt();
    message = json['message']?.toString();
    data = (json['data'] != null)
        ? UserInfoResponseData.fromJson(json['data'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['statusCode'] = statusCode;
    data['message'] = message;
    if (this.data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
