///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///

class WeekSmartGoalData {
/*
{
  "type": 0,
  "name": "string",
  "description": "string",
  "executeWeekTimes": 0,
  "actualExecuteWeekTimes": 0
} 
*/

  int? type;
  String? name;
  String? description;
  int? executeWeekTimes;
  int? actualExecuteWeekTimes;

  WeekSmartGoalData({
    this.type,
    this.name,
    this.description,
    this.executeWeekTimes,
    this.actualExecuteWeekTimes,
  });

  double get progress {
    if (actualExecuteWeekTimes == null) return 0;
    if (executeWeekTimes == null || executeWeekTimes == 0) return 1;
    final double progress = actualExecuteWeekTimes! / executeWeekTimes!;
    if (progress < 0) return 0;
    if (progress > 1) return 1;
    return progress;
  }

  WeekSmartGoalData.fromJson(Map<String, dynamic> json) {
    type = json['type']?.toInt();
    name = json['name']?.toString();
    description = json['description']?.toString();
    executeWeekTimes = json['executeWeekTimes']?.toInt();
    actualExecuteWeekTimes = json['actualExecuteWeekTimes']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['type'] = type;
    data['name'] = name;
    data['description'] = description;
    data['executeWeekTimes'] = executeWeekTimes;
    data['actualExecuteWeekTimes'] = actualExecuteWeekTimes;
    return data;
  }
}

class WeekSmartGoalResponseData {
/*
{
  "lesson": {
    "type": 0,
    "name": "string",
    "description": "string",
    "executeWeekTimes": 0,
    "actualExecuteWeekTimes": 0
  },
  "exercise": {
    "type": 0,
    "name": "string",
    "description": "string",
    "executeWeekTimes": 0,
    "actualExecuteWeekTimes": 0
  }
} 
*/

  WeekSmartGoalData? lesson;
  WeekSmartGoalData? exercise;

  WeekSmartGoalResponseData({
    this.lesson,
    this.exercise,
  });
  WeekSmartGoalResponseData.fromJson(Map<String, dynamic> json) {
    lesson = (json['lesson'] != null)
        ? WeekSmartGoalData.fromJson(json['lesson'])
        : null;
    exercise = (json['exercise'] != null)
        ? WeekSmartGoalData.fromJson(json['exercise'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (lesson != null) {
      data['lesson'] = lesson!.toJson();
    }
    if (exercise != null) {
      data['exercise'] = exercise!.toJson();
    }
    return data;
  }
}

class WeekSmartGoalResponseMeta {
/*
{
  "success": true
} 
*/

  bool? success;

  WeekSmartGoalResponseMeta({
    this.success,
  });
  WeekSmartGoalResponseMeta.fromJson(Map<String, dynamic> json) {
    success = json['success'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    return data;
  }
}

class WeekSmartGoalResponse {
/*
{
  "meta": {
    "success": true
  },
  "data": {
    "lesson": {
      "type": 0,
      "name": "string",
      "description": "string",
      "executeWeekTimes": 0,
      "actualExecuteWeekTimes": 0
    },
    "exercise": {
      "type": 0,
      "name": "string",
      "description": "string",
      "executeWeekTimes": 0,
      "actualExecuteWeekTimes": 0
    }
  }
} 
*/

  WeekSmartGoalResponseMeta? meta;
  WeekSmartGoalResponseData? data;

  WeekSmartGoalResponse({
    this.meta,
    this.data,
  });

  List<WeekSmartGoalData> get weekSmartGoalList {
    final List<WeekSmartGoalData> weekSmartGoalList = [];
    if (data?.lesson != null) weekSmartGoalList.add(data!.lesson!);
    if (data?.exercise != null) weekSmartGoalList.add(data!.exercise!);
    return weekSmartGoalList;
  }

  WeekSmartGoalResponse.fromJson(Map<String, dynamic> json) {
    meta = (json['meta'] != null)
        ? WeekSmartGoalResponseMeta.fromJson(json['meta'])
        : null;
    data = (json['data'] != null)
        ? WeekSmartGoalResponseData.fromJson(json['data'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (meta != null) {
      data['meta'] = meta!.toJson();
    }
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
