import 'package:medical/src/widget/my_plan_screens/my_plan/models/completion_status.dart';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class WeekStatesResponseData {
/*
{
  "week": 1,
  "weekTitle": "Tuần 1",
  "state": 0
} 
*/

  int? week;
  String? weekTitle;
  int? state;

  WeekStatesResponseData({
    this.week,
    this.weekTitle,
    this.state,
  });

  CompletionStatus get completionStatus {
    if (state == 0) return CompletionStatus.not_completed;
    if (state == 1) return CompletionStatus.completed;
    if (state == 2) return CompletionStatus.studying;
    return CompletionStatus.not_start_yet;
  }

  WeekStatesResponseData.fromJson(Map<String, dynamic> json) {
    week = json['week']?.toInt();
    weekTitle = json['weekTitle']?.toString();
    state = json['state']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['week'] = week;
    data['weekTitle'] = weekTitle;
    data['state'] = state;
    return data;
  }
}

class WeekStatesResponseMeta {
/*
{
  "success": true
} 
*/

  bool? success;

  WeekStatesResponseMeta({
    this.success,
  });
  WeekStatesResponseMeta.fromJson(Map<String, dynamic> json) {
    success = json['success'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    return data;
  }
}

class WeekStatesResponse {
/*
{
  "meta": {
    "success": true
  },
  "data": [
    {
      "week": 1,
      "weekTitle": "Tuần 1",
      "state": 0
    }
  ]
} 
*/

  WeekStatesResponseMeta? meta;
  List<WeekStatesResponseData?>? data;

  WeekStatesResponse({
    this.meta,
    this.data,
  });
  WeekStatesResponse.fromJson(Map<String, dynamic> json) {
    meta = (json['meta'] != null)
        ? WeekStatesResponseMeta.fromJson(json['meta'])
        : null;
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <WeekStatesResponseData>[];
      v.forEach((v) {
        arr0.add(WeekStatesResponseData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (meta != null) {
      data['meta'] = meta!.toJson();
    }
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }
}
