import 'package:medical/src/model/response/my_benefit_response.dart';

/// Mock response matching the real `GET App/UserBundleOrders/my-benefit`
/// contract: `itemType`/`appFeature` are raw wire ints (see
/// [BenefitBundleItemType.resolve]), and `bookingType` is derived rather
/// than sent on the wire. Mirrors a real dev-environment payload, with
/// remote `imageUrl.url` values swapped for local asset paths.
class MyBenefitMock {
  static MyBenefitResponse get response {
    // Vouchers are computed relative to "now" (instead of the fixed epoch
    // seconds the dev API returned) so they stay valid regardless of when
    // this mock is run.
    final now = DateTime.now();
    final validUntilMedArmor =
        now.add(const Duration(days: 200)).millisecondsSinceEpoch ~/ 1000;
    final validUntilWeCare =
        now.add(const Duration(days: 190)).millisecondsSinceEpoch ~/ 1000;
    final validUntilCalifornia =
        now.add(const Duration(days: 190)).millisecondsSinceEpoch ~/ 1000;

    return MyBenefitResponse.fromJson({
      'meta': {'success': true},
      'data': {
        'id': '1501dad4-9862-4830-b254-08deed254694',
        'name': 'Chương trình chăm sóc sức khoẻ doanh nghiệp',
        'status': 1,
        'remainingDays': 183,
        'startDate': 1785283200,
        'endDate': 1801180800,
        'totalItems': 10,
        'usedItems': 0,
        'completionPercent': 0,
        'sections': [
          {
            'tagName': 'Thăm khám & Xét nghiệm',
            'items': [
              {
                'itemId': '142ed00d-5957-491f-bf41-08deed25465b',
                'itemType': 2,
                'appFeature': 1,
                'name': 'Khám và tư vấn dinh dưỡng',
                'category': 0,
                'reportType': null,
                'specialtyId': null,
                'specialtyName': 'Thừa cân/Béo phì',
                'clinicId': null,
                'isUnlimited': 0,
                'quantity': 1,
                'quantityUsed': 0,
                'discountValue': 0,
                'discountType': 0,
                'servicePackageId': null,
                'totalWeek': null,
                'currentWeek': null,
                'benefitType': null,
              },
              {
                'itemId': 'd0d93ad7-e32b-45f6-bf46-08deed25465b',
                'itemType': 2,
                'appFeature': 2,
                'name': 'Khám cơ xương khớp',
                'category': 0,
                'reportType': null,
                'specialtyId': 2,
                'specialtyName': 'Cơ xương khớp',
                'clinicId': 1644,
                'isUnlimited': 0,
                'quantity': 1,
                'quantityUsed': 0,
                'discountValue': 0,
                'discountType': 0,
                'servicePackageId': null,
                'totalWeek': null,
                'currentWeek': null,
                'benefitType': null,
              },
              {
                'itemId': 'a996c743-9a7e-465b-bf45-08deed25465b',
                'itemType': 2,
                'appFeature': 3,
                'name': 'Xét nghiệm Gene',
                'category': 0,
                'reportType': null,
                'specialtyId': null,
                'specialtyName': null,
                'clinicId': null,
                'isUnlimited': 0,
                'quantity': 1,
                'quantityUsed': 0,
                'discountValue': 0,
                'discountType': 0,
                'servicePackageId': null,
                'totalWeek': null,
                'currentWeek': null,
                'benefitType': {
                  'id': 'b5bbd0ea-2fb9-4c75-0ca4-08dedbdbb8bc',
                  'title': 'MedArmor',
                  'contentType': 2,
                  'description':
                      'MedArmor Vietnam là trung tâm tầm soát và chăm sóc sức khỏe công nghệ cao, đặt tại 33C Lê Thánh Tôn, Quận 1, ứng dụng sinh học phân tử và trí tuệ nhân tạo để phân tích đa tầng dữ liệu sức khỏe cá nhân. \n \n Hệ thống 4DMatrix™ đánh giá hàng trăm chỉ dấu sinh học (gen, máu, mRNA, vi sinh đường ruột), hỗ trợ phát hiện sớm xu hướng sức khỏe và cá nhân hóa tư vấn phòng ngừa lâu dài. \n \n Trung tâm flagship tại TP.HCM, kết nối mạng lưới chuyên gia và đối tác y tế quốc tế để tư vấn chuyên sâu và theo dõi sức khỏe chủ động.',
                  'status': 1,
                  'tag': null,
                  'hasVoucher': 1,
                  'voucherName': 'GIẢM 10%',
                  'voucherSubName': 'Gói dịch vụ tại MedArmor',
                  'voucherCode': 'CFY-CORP-2024',
                  'voucherValue': 'Giảm 10% trên tổng hoá đơn',
                  'applicableTo': 'Nhân viên Axon',
                  'applicableLocation': 'Tất cả cơ sở',
                  'validUntil': validUntilMedArmor,
                  'location': '33C Lê Thánh Tôn, Quận 1, TP.HCM',
                  'openTime':
                      '08:30 – 17:30, Thứ 2 – Thứ 7 (giờ có thể thay đổi, vui lòng đặt lịch trước)',
                  'order': 1,
                  'bundleTagId': '981561ae-00d3-40e2-a702-08deed17fe8f',
                  'media': [
                    {
                      'id': 'dcd0edff-ae25-4a9f-e167-08deed259d2f',
                      'bundleBenefitTypeId':
                          'b5bbd0ea-2fb9-4c75-0ca4-08dedbdbb8bc',
                      'imageId': 'b12863b3-05f8-414d-afa2-08deed1ab011',
                      'url': null,
                      'type': 1,
                      'sortOrder': 1,
                      'imageUrl': {
                        'id': 'b12863b3-05f8-414d-afa2-08deed1ab011',
                        'url': 'lib/res/drawables/med_image_title.jpg',
                      },
                    },
                    {
                      'id': '714b8a68-254f-4ef9-e168-08deed259d2f',
                      'bundleBenefitTypeId':
                          'b5bbd0ea-2fb9-4c75-0ca4-08dedbdbb8bc',
                      'imageId': '95cfd439-be04-4dc7-afa3-08deed1ab011',
                      'url': null,
                      'type': 1,
                      'sortOrder': 2,
                      'imageUrl': {
                        'id': '95cfd439-be04-4dc7-afa3-08deed1ab011',
                        'url': 'lib/res/drawables/med_sub_image_1.jpg',
                      },
                    },
                    {
                      'id': '6eeaa046-5c03-4948-e169-08deed259d2f',
                      'bundleBenefitTypeId':
                          'b5bbd0ea-2fb9-4c75-0ca4-08dedbdbb8bc',
                      'imageId': 'a92e9aaf-d4ab-42b0-afa4-08deed1ab011',
                      'url': null,
                      'type': 1,
                      'sortOrder': 3,
                      'imageUrl': {
                        'id': 'a92e9aaf-d4ab-42b0-afa4-08deed1ab011',
                        'url': 'lib/res/drawables/med_sub_image_2.jpg',
                      },
                    },
                  ],
                },
              },
              {
                'itemId': '238224e2-de76-4802-bf44-08deed25465b',
                'itemType': 2,
                'appFeature': 1,
                'name': 'Tư vấn chuyên sâu với bác sĩ',
                'category': 0,
                'reportType': null,
                'specialtyId': null,
                'specialtyName': 'Thừa cân/Béo phì',
                'clinicId': null,
                'isUnlimited': 0,
                'quantity': 1,
                'quantityUsed': 0,
                'discountValue': 0,
                'discountType': 0,
                'servicePackageId': null,
                'totalWeek': null,
                'currentWeek': null,
                'benefitType': null,
              },
              {
                'itemId': '5ba014d6-8df8-4f8d-bf42-08deed25465b',
                'itemType': 2,
                'appFeature': 5,
                'name': 'Giao thuốc tận nhà',
                'category': 0,
                'reportType': null,
                'specialtyId': null,
                'specialtyName': null,
                'clinicId': null,
                'isUnlimited': 0,
                'quantity': 1,
                'quantityUsed': 0,
                'discountValue': 0,
                'discountType': 0,
                'servicePackageId': null,
                'totalWeek': null,
                'currentWeek': null,
                'benefitType': null,
              },
            ],
          },
          {
            'tagName': 'Dịch vụ sức khoẻ',
            'items': [
              {
                'itemId': 'f2f28f2e-e77d-466f-bf43-08deed25465b',
                'itemType': 2,
                'appFeature': 3,
                'name': 'Điều trị bệnh lý Cơ xương khớp',
                'category': 0,
                'reportType': null,
                'specialtyId': null,
                'specialtyName': null,
                'clinicId': null,
                'isUnlimited': 0,
                'quantity': 1,
                'quantityUsed': 0,
                'discountValue': 0,
                'discountType': 0,
                'servicePackageId': null,
                'totalWeek': null,
                'currentWeek': null,
                'benefitType': {
                  'id': '658994ae-50f2-469f-4fa0-08deed26860e',
                  'title': 'Optimal365 Chiropractic',
                  'contentType': 2,
                  'description':
                      'Optimal365 Chiropractic là trung tâm trị liệu cơ xương khớp – cột sống chuẩn quốc tế tại Quận 1, TP.HCM, được dẫn dắt bởi đội ngũ bác sĩ Chiropractic được đào tạo và cấp phép tại Mỹ. \n \n Trung tâm chuyên điều trị không xâm lấn các vấn đề đau cổ, vai, lưng, thoát vị đĩa đệm, đau thần kinh tọa và chấn thương thể thao, tập trung vào chỉnh trục cột sống, cải thiện tư thế và phục hồi vận động bền vững.',
                  'status': 1,
                  'tag': null,
                  // No active voucher for this partner — the intro page
                  // falls back to a promo image (media type == 4).
                  'hasVoucher': 0,
                  'voucherName': '',
                  'voucherSubName': '',
                  'voucherCode': '',
                  'voucherValue': '',
                  'applicableTo': '',
                  'applicableLocation': '',
                  'validUntil': null,
                  'location':
                      '18Ter Nguyễn Thị Minh Khai, Phường Đa Kao, Quận 1, TP.HCM',
                  'openTime':
                      '09:00 – 19:00, Thứ 2 – Thứ 7 (Chủ nhật nghỉ; giờ có thể thay đổi, vui lòng đặt lịch trước)',
                  'order': 0,
                  'bundleTagId': '863c7fda-7608-4660-a701-08deed17fe8f',
                  'media': [
                    {
                      'id': '3750f0c7-aa1c-4c38-e177-08deed259d2f',
                      'bundleBenefitTypeId':
                          '658994ae-50f2-469f-4fa0-08deed26860e',
                      'imageId': '64fb4525-0b15-4482-93a8-08deed2660f8',
                      'url': null,
                      'type': 4,
                      'sortOrder': 0,
                      'imageUrl': {
                        'id': '64fb4525-0b15-4482-93a8-08deed2660f8',
                        'url': 'lib/res/drawables/optimal_image_voucher.jpg',
                      },
                    },
                    {
                      'id': 'e1458034-4f48-47c6-e174-08deed259d2f',
                      'bundleBenefitTypeId':
                          '658994ae-50f2-469f-4fa0-08deed26860e',
                      'imageId': 'd6e61daa-25c1-4827-93a9-08deed2660f8',
                      'url': null,
                      'type': 1,
                      'sortOrder': 1,
                      'imageUrl': {
                        'id': 'd6e61daa-25c1-4827-93a9-08deed2660f8',
                        'url': 'lib/res/drawables/optimal_image_title.jpg',
                      },
                    },
                    {
                      'id': '53cda94e-89f8-43e1-e175-08deed259d2f',
                      'bundleBenefitTypeId':
                          '658994ae-50f2-469f-4fa0-08deed26860e',
                      'imageId': '750e8ed7-a890-4f01-93aa-08deed2660f8',
                      'url': null,
                      'type': 1,
                      'sortOrder': 2,
                      'imageUrl': {
                        'id': '750e8ed7-a890-4f01-93aa-08deed2660f8',
                        'url': 'lib/res/drawables/optimal_sub_image_1.jpg',
                      },
                    },
                    {
                      'id': '4d264b68-f2d1-4c9c-e176-08deed259d2f',
                      'bundleBenefitTypeId':
                          '658994ae-50f2-469f-4fa0-08deed26860e',
                      'imageId': 'd25d63a0-e443-4644-93ab-08deed2660f8',
                      'url': null,
                      'type': 1,
                      'sortOrder': 3,
                      'imageUrl': {
                        'id': 'd25d63a0-e443-4644-93ab-08deed2660f8',
                        'url': 'lib/res/drawables/optimal_sub_image_2.jpg',
                      },
                    },
                  ],
                },
              },
              {
                'itemId': 'ee2338f3-2b09-4d11-bf47-08deed25465b',
                'itemType': 2,
                'appFeature': 3,
                'name': 'Dịch vụ chăm sóc tại nhà Wecare247',
                'category': 0,
                'reportType': null,
                'specialtyId': null,
                'specialtyName': null,
                'clinicId': null,
                'isUnlimited': 0,
                'quantity': 1,
                'quantityUsed': 0,
                'discountValue': 0,
                'discountType': 0,
                'servicePackageId': null,
                'totalWeek': null,
                'currentWeek': null,
                'benefitType': {
                  'id': '2b013ca8-119d-40f8-d7c6-08deebc86f24',
                  'title': 'Dịch vụ chăm sóc tại nhà Wecare247',
                  'contentType': 2,
                  'description':
                      'WeCare247 là đơn vị cung cấp dịch vụ chăm sóc sức khỏe cá nhân tại nhà và tại bệnh viện, thành lập năm 2017 với sứ mệnh nâng cao chất lượng sống cho các gia đình Việt Nam. \n \n Đội ngũ chăm sóc viên và điều dưỡng được đào tạo bài bản, làm việc 24/7, hỗ trợ người cao tuổi và người bệnh trong sinh hoạt, theo dõi sức khỏe và phối hợp cùng bác sĩ điều trị.',
                  'status': 1,
                  'tag': null,
                  'hasVoucher': 1,
                  'voucherName': 'GIẢM 10%',
                  'voucherSubName': 'Gói chăm sóc sức khoẻ tại WeCare247',
                  'voucherCode': 'CFY-CORP-2024',
                  'voucherValue': 'Giảm 10% trên tổng hoá đơn',
                  'applicableTo': 'Nhân viên Axon',
                  'applicableLocation': 'Tất cả cơ sở',
                  'validUntil': validUntilWeCare,
                  'location':
                      'Dịch vụ tại nhà & bệnh viện tại TP.HCM, mạng lưới hợp tác nhiều bệnh viện tuyến đầu',
                  'openTime':
                      'Hoạt động linh hoạt 24/7, kể cả Lễ Tết (đặt lịch trước để sắp xếp chăm sóc viên)',
                  'order': 0,
                  'bundleTagId': '863c7fda-7608-4660-a701-08deed17fe8f',
                  'media': [
                    {
                      'id': '92b5e4a4-5092-4f8f-e171-08deed259d2f',
                      'bundleBenefitTypeId':
                          '2b013ca8-119d-40f8-d7c6-08deebc86f24',
                      'imageId': '203f791d-3fd4-48ef-3510-08deed22e608',
                      'url': null,
                      'type': 1,
                      'sortOrder': 1,
                      'imageUrl': {
                        'id': '203f791d-3fd4-48ef-3510-08deed22e608',
                        'url': 'lib/res/drawables/wecare_image_title.jpg',
                      },
                    },
                    {
                      'id': '63e98a2d-7da4-4d8f-e172-08deed259d2f',
                      'bundleBenefitTypeId':
                          '2b013ca8-119d-40f8-d7c6-08deebc86f24',
                      'imageId': 'cd2d42e4-9833-4d9d-3511-08deed22e608',
                      'url': null,
                      'type': 1,
                      'sortOrder': 2,
                      'imageUrl': {
                        'id': 'cd2d42e4-9833-4d9d-3511-08deed22e608',
                        'url': 'lib/res/drawables/wecare_sub_image_1.jpg',
                      },
                    },
                    {
                      'id': '67cb6cc7-a767-4505-e173-08deed259d2f',
                      'bundleBenefitTypeId':
                          '2b013ca8-119d-40f8-d7c6-08deebc86f24',
                      'imageId': '5656aca3-3b36-4e82-3512-08deed22e608',
                      'url': null,
                      'type': 1,
                      'sortOrder': 3,
                      'imageUrl': {
                        'id': '5656aca3-3b36-4e82-3512-08deed22e608',
                        'url': 'lib/res/drawables/wecare_sub_image_2.jpg',
                      },
                    },
                  ],
                },
              },
              {
                'itemId': '848fe966-8440-4802-bf49-08deed25465b',
                'itemType': 2,
                'appFeature': 3,
                'name': 'Tập luyện tại California Fitness & Yoga',
                'category': 0,
                'reportType': null,
                'specialtyId': null,
                'specialtyName': null,
                'clinicId': null,
                'isUnlimited': 0,
                'quantity': 1,
                'quantityUsed': 0,
                'discountValue': 0,
                'discountType': 0,
                'servicePackageId': null,
                'totalWeek': null,
                'currentWeek': null,
                'benefitType': {
                  'id': '430d6215-ec9d-40fc-9e60-08deed22c245',
                  'title': 'California Fitness & Yoga',
                  'contentType': 2,
                  'description':
                      'Chuỗi phòng gym & yoga hàng đầu tại Việt Nam với hơn 20 cơ sở trên toàn quốc. Trang thiết bị hiện đại, đội ngũ HLV chuyên nghiệp và không gian rộng rãi, thoáng mát.',
                  'status': 1,
                  'tag': null,
                  'hasVoucher': 1,
                  'voucherName': 'Miễn phí 21 ngày',
                  'voucherSubName':
                      'Gói dịch vụ tại California Fitness & Yoga',
                  'voucherCode': 'CFY-CORP-2024',
                  'voucherValue': 'Miễn phí 100%',
                  'applicableTo': 'Nhân viên Axon',
                  'applicableLocation': 'Tất cả cơ sở',
                  'validUntil': validUntilCalifornia,
                  'location': '20+ cơ sở tại TP.HCM, Hà Nội, Đà Nẵng',
                  'openTime': 'Mở cửa 05:30 – 22:30, tất cả các ngày',
                  'order': 0,
                  'bundleTagId': '863c7fda-7608-4660-a701-08deed17fe8f',
                  'media': [
                    {
                      'id': '01d4d225-3bfd-4ffe-e16a-08deed259d2f',
                      'bundleBenefitTypeId':
                          '430d6215-ec9d-40fc-9e60-08deed22c245',
                      'imageId': 'c7457262-b662-4581-3509-08deed22e608',
                      'url': null,
                      'type': 1,
                      'sortOrder': 1,
                      'imageUrl': {
                        'id': 'c7457262-b662-4581-3509-08deed22e608',
                        'url': 'lib/res/drawables/cali_image_title.jpg',
                      },
                    },
                    {
                      'id': 'a03c8bd8-e54f-42b2-e16b-08deed259d2f',
                      'bundleBenefitTypeId':
                          '430d6215-ec9d-40fc-9e60-08deed22c245',
                      'imageId': 'bbdb31b7-c884-4947-350a-08deed22e608',
                      'url': null,
                      'type': 1,
                      'sortOrder': 2,
                      'imageUrl': {
                        'id': 'bbdb31b7-c884-4947-350a-08deed22e608',
                        'url': 'lib/res/drawables/cali_sub_image_1.jpg',
                      },
                    },
                    {
                      'id': '57eb9eb3-13e4-45a7-e16c-08deed259d2f',
                      'bundleBenefitTypeId':
                          '430d6215-ec9d-40fc-9e60-08deed22c245',
                      'imageId': 'f6b72500-d7f4-4643-350b-08deed22e608',
                      'url': null,
                      'type': 1,
                      'sortOrder': 3,
                      'imageUrl': {
                        'id': 'f6b72500-d7f4-4643-350b-08deed22e608',
                        'url': 'lib/res/drawables/cali_sub_image_2.jpg',
                      },
                    },
                    {
                      'id': 'f105e6e5-8554-437d-e16d-08deed259d2f',
                      'bundleBenefitTypeId':
                          '430d6215-ec9d-40fc-9e60-08deed22c245',
                      'imageId': 'b36bbc91-da9e-4fad-350c-08deed22e608',
                      'url': null,
                      'type': 1,
                      'sortOrder': 4,
                      'imageUrl': {
                        'id': 'b36bbc91-da9e-4fad-350c-08deed22e608',
                        'url': 'lib/res/drawables/cali_sub_image_3.png',
                      },
                    },
                  ],
                },
              },
              {
                'itemId': '8abd7428-461e-4539-bf48-08deed25465b',
                'itemType': 2,
                'appFeature': 4,
                'name': 'Phân tích sức khoẻ và lộ trình cải thiện',
                'category': 0,
                'reportType': 1,
                'specialtyId': null,
                'specialtyName': null,
                'clinicId': null,
                'isUnlimited': 0,
                'quantity': 1,
                'quantityUsed': 0,
                'discountValue': 0,
                'discountType': 0,
                'servicePackageId': null,
                'totalWeek': null,
                'currentWeek': null,
                'benefitType': null,
              },
              {
                'itemId': '5e39f62d-835e-405a-d569-08deed25466c',
                'itemType': 1,
                'appFeature': 0,
                'name': 'Chương trình Thay đổi lối sống y khoa',
                'category': null,
                'reportType': null,
                'specialtyId': null,
                'specialtyName': null,
                'clinicId': null,
                'isUnlimited': 0,
                'quantity': 1,
                'quantityUsed': 0,
                'discountValue': 0,
                'discountType': 0,
                'servicePackageId': '78b2c272-cd99-426d-87c4-df3a35d2fe32',
                'totalWeek': 22,
                'currentWeek': null,
                'benefitType': null,
              },
            ],
          },
        ],
      },
    });
  }
}
