import 'package:medical/src/model/response/my_benefit_response.dart';

/// Mock response covering 6 benefit item types (excluding medicine).
class MyBenefitMock {
  static MyBenefitResponse get response => MyBenefitResponse.fromJson({
        'meta': {'success': true},
        'data': {
          'id': 'e2937f30-eec6-4071-13b9-08ded80d5c30',
          'name': 'Chương trình Chăm sóc sức khoẻ doanh nghiệp',
          'status': 1,
          'remainingDays': 200,
          'startDate': 1782777600,
          'endDate': 1790726400,
          'totalItems': 18,
          'usedItems': 0,
          'completionPercent': 0,
          'sections': [
            {
              'tagName': 'Thuốc & Thực phẩm chức năng',
              'items': [
                {
                  'itemId': 'medicine-001',
                  'itemType': BenefitBundleItemType.medicine.value,
                  'name': 'Metformin 500mg',
                  'isUnlimited': 1,
                  'quantity': 0,
                  'quantityUsed': 0,
                  'discountValue': 0,
                  'discountType': 0,
                },
                {
                  'itemId': 'medicine-002',
                  'itemType': BenefitBundleItemType.medicine.value,
                  'name': 'Ozempic 2mg',
                  'isUnlimited': 0,
                  'quantity': 3,
                  'quantityUsed': 1,
                  'discountValue': 15,
                  'discountType': 0,
                },
              ],
            },
            {
              'tagName': 'Thăm khám & Xét nghiệm',
              'items': [
                {
                  'itemId': 'booking-001',
                  'itemType': BenefitBundleItemType.booking.value,
                  'name': 'Tư vấn chuyên sâu với bác sĩ',
                  'isUnlimited': 0,
                  'quantity': 1,
                  'quantityUsed': 0,
                  'discountValue': 0,
                  'discountType': 0,
                },
                {
                  'itemId': 'medicine-purchase-001',
                  'itemType': BenefitBundleItemType.medicinePurchase.value,
                  'name': 'Giao thuốc tận nhà',
                  'isUnlimited': 1,
                  'quantity': 0,
                  'quantityUsed': 0,
                  'discountValue': 0,
                  'discountType': 0,
                },
                {
                  'itemId': 'lab-test-001',
                  'itemType': BenefitBundleItemType.labTest.value,
                  'name': 'Xét nghiệm tại nhà',
                  'isUnlimited': 0,
                  'quantity': 1,
                  'quantityUsed': 0,
                  'discountValue': 5,
                  'discountType': 0,
                },
                {
                  'itemId': 'lab-test-002',
                  'itemType': BenefitBundleItemType.labTest.value,
                  'name': 'Xét nghiệm Gene',
                  'isUnlimited': 0,
                  'quantity': 1,
                  'quantityUsed': 0,
                  'discountValue': 20,
                  'discountType': 0,
                },
              ],
            },
            {
              'tagName': 'Dịch vụ sức khoẻ',
              'items': [
                {
                  'itemId': 'report-001',
                  'itemType': BenefitBundleItemType.report.value,
                  'name': 'Phân tích sức khỏe & Lộ trình cải thiện',
                  'isUnlimited': 0,
                  'quantity': 1,
                  'quantityUsed': 0,
                  'discountValue': 0,
                  'discountType': 0,
                },
                {
                  'itemId': 'dsp-001',
                  'itemType': BenefitBundleItemType.dsp.value,
                  'name': 'Chương trình nền tảng sức khỏe',
                  'isUnlimited': 0,
                  'quantity': 1,
                  'quantityUsed': 0,
                  'discountValue': 0,
                  'discountType': 0,
                },
                {
                  'itemId': 'partner-001',
                  'itemType': BenefitBundleItemType.partnerIntro.value,
                  'name': 'Wecare247',
                  'isUnlimited': 0,
                  'quantity': 1,
                  'quantityUsed': 0,
                  'discountValue': 5,
                  'discountType': 0,
                },
                {
                  'itemId': 'partner-002',
                  'itemType': BenefitBundleItemType.partnerIntro.value,
                  'name': 'California Fitness & Yoga',
                  'isUnlimited': 0,
                  'quantity': 1,
                  'quantityUsed': 0,
                  'discountValue': 20,
                  'discountType': 0,
                },
              ],
            },
          ],
        },
      });
}
