# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    build_app(
      scheme: "Stag.Release",
      xcargs: "-allowProvisioningUpdates FLUTTER_TARGET=lib/main.dart",
      workspace: "Runner.xcworkspace"
    )
    upload_to_testflight(
      skip_waiting_for_build_processing: true,
      beta_app_description: "<CHANGE THIS>"
    )
  end
end
