# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :upload_beta do
    build_app(
      scheme: "Stag.Release",
      xcargs: "-allowProvisioningUpdates FLUTTER_TARGET=lib/main.dart",
      workspace: "Runner.xcworkspace",
      output_name: "Runner.ipa"
    )
    upload_to_testflight(
      skip_waiting_for_build_processing: true,
      skip_submission: true,
      beta_app_description: "Staging: - fixes and improvements",
      ipa: "Runner.ipa"
    )
  end

  desc "Push a new production build to TestFlight"
  lane :upload_prod do
    build_app(
      scheme: "Release",
      xcargs: "-allowProvisioningUpdates FLUTTER_TARGET=lib/main.dart",
      workspace: "Runner.xcworkspace",
      output_name: "Runner.ipa"
    )
    upload_to_testflight(
      skip_waiting_for_build_processing: true,
      skip_submission: true,
      beta_app_description: "Production: - fixes and improvements",
      ipa: "Runner.ipa"
    )
  end
end
