///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CompleteSmartGoalRequest {
/*
{
  "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "type": 0,
  "executeTimes": 0
} 
*/

  String? id;
  int? type;
  int? executeTimes;
  int? appointmentDate;

  CompleteSmartGoalRequest({
    this.id,
    this.type,
    this.executeTimes,
    this.appointmentDate,
  });
  CompleteSmartGoalRequest.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    type = json['type']?.toInt();
    executeTimes = json['executeTimes']?.toInt();
    appointmentDate = json['appointmentDate']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    if (type != null) data['type'] = type;
    if (executeTimes != null) data['executeTimes'] = executeTimes;
    if (appointmentDate != null) data['appointmentDate'] = appointmentDate;
    return data;
  }
}
