///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CompleteExerciseRequest {
/*
{
  "exerciseMovementId": "fe318b9c-788d-4886-beee-08d999c20214",
  "roadmapid": "9938634a-fd6c-47b7-7df7-08d999147edf"
} 
*/

  String? exerciseMovementId;
  String? roadmapid;

  CompleteExerciseRequest({
    this.exerciseMovementId,
    this.roadmapid,
  });
  CompleteExerciseRequest.fromJson(Map<String, dynamic> json) {
    exerciseMovementId = json['exerciseMovementId']?.toString();
    roadmapid = json['roadmapid']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['exerciseMovementId'] = exerciseMovementId;
    data['roadmapid'] = roadmapid;
    return data;
  }
}
