///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CompleteVideoRequest {
/*
{
  "exerciseMovementId": "fe318b9c-788d-4886-beee-08d999c20214",
  "roadmapid": "9938634a-fd6c-47b7-7df7-08d999147edf"
} 
*/

  String? exerciseCategoryId;
  int? duration;

  CompleteVideoRequest({
    this.exerciseCategoryId,
    this.duration,
  });
  CompleteVideoRequest.fromJson(Map<String, dynamic> json) {
    exerciseCategoryId = json['exerciseCategoryId']?.toString();
    duration = json['duration'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['exerciseCategoryId'] = exerciseCategoryId;
    data['duration'] = duration;
    return data;
  }
}
