///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CreateMenuRequest {
/*
{
  "kcal": 0,
  "includeBreakfast": true,
  "includeLunch": true,
  "includeDinner": true
} 
*/

  late int kcal;
  late bool includeBreakfast;
  late bool includeLunch;
  late bool includeDinner;

  CreateMenuRequest({
    required this.kcal,
    required this.includeBreakfast,
    required this.includeLunch,
    required this.includeDinner,
  });

  set setKcal(int value) {
    if (900 <= value && value <= 1100) {
      this.kcal = 1000;
    } else if (1101 <= value && value <= 1300) {
      this.kcal = 1200;
    } else if (1301 <= value && value <= 1500) {
      this.kcal = 1400;
    } else if (1501 <= value && value <= 1700) {
      this.kcal = 1600;
    } else if (1701 <= value && value <= 1900) {
      this.kcal = 1800;
    } else if (1901 <= value && value <= 2100) {
      this.kcal = 2000;
    } else if (2101 <= value && value <= 2300) {
      this.kcal = 2200;
    } else if (2301 <= value && value <= 2500) {
      this.kcal = 2400;
    } else if (2501 <= value && value <= 2700) {
      this.kcal = 2600;
    } else {
      this.kcal = 0;
    }
  }

  CreateMenuRequest.emptyRequest() {
    kcal = 0;
    includeBreakfast = false;
    includeLunch = false;
    includeDinner = false;
  }

  CreateMenuRequest copyWith({
    int? kcal,
    bool? includeBreakfast,
    bool? includeLunch,
    bool? includeDinner,
  }) {
    return CreateMenuRequest(
      kcal: kcal ?? this.kcal,
      includeBreakfast: includeBreakfast ?? this.includeBreakfast,
      includeLunch: includeLunch ?? this.includeLunch,
      includeDinner: includeDinner ?? this.includeDinner,
    );
  }

  CreateMenuRequest.fromJson(Map<String, dynamic> json) {
    kcal = json["kcal"]?.toInt();
    includeBreakfast = json["includeBreakfast"];
    includeLunch = json["includeLunch"];
    includeDinner = json["includeDinner"];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["kcal"] = kcal;
    data["includeBreakfast"] = includeBreakfast;
    data["includeLunch"] = includeLunch;
    data["includeDinner"] = includeDinner;
    return data;
  }
}
