///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CustomWeekList {
/*
{
  "dayInWeek": 0,
  "targetSchedulerId": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
} 
*/

  int? dayInWeek;
  String? targetSchedulerId;

  CustomWeekList({
    this.dayInWeek,
    this.targetSchedulerId,
  });
  CustomWeekList.fromJson(Map<String, dynamic> json) {
    dayInWeek = json['dayInWeek']?.toInt();
    targetSchedulerId = json['targetSchedulerId']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['dayInWeek'] = dayInWeek;
    if (targetSchedulerId != null)
      data['targetSchedulerId'] = targetSchedulerId;
    return data;
  }
}

class CustomScheduler {
/*
{
  "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "repeatTime": 0,
  "repeatType": 0,
  "endDate": 0,
  "targetSchedulerWeeks": [
    {
      "dayInWeek": 0,
      "targetSchedulerId": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
    }
  ]
} 
*/

  String? id;
  int? repeatTime;
  int? repeatType;
  int? endDate;
  List<CustomWeekList?>? targetSchedulerWeeks;

  CustomScheduler({
    this.id,
    this.repeatTime,
    this.repeatType,
    this.endDate,
    this.targetSchedulerWeeks,
  });
  CustomScheduler.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    repeatTime = json['repeatTime']?.toInt();
    repeatType = json['repeatType']?.toInt();
    endDate = json['endDate']?.toInt();
    if (json['targetSchedulerWeeks'] != null) {
      final v = json['targetSchedulerWeeks'];
      final arr0 = <CustomWeekList>[];
      v.forEach((v) {
        arr0.add(CustomWeekList.fromJson(v));
      });
      targetSchedulerWeeks = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (id != null) data['id'] = id;
    data['repeatTime'] = repeatTime;
    data['repeatType'] = repeatType;
    data['endDate'] = endDate;
    if (targetSchedulerWeeks != null) {
      final v = targetSchedulerWeeks;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['targetSchedulerWeeks'] = arr0;
    }
    return data;
  }
}

class CreateSmartGoalRequest {
/*
{
  "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "targetSchedulerId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "name": "string",
  "type": 0,
  "appointmentDate": 0,
  "executeType": 0,
  "executeDayTimes": 0,
  "targetScheduler": {
    "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
    "repeatTime": 0,
    "repeatType": 0,
    "endDate": 0,
    "targetSchedulerWeeks": [
      {
        "dayInWeek": 0,
        "targetSchedulerId": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
      }
    ]
  }
} 
*/

  String? id;
  String? targetSchedulerId;
  String? name;
  int? type;
  int? appointmentDate;
  int? executeType;
  int? executeDayTimes;
  CustomScheduler? targetScheduler;

  CreateSmartGoalRequest({
    this.id,
    this.targetSchedulerId,
    this.name,
    this.type,
    this.appointmentDate,
    this.executeType,
    this.executeDayTimes,
    this.targetScheduler,
  }) {
    this.appointmentDate =
        (DateTime.now().millisecondsSinceEpoch ~/ 1000).toInt();
  }
  CreateSmartGoalRequest.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    targetSchedulerId = json['targetSchedulerId']?.toString();
    name = json['name']?.toString();
    type = json['type']?.toInt();
    appointmentDate = json['appointmentDate']?.toInt();
    executeType = json['executeType']?.toInt();
    executeDayTimes = json['executeDayTimes']?.toInt();
    targetScheduler = (json['targetScheduler'] != null)
        ? CustomScheduler.fromJson(json['targetScheduler'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (id != null) data['id'] = id;
    if (targetSchedulerId != null)
      data['targetSchedulerId'] = targetSchedulerId;
    data['name'] = name;
    data['type'] = type;
    data['appointmentDate'] = appointmentDate;
    data['executeType'] = executeType;
    data['executeDayTimes'] = executeDayTimes;
    if (targetScheduler != null) {
      data['targetScheduler'] = targetScheduler!.toJson();
    }
    return data;
  }
}
