///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CreateMenuRequest {
/*
{
  "kcal": 0,
  "includeBreakfast": true,
  "includeLunch": true,
  "includeDinner": true
} 
*/

  late int kcal;
  late bool includeBreakfast;
  late bool includeLunch;
  late bool includeDinner;

  CreateMenuRequest({
    required this.kcal,
    required this.includeBreakfast,
    required this.includeLunch,
    required this.includeDinner,
  });

  CreateMenuRequest.emptyRequest() {
    kcal = 0;
    includeBreakfast = false;
    includeLunch = false;
    includeDinner = false;
  }

  CreateMenuRequest copyWith({
    int? kcal,
    bool? includeBreakfast,
    bool? includeLunch,
    bool? includeDinner,
  }) {
    return CreateMenuRequest(
      kcal: kcal ?? this.kcal,
      includeBreakfast: includeBreakfast ?? this.includeBreakfast,
      includeLunch: includeLunch ?? this.includeLunch,
      includeDinner: includeDinner ?? this.includeDinner,
    );
  }

  CreateMenuRequest.fromJson(Map<String, dynamic> json) {
    kcal = json["kcal"]?.toInt();
    includeBreakfast = json["includeBreakfast"];
    includeLunch = json["includeLunch"];
    includeDinner = json["includeDinner"];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["kcal"] = kcal;
    data["includeBreakfast"] = includeBreakfast;
    data["includeLunch"] = includeLunch;
    data["includeDinner"] = includeDinner;
    return data;
  }
}
