///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CustomWeekList {
/*
{
  "dayInWeek": 1
} 
*/

  int? dayInWeek;

  CustomWeekList({
    this.dayInWeek,
  });
  CustomWeekList.fromJson(Map<String, dynamic> json) {
    dayInWeek = json['dayInWeek']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['dayInWeek'] = dayInWeek;
    return data;
  }
}

class CustomScheduler {
/*
{
  "repeatTime": 1,
  "repeatType": 0,
  "endDate": 1641003360,
  "targetSchedulerWeeks": [
    {
      "dayInWeek": 1
    }
  ]
} 
*/

  int? repeatTime;
  int? repeatType;
  int? endDate;
  List<CustomWeekList?>? targetSchedulerWeeks;

  CustomScheduler({
    this.repeatTime,
    this.repeatType,
    this.endDate,
    this.targetSchedulerWeeks,
  });
  CustomScheduler.fromJson(Map<String, dynamic> json) {
    repeatTime = json['repeatTime']?.toInt();
    repeatType = json['repeatType']?.toInt();
    endDate = json['endDate']?.toInt();
    if (json['targetSchedulerWeeks'] != null) {
      final v = json['targetSchedulerWeeks'];
      final arr0 = <CustomWeekList>[];
      v.forEach((v) {
        arr0.add(CustomWeekList.fromJson(v));
      });
      targetSchedulerWeeks = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['repeatTime'] = repeatTime;
    data['repeatType'] = repeatType;
    data['endDate'] = endDate;
    if (targetSchedulerWeeks != null) {
      final v = targetSchedulerWeeks;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['targetSchedulerWeeks'] = arr0;
    }
    return data;
  }
}

class CreateSmartGoalRequest {
/*
{
  "name": "Mục tiêu mới 1",
  "type": 1,
  "appointmentDate": 1638238609,
  "executeType": 1,
  "executeDayTimes": 3,
  "targetScheduler": {
    "repeatTime": 1,
    "repeatType": 0,
    "endDate": 1641003360,
    "targetSchedulerWeeks": [
      {
        "dayInWeek": 1
      }
    ]
  }
} 
*/

  String? name;
  int? type;
  int? appointmentDate;
  int? executeType;
  int? executeDayTimes;
  CustomScheduler? targetScheduler;

  CreateSmartGoalRequest({
    this.name,
    this.type,
    this.appointmentDate,
    this.executeType,
    this.executeDayTimes,
    this.targetScheduler,
  });
  CreateSmartGoalRequest.fromJson(Map<String, dynamic> json) {
    name = json['name']?.toString();
    type = json['type']?.toInt();
    appointmentDate = json['appointmentDate']?.toInt();
    executeType = json['executeType']?.toInt();
    executeDayTimes = json['executeDayTimes']?.toInt();
    targetScheduler = (json['targetScheduler'] != null)
        ? CustomScheduler.fromJson(json['targetScheduler'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['name'] = name;
    data['type'] = type;
    data['appointmentDate'] = appointmentDate;
    data['executeType'] = executeType;
    data['executeDayTimes'] = executeDayTimes;
    if (targetScheduler != null) {
      data['targetScheduler'] = targetScheduler!.toJson();
    }
    return data;
  }
}
