///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ExerciseFeedbackRequest {
/*
{
  "exerciseMovementId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "rating": 1,
  "note": "string"
} 
*/

  String? exerciseMovementId;
  int? rating;
  String? note;

  ExerciseFeedbackRequest({
    this.exerciseMovementId,
    this.rating,
    this.note,
  });
  ExerciseFeedbackRequest.fromJson(Map<String, dynamic> json) {
    exerciseMovementId = json['exerciseMovementId']?.toString();
    rating = json['rating']?.toInt();
    note = json['note']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['exerciseMovementId'] = exerciseMovementId;
    data['rating'] = rating;
    data['note'] = note;
    return data;
  }
}
