///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class FoodChangeRequest {
/*
{
  "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "foodId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "portion": 0
} 
*/

  String? id;
  String? foodId;
  double? portion;

  FoodChangeRequest({
    this.id,
    this.foodId,
    this.portion,
  });
  FoodChangeRequest.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toString();
    foodId = json["foodId"]?.toString();
    portion = json["portion"]?.toDouble();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["foodId"] = foodId;
    data["portion"] = portion;
    return data;
  }
}

