///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class LessonFilterRequest {
/*
{
  "type": 1,
  "roadmapId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "tagIdList": [
    "3fa85f64-5717-4562-b3fc-2c963f66afa6"
  ],
  "lessonIdList": [
    "3fa85f64-5717-4562-b3fc-2c963f66afa6"
  ],
  "isCompleted": true,
  "week": 0
} 
*/

  int? type;
  String? roadmapId;
  List<String?>? tagIdList;
  List<String?>? lessonIdList;
  bool? isCompleted;
  int? week;

  LessonFilterRequest({
    this.type,
    this.roadmapId,
    this.tagIdList,
    this.lessonIdList,
    this.isCompleted,
    this.week,
  });
  LessonFilterRequest.fromJson(Map<String, dynamic> json) {
    type = json['type']?.toInt();
    roadmapId = json['roadmapId']?.toString();
    if (json['tagIdList'] != null) {
      final v = json['tagIdList'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      tagIdList = arr0;
    }
    if (json['lessonIdList'] != null) {
      final v = json['lessonIdList'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      lessonIdList = arr0;
    }
    isCompleted = json['isCompleted'];
    week = json['week']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['type'] = type;
    data['roadmapId'] = roadmapId;
    if (tagIdList != null) {
      final v = tagIdList;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['tagIdList'] = arr0;
    }
    if (lessonIdList != null) {
      final v = lessonIdList;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['lessonIdList'] = arr0;
    }
    data['isCompleted'] = isCompleted;
    data['week'] = week;
    return data;
  }
}
