///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class MarkCompletedCalendarRequest {
/*
{
  "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
} 
*/

  String? id;

  MarkCompletedCalendarRequest({
    this.id,
  });
  MarkCompletedCalendarRequest.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    return data;
  }
}
