///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class UpdateQuizLessonRequest {
/*
{
  "lessonId": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
} 
*/

  String? lessonId;

  UpdateQuizLessonRequest({
    this.lessonId,
  });
  UpdateQuizLessonRequest.fromJson(Map<String, dynamic> json) {
    lessonId = json['lessonId']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['lessonId'] = lessonId;
    return data;
  }
}
