///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class UpdateLessonSectionRequest {
/*
{
  "lessonId": "string",
  "type": 1,
  "lessonSectionId": "string"
} 
*/

  String? lessonId;
  int? type;
  String? lessonSectionId;

  UpdateLessonSectionRequest({
    this.lessonId,
    this.type,
    this.lessonSectionId,
  });
  UpdateLessonSectionRequest.fromJson(Map<String, dynamic> json) {
    lessonId = json["lessonId"]?.toString();
    type = json["type"]?.toInt();
    lessonSectionId = json["lessonSectionId"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["lessonId"] = lessonId;
    data["type"] = type;
    data["lessonSectionId"] = lessonSectionId;
    return data;
  }
}