///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class UpdateSharedProfileRequest {
/*
{
  "referalCode": "21iG90",
  "referalCodeType": 3
} 
*/

  String? referalCode;
  int? referalCodeType;

  UpdateSharedProfileRequest({
    this.referalCode,
    this.referalCodeType,
  });
  UpdateSharedProfileRequest.fromJson(Map<String, dynamic> json) {
    referalCode = json['referalCode']?.toString();
    referalCodeType = json['referalCodeType']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['referalCode'] = referalCode;
    data['referalCodeType'] = referalCodeType;
    return data;
  }
}
