///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ZoomTokenRequest {
/*
{
    "roomId": "123",
    "sessionIdleTimeoutMins": "40",
    "sessionPassword": "1", 
    "displayName": "backroom"
}
*/

  String roomId;
  String displayName;

  ZoomTokenRequest({
    required this.roomId,
    required this.displayName,
  });

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['roomId'] = roomId;
    data['displayName'] = displayName;
    data['sessionIdleTimeoutMins'] = '40';
    data['sessionPassword'] = '1';
    return data;
  }
}
